### ISSUE TITLE
Checkbox with link no longer displayed

### ISSUE THREAD

**Issue by castor01** [Octopoos/SEBLOD#104]
Hello,
Once the checkbox has a link (button 2 -> View), it is no longer displayed. 
A description you can find here: http://www.seblod.com/community/forums/general-discussions?task=download&client=intro&file=seb_media_document&id=60325
Best regards

**Comment by klas** [comment]
Checkboxes are not supposed to have be displayed as buttons or have links (except perhaps in label), this is why there is html element button.
