### ISSUE TITLE
Seblod Forum > E-Mail > Included Links

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#113]
The Links in the E-Mail from SEBLOD Forum are duplicated, the reply link opens a blank page and the last ones do not open at all.

Category: Fields & Plug-ins
Reply: How can i create opening hours

Category: Forms & Content Types
Reply: How can i create opening hours

Best Regards,
SEBLOD Team.
www.seblod.com

Follow us on SEBLOD Social Hub
Discuss on SEBLOD Forums

**Comment by klas** [comment]
Move to seblod.com tracker
