### ISSUE TITLE
REGEXP Search to FieldX problem(bug).

### ISSUE THREAD

**Issue by wedal** [Octopoos/SEBLOD#114]
When we need to search in the field FieldX in the SQL-query uses REGEXP. For example:

...... AND t1.introtext REGEXP ("(::art_keyword\\|[0-9]+\\|art_keywords::).*keyword.*(::/art_keyword\\|[0-9]+\\|art_keywords::)") .....

REGEXP is case-sensitive function. As a result, when the user enters "Keyword", and  the database contain "keyword", then the search will return the empty result.

**Comment by sebastienheraud** [comment]
Hi,
REGEXP is not case sensitive, but your issue may be related to the charset/collation used for your table/column. Not able to replicate.
Saba.
