### ISSUE TITLE
Request > Seblod Website > UX

### ISSUE THREAD

**Issue by designbengel** [Octopoos/SEBLOD#116]
When selecting text on seblod Website the characters change color from black to dark blue. It´s hardly to recognize what is selected. In the example img the subline of the first entry is selected.

![bildschirmfoto 2015-09-30 um 12 41 16](https://cloud.githubusercontent.com/assets/828371/10190955/92c9882a-6770-11e5-92a2-7d61275354a5.png)

**Comment by sebastienheraud** [comment]
Hi Elisa,
This is now fixed. Thank you!
And we have a new repo: https://github.com/Octopoos/SEBLOD.com for all reports/suggestions about our websites now.
Regards,
Saba.

**Comment by designbengel** [comment]
great thank you!! way better
