### ISSUE TITLE
problems between Captcha Math  and SD Concat Fields 

### ISSUE THREAD

**Issue by Mineslu** [Octopoos/SEBLOD#117]
Hello,
I have a problem with the SD extension Concat Fields
I have a contact form here:
http://www.aulaideal.com/contactoseblod/

I'm using SD Field Concat to create a single title of articles, like this:
< content > || # fc_nombre #

When not using the Math Captcha Recaptcha or field, the form sends the information correctly and generates a title for my articles For example: 656 Erick

But when I place or Recaprcha Math Captcha field and put a word of incorrect security, the system shows me a text like this:
Error
Wrong security code. Please try again.

...
But beneath the text it appears as follows:
 #fc_nombre# IS A FIELDS

This problem only occurs when you use the field "SD   Concat Field" together with fields "Captcha Math" or  "RE Captcha"

**Comment by klas** [comment]
To be closed, SD concat bug

**Comment by Mineslu** [comment]
@klas This has been fixed in any update?
Thank.

**Comment by klas** [comment]
SD concat is not a SEBLOD product, it was amde ba Simon Downles

**Comment by sebastienheraud** [comment]
Hi
@Mineslu please try to ask on the forum, maybe someone from the community will be able to help.
I'm closing it.
Saba
