### ISSUE TITLE
FieldX::Documentation::How To Set Up This Field

### ISSUE THREAD

**Issue by Bucklash** [Octopoos/SEBLOD#119]
Hi Folks

File in question:
http://www.seblod.com/resources/manuals/archives/seblod-2-x-field-x?tmpl=component

I propose a few changes to the docs loaded from the fieldx config window when a user clicks "HOW TO SETUP THIS FIELD ?". The docs refer to Seblod 2.

1
This first image under the heading SETTINGS. 
Redo the picture, to something along the lines of: 
CUSTOM | Article | new_db_column[field_to_repeat]

2
Change the line at the very bottom in the div.warning:
From: "Please note, use only the storage custom, Article, introtext" for the field "fieldX"."
To: "Please note: 
Fieldx requires storage type: CUSTOM. 
The Object can be whatever you would like ie Article, Category, User, UserGroup, or Free.
The last entry must be the db column where you want to store the fieldx data followed by square brackets("[]") in which you place the field to repeat."

**Comment by klas** [comment]
I have created a new manual, we should link to this manual instead. Old manuals contained some outdated info, mainly about storages
