### ISSUE TITLE
Variation of the field ARTICLE TAGS to HIDDEN breaks all fields of type TAB in the admin form

### ISSUE THREAD

**Issue by narcisob** [Octopoos/SEBLOD#120]
Hello,

If you set the variation of the field ARTICLE TAGS to "Hidden", all fields of type TAB in the admin form don't work and we show only the content of the first tab. No tab label is shown.
I haven't checked in other forms (content, etc.).
Shown in Joomla! 3.4.5 and Seblod 3.7.2

Regards,

Narciso.

**Comment by sebastienheraud** [comment]
Hi Narciso,
This issue has been fixed in SEBLOD 3.8.0.
You can upgrade your sites.
Regards,
Saba.
