### ISSUE TITLE
Sales responses?

### ISSUE THREAD

**Issue by JimboManiac** [Octopoos/SEBLOD#122]
Been thinking of coming back to Seblod as since 2012 when I tested and tried it, it seems (at least you'all say so) it is better and best?

Well, I'm not getting replies from sales fellow James?

**Comment by Octopoos-James** [comment]
Hi Jimbo,

You had sent some emails to my personal email address, which is not the correct channel to get information about SEBLOD.

If you'd like some information before making a purchase on a product for SEBLOD from the marketplace, please use the contact form: http://www.seblod.com/contact

If you'd like some community support, please use the forum: http://www.seblod.com/community/forums

If you'd like assistance with a project, please consider taking a support session: http://www.seblod.com/enterprise/support

Cheers,
James
