### ISSUE TITLE
Content of modal windows in admin does not load

### ISSUE THREAD

**Issue by Lazerproof** [Octopoos/SEBLOD#125]
Hi. 
After updating joomla to 3.4.7 content of all modals does not load.
Here some video about it 
http://recordit.co/oN1KWueTbG

**Comment by sebastienlapoux** [comment]
Hi Lazerproof,
It's certainly the Joomla issue about session bring with the last version Joomla 3.4.7.
Try to log you off and to log you again, just after open again some modal. Do you still have the issue?

Joomla 3.4.8 is planed to fix the session issue.

Thanks.

**Comment by Lazerproof** [comment]
Hi Sebastien.
Yes. Log off helped. 
Thank you.
