### ISSUE TITLE
Exporter does not work with user object

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#131]
A buch of notices plus
Catchable fatal error: Object of class JUserWrapperHelper could not be converted to string in E:\xampp\htdocs\seblod-testing\plugins\cck_storage_location\joomla_user\classes\exporter.php on line 194

**Comment by sebastienheraud** [comment]
Hi Klas,
Fixed here: https://github.com/Octopoos/SEBLOD/commit/9648c6b8df26003ad160b59b9e3df7d883b41383
Thanks,
Saba
