### ISSUE TITLE
Joomla edit button on user content

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#132]
Hi
If you are connected as a manager or admin in front end and display a custom user content (with the user bridge plugin activvated) you are NOT redirected to the right content type when you click on the native Joomla EDIT button.
Actually you are redirected to option=com_cck&view=form&layout=edit&type=wrong_content_type&id=xxx   instead of 
option=com_cck&view=form&layout=edit&type=my_user_type&id=xxx

This is because (I believe) Joomla! / SEBLOD catches the ID of the content and tries to find the proper content type that matches this ID but it only looks into the #__content tabel NOT in the #__users table where it should see.
Is there a way to force the joomla edit buton to find the right user_type ?
thanks
cyril

**Comment by klas** [comment]
Hi,
just one notice - you links option=com_cck&view=form&layout=edit&type=&id=XXX are exactly the same

**Comment by pulsarinformatique** [comment]
Hi 

You are right, I fixed the post.

thanks

cyril

**Comment by sebastienheraud** [comment]
Hi,
Just to keep the ref: http://www.seblod.com/community/forums/general-discussions/joomla-edit-button-on-user-content
Saba.

**Comment by sebastienheraud** [comment]
Hey guys,
Feel free to test the commit: https://github.com/Octopoos/SEBLOD/commit/cd624e70585357d5d66ccb404fdbd6b8aca8f8a0
Thanks,
Saba.

**Comment by pulsarinformatique** [comment]
Yes, thanks it works!
