### ISSUE TITLE
Quick Folder+Top folders options App Root & Featured don't work

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#144]
If you try to change App Root & Featured options it creates an sql error
`Save failed with the following error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN lft + 2 ELSE lft END, rgt = CASE WHEN rgt >= THEN rgt + 2 ELSE rgt END WHE' at line 1 SQL=UPDATE qgd72_cck_core_folders SET lft = CASE WHEN lft > THEN lft + 2 ELSE lft END, rgt = CASE WHEN rgt >= THEN rgt + 2 ELSE rgt END WHERE rgt >`

I presume this happens as this 2 folders don't have any parents, I suggest we disable  App Root & Featured options.

Reference 
http://www.seblod.com/community/forums/forms-content-types/edit-app-folder

**Comment by klas** [comment]
Confirmed, still here.

**Comment by sebastienheraud** [comment]
Hi Klas,
Here is the fix https://github.com/Octopoos/SEBLOD/commit/9b6950e8f1c5e0eb3bc71ac7f13e86601e7b06df
Thanks,
Saba.
