### ISSUE TITLE
GroupX table mode - no buttons

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#148]
No buttons are rendered when groupX is used in table mode.

Reference [http://www.seblod.com/community/forums/fields-plug-ins/table-orientation-groupx](http://www.seblod.com/community/forums/fields-plug-ins/table-orientation-groupx)

**Comment by sebastienheraud** [comment]
https://github.com/Octopoos/SEBLOD/commit/a44b5eaacd02781b481432cfa4b3d6761fdbf67e
