### ISSUE TITLE
#__cck_core database entry not created when warning in Joomla

### ISSUE THREAD

**Issue by jochendaum** [Octopoos/SEBLOD#157]
We have a consistent error on a website, which shows like this:
- The user creates a new content item with a chosen content type. We are experiencing the problem across all content types.
- Accidentally they may enter a title that already exists and an alias is created which already exists
- When saving they get a warning "an item with the same alias already exists in this category". This is a Joomla warning, independent of jSeblod
- Subsequently we find that the content item has been saved, but the __cck_core table entry has not been made.

As a result the item can not be edited, as no jSeblod form/ content type is associated with it.

We have experienced this issue since jSeblod 3.4.1 and it is still present in the current version. I have done some debugging, but cannot find where this happens, so we ended up building a repair routine to solve this problem for us.

**Comment by klas** [comment]
This should be fixed in Seblod 3.9 and after as check has been implemented if alias is unique

https://github.com/Octopoos/SEBLOD/commit/efa6da5d3763225d13aea0920873b4c9432f82e2

**Comment by sebastienheraud** [comment]
I'm closing it.
Thanks.
