### ISSUE TITLE
Importer does not work for any not-only-lowercase columns (and fix)

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#158]
Example problem are sendEmail, registerDate and lastvisitDate - importer does not work for those and other not-only-lowercase columns, problem is in this lines where lowercase is forced for some reason, this lines need to be removed frommodels/cck_imported.php:
`if ( count( $fieldnames ) ) {
			foreach ( $fieldnames as $k=>$fieldname ) {
				$fieldnames[$k]	=	strtolower( $fieldname );
			}
		}`

**Comment by klas** [comment]
test file for import into standard user content type [user_import_test.txt](https://github.com/Octopoos/SEBLOD/files/158640/user_import_test.txt)

**Comment by sebastienheraud** [comment]
Hi Klas,
Thank you for the report. This is fixed in upcoming SEBLOD 3.8.2 and SEBLOD Importer 1.7.0.
Saba
