### ISSUE TITLE
Canel button doesn't cancel all on Firefox

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#159]
Hi

On firefox when we click on the CANCEL button (front end) the selections on the multiple dynamic lists are NOT reinitialized. It works on other browsers though

SO we suggest  the following change on \plugins\cck_field\button_submit\button_submit.php

replace
// $onclick = 'onclick="jQuery(\'#'.$config['formId'].'\').clearForm();"';

with:

$onclick = 'onclick="jQuery(\'#'.$config['formId'].'\').trigger(\'reset\');"';//also works on Firefox

thanks

Cyril

**Comment by klas** [comment]
Which view do you refer to? Please include some instructions to replicate this.

**Comment by pulsarinformatique** [comment]
Hi Klas

it is on the search form 

thanks

cyril

**Comment by klas** [comment]
Did you close by accident?

**Comment by pulsarinformatique** [comment]
Yes, I'm sorry

**Comment by pulsarinformatique** [comment]
Hi, Should I understand this issue is not solved with 3.8.0 please?
thanks

cyril

**Comment by sebastienheraud** [comment]
Hi,
Fixed in upcoming 3.8.1, available here: https://github.com/Octopoos/SEBLOD/commit/65a19026e7bbbe262cad87eb0cce357c8ddf7c2a
Thanks,
Saba

**Comment by pulsarinformatique** [comment]
thanks Saba !
cyril
