### ISSUE TITLE
Сopying labels in several loadposition-L&S-Modules

### ISSUE THREAD

**Issue by Nitische** [Octopoos/SEBLOD#161]
Labels in the head of the table are copying when adding more then one "SEBLOD - List" module to one article using loadposition [my-position]
[http://www.seblod.com/images/medias/35449/_thumb2/seblod.png](http://www.seblod.com/images/medias/35449/_thumb2/seblod.png)
Standart template "Table - seb_table" used

**Comment by klas** [comment]
Can't confirm with Seblod 3.10 - if I put 2 modules in one column I get Module1 / Module 2, the same as with any other field.
