### ISSUE TITLE
Calendar field not translated on the loading of the search form

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#162]
Hi

The calendar field is not automatically translated BEFORE any clicking when used in a search form 

On http://www.dbu.univ-paris3.fr/fr/formations/doctorants-informations-et-inscriptions we had to apply the modification we wrote below unless the date in the form is not translated.

Please notice the problem ONLY occurs on the loading of the search form BEFORE you click on the calendar itself if you put (for example) TODAY as a live value (button 2) on the date field. 

Once you pick a date on the calendar, the date is correctly translated in the field.

On http://www.dbu.univ-paris3.fr/fr/formations/doctorants-informations-et-inscriptions you no longer see the error since we applied the fix we wrote before.

here is the fix 

We just added these lines in the onCCK_FieldPrepareSearch function, line 181 =>
	
	$pattern = "/([[:alpha:]]+)/i"; 
	                        $value = preg_replace_callback($pattern,function($matches){
                                return JText::_($matches[1]);
                        },$value);

Thanks

cyril

**Comment by klas** [comment]
I made a pull to fix this problem together with missing usage of joomla timezone, see pull above

**Comment by sebastienheraud** [comment]
Hi,
Ok so this should be fixed in 3.8.0.
Thanks,
Saba.
