### ISSUE TITLE
Labels put in the templates positions names are not translated

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#175]
Hi

Please check the attached image. Labels put in the templates positions names are not translated
![non-traduit](https://cloud.githubusercontent.com/assets/10794564/14524017/ae45feba-0236-11e6-80b7-21084614ba68.jpg)

thanks

cyril

**Comment by klas** [comment]
Confirmed with Seblod 3.10., still here.

**Comment by sebastienheraud** [comment]
Hello,
Fixed in SEBLOD 3.11
And another minor fix applied in upcoming 3.13
Regards,
Saba
