### ISSUE TITLE
Email field failing

### ISSUE THREAD

**Issue by HarryBosh** [Octopoos/SEBLOD#179]
Using seblod 3.7.2 & joomla 3.5.2
Unable to get the email field to work (joomla test email from global config work ok!)
The form posts ok i recieve a new article,(permissions ok!)
This is a site form

**Comment by klas** [comment]
Using seblod 3.7.2 & joomla 3.5.2 is the reason, you need to wait for seblod 3.8

**Comment by HarryBosh** [comment]
True no Joomla 3.5.2
Using this plugin in the mean time 
http://gruz.org.ua/en/extensions/notificationary.html
