### ISSUE TITLE
Unable to get the uploaded files to show in the article 

### ISSUE THREAD

**Issue by HarryBosh** [Octopoos/SEBLOD#181]
Using seblod 3.7.2 & joomla 3.5.2
Unable to get the uploaded files to show in the article 

Shows 'array'

see -> http://joomla.stackexchange.com/questions/16224/seblod-how-to-show-uploaded-files-in-admin-form

**Comment by klas** [comment]
As I told you before, you can't use seblod with joomla 3.5. yet.

**Comment by klas** [comment]
Also there is no joomla 3.5.2, so please check which version do you use.

**Comment by klas** [comment]
Issue relates to old version that was not compatible with new Joomla relase at the time, To be closed.
