### ISSUE TITLE
Registration message customizaton

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#184]
Hi

We had to hack the plugins\cck_storage_location\joomla_user\joomla_user.php file for the following reasons:
- send the activation email according to the group, not to the Joomla user configuration panel. Depending on the group of the new user, the email is sent or not.
- modify the order of the variables in the email message in the following call:
  
  $body            =    JText::sprintf( 'COM_CCK_EMAIL_REGISTERED_WITH_ACTIVATION_BODY',
                                                            $data['activate'],
                                                            $data['siteurl'],
                                                            $data['username'],
                                                            $data['password_clear']
                                            );

instead of the original call 
 $body   = JText::sprintf( 'COM_CCK_EMAIL_REGISTERED_WITH_ACTIVATION_BODY',
               $data['name'],
                $data['sitename'],
               $data['activate'],
               $data['siteurl'],
               $data['username'],
               $data['password_clear']
            );

Is there another way to customize the activation email without this hack please ?

thanks

cyril

**Comment by pulsarinformatique** [comment]
Hi, no news on this question please ?

**Comment by klas** [comment]
Please use forum for such questions

**Comment by klas** [comment]
To be closed, question for forum.
