### ISSUE TITLE
J 3.5.1 + S 3.8.0 -> Multisite/ Access Problem with Menu items

### ISSUE THREAD

**Issue by pixelneco** [Octopoos/SEBLOD#186]
Hi

System: Joomla 3.5.1 + Seblod 3.8 (fresh installation)

Created Multisites Site A and Site B
Created 2 Menu Items, Menuitem A (Access Site A) Menuitem B (Access Site B)

Problem:

When i go to Site A, Menu A does not appear on first load of the site. After refreshing the browser, Menu A appears. Same with Site B.

Test Environment: 

Macbook (El Capitan); Firefox, Chrome, Safari
iPad; Safari

With J 3.4.8 + 3.7.2 the same structure works fine. 

Best regards

**Comment by sebastienheraud** [comment]
Hi,
I can confirm yes.. we'll have a look tomorrow.
Thank you.
Saba.

**Comment by pixelneco** [comment]
thx a lot for your feedback Saba

**Comment by sebastienheraud** [comment]
Hi !
Here is the fix for the regression: https://github.com/Octopoos/SEBLOD/commit/12f3cade180a9d3f3d57498379d5542535ad3bc1
Could you please have a try?
Thanks,
Saba.

**Comment by pixelneco** [comment]
Hi Saba,

looks good. Tested with same installation and environment without problems :D thx a lot!

best regards

**Comment by sebastienheraud** [comment]
Great !
Thanks 👍 
Saba.
