### ISSUE TITLE
After upgrading to version 3.8.1 broken link Wiew (List Form, back-end site)

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#193]
![2016-05-08_225029](https://cloud.githubusercontent.com/assets/19167244/15100051/11141fc6-1570-11e6-8c63-69a07d071d5a.jpg)

**Comment by sebastienheraud** [comment]
Hi,
Yes, that's currently a downside of the fixes applied to the router.
The purpose is to prevent bad/broken URLs and non-SEF URLs.
We'll see if this can be improved in 3.8.2
Saba.

**Comment by kkaazzoo** [comment]
Thank you, Saba!

**Comment by sebastienheraud** [comment]
Hi,
SEBLOD 3.8.2 is available, and it should fix the issue.
Now routes are supported in the back-end via AJAX.
(you should select the menu item target for the actual/propre route)
Thanks,
Saba
