### ISSUE TITLE
Bug field plugin Address to coordinates

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#194]
Hi, will there be in the future corrected the bug with the Address to Coordinates field?
[http://www.seblod.com/resources/tracker/20977](http://www.seblod.com/resources/tracker/20977)
Sorry for bad English:-)

**Comment by sebastienheraud** [comment]
Hello,
Could you please have a try with this fix (3 files to update)?
https://github.com/Octopoos/SEBLOD/commit/f3fea0cb0f490d5480fd416f2133313fe9fa1953
Please let me know.
Saba

**Comment by kkaazzoo** [comment]
Hi, Saba, unfortunately I can't test the change

**Comment by kkaazzoo** [comment]
It works! Thanks, Saba!

**Comment by sebastienheraud** [comment]
Thanks
