### ISSUE TITLE
Feature Request::Enable live sql query on tag field

### ISSUE THREAD

**Issue by Bucklash** [Octopoos/SEBLOD#197]
Hi
Allowing sql query on tag field would allow the site developer to create tag lists with parent-id of x, or y etc.  

There is no effect with an sql query applied at the minute. 

Tags have limitations and almost nullify their utility.  Having this kind of sql option really opens them up

Thanks :)

**Comment by sebastienheraud** [comment]
Hi Jon,
The Tag field uses the Joomla! JForm Tag class/field... so we can't really allow an SQL query here.
Saba.

**Comment by Bucklash** [comment]
ok.  thanks
