### ISSUE TITLE
Importer erorr with custom key

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#206]
Importer using custom key leads to JTableContent::bind(*NULL*) 

Reference (sample file available there) http://www.seblod.com/community/forums/general-discussions/importer-selection-by-key-custom#post41677

**Comment by sebastienheraud** [comment]
Hi Klas,
Fixed here: https://github.com/Octopoos/SEBLOD/commit/e4d7d23dd32f7535d8f4c39c0bc4b1d385291676
(not related with custom update key but only when there was no field from base/native table)
Fix will be included in upcoming SEBLOD 3.8.2
Saba.
