### ISSUE TITLE
Joomla variations

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#207]
If you use "joomla variations" in the positions of Seb_one template tab on the Site Form, the right border disappears in the browser Fifefox on any Joomla template
![2016-05-26_0941131](https://cloud.githubusercontent.com/assets/19167244/15578211/44852b74-2368-11e6-976c-6c4871cd3cde.jpg)
![2016-05-26_0941332](https://cloud.githubusercontent.com/assets/19167244/15578236/552d0226-2368-11e6-8b47-90f50b1bcf47.jpg)

**Comment by klas** [comment]
I can't reproduce this issue with current Seblod 3.10. 
Probably the problem is in your fields width - fields have too much width for the available space.

**Comment by sebastienheraud** [comment]
Hi kkaazzoo,
Please note the "var_joomla" variation was the one used for Joomla! 2.5.x
It is supposed to be removed from core package in a near future.
One suggestion here would be to display all front-end managers in full-width (without sidebar)
Saba.
