### ISSUE TITLE
Problem with the Select - Dynamic Cascade

### ISSUE THREAD

**Issue by ricoo123** [Octopoos/SEBLOD#208]
Hi,

The problem is that if we set dynamic cascade fields in a search type to filter the second filter is getting in an infinitive loop and the page doesn't stop to reload.

Please let me know if you need more information.

Regards,
ricco

**Comment by klas** [comment]
Confirmedit even gets in a loop with only first one as filter

**Comment by klas** [comment]
Confirmed with Seblod 3.10. and plugin version 1.3.3., still here.

**Comment by Giuse69** [comment]
After 5 months from opening the issue, I hope it Will be fixed soon.

**Comment by sebastienheraud** [comment]
Hi,
Work in progress.. will let you know asap.
Saba

**Comment by sebastienheraud** [comment]
Hello,
Dynamic Cascade Select plug-in 1.3.5 has been released. This issue should be fixed now.
Thanks,
Saba.
