### ISSUE TITLE
The field is jForm-User is not working on the Site Form tab

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#209]
If you select error occurs
![2016-05-30_115505](https://cloud.githubusercontent.com/assets/19167244/15644876/1c9d3040-265e-11e6-8182-f86bff634202.jpg)

**Comment by klas** [comment]
I can't confirm this with joomla 3.5.1 and seblod 3.8.1
Whic joomla and seblod version do you use?

**Comment by kkaazzoo** [comment]
Joomla 3.5.1 and SEBLOD 3.8.1

![2016-05-30_191941](https://cloud.githubusercontent.com/assets/19167244/15655519/8ec0f178-26a6-11e6-899a-a5b0a303e326.jpg)

![2016-05-30_192007](https://cloud.githubusercontent.com/assets/19167244/15655555/cc2959f6-26a6-11e6-9971-34dc28c9e90a.jpg)

The bug appears when setting Search Engine Friendly URLs YES

![2016-05-30_203312](https://cloud.githubusercontent.com/assets/19167244/15655566/f4038708-26a6-11e6-858b-a42a185be478.jpg)

**Comment by klas** [comment]
With SEF on I'm able to confirm it. Same problem appears even with SEF off when filter variation is used in search.

**Comment by sebastienheraud** [comment]
Hi,
Fix merged in 3.8.3
Closing this now.
Saba.
