### ISSUE TITLE
Undefined property in CCKViewVersion

### ISSUE THREAD

**Issue by michaelhq** [Octopoos/SEBLOD#216]
When opening "Version Manager" in Forms & Content Types, the following error message appears:

Notice: Undefined property: CCKViewVersions::$vTitle in C:\xampp\htdocs\experience_1\libraries\cms\cck\base\legacy\view\list.php on line 69.

J3.5.1 & S3.8.2

**Comment by sebastienheraud** [comment]
Hi
Fixed here: https://github.com/Octopoos/SEBLOD/commit/265f216d1031b012238111653abfd1629215d259
Thank you,
Saba.
