### ISSUE TITLE
List & Search Type - Ordering View - "Undefinded index" in helper_workshop.php 

### ISSUE THREAD

**Issue by michaelhq** [Octopoos/SEBLOD#224]
In a new or existing List & Search Type, when selecting view "Ordering" the following errors occurs.

Notice: Undefined index: template in [...]\administrator\components\com_cck\helpers\helper_workshop.php on line 90
Notice: Undefined index: template in [...]\administrator\components\com_cck\helpers\helper_workshop.php on line 93
Notice: Undefined index: name in [...]\administrator\components\com_cck\helpers\helper_workshop.php on line 93
Notice: Undefined index: view in [...]\administrator\components\com_cck\helpers\helper_workshop.php on line 93

SEBLOD 3.8.3
Joomla 3.5.1

**Comment by klas** [comment]
To be closed, this has been fixed.
