### ISSUE TITLE
updater 3.8.3 not adding Manager Apps for Article etc

### ISSUE THREAD

**Issue by creative-resort** [Octopoos/SEBLOD#229]
Hi,
after successfully updating to 3.8.3 from 3.7.x,
the Article, User and Category Managers are missing from the List & Search Types.

I am using Joomla 3.5.1

**Comment by creative-resort** [comment]
Hi @klas 
how can I have these managers added after the fact?

**Comment by sebastienlapoux** [comment]
Hi creative-resort,
You can export into an app and import.
Thanks.

**Comment by creative-resort** [comment]
I'm revisiting this issue, as I'm **not able to see these managers still** 
after updating another site (SEBLOD 3.5.0) even to version 3.10.0

@sebastienlapoux I can't export to an app because it isn't available after an update in the first place.

This is so weird ...

**Comment by sebastienlapoux** [comment]
hi @creative-resort ,
install a new joomla with seblod, then export/import.

**Comment by klas** [comment]
To be closed, this is not a bug.
