### ISSUE TITLE
Plugin import release 1.7.1

### ISSUE THREAD

**Issue by GBob1789** [Octopoos/SEBLOD#233]
Hello
from the 3.8.x version, the log file after importing (plugin import 1.7.1) users is empty.
example : 
`"name"|"username"|"email"|"block"|"groups"|"user_country"|"user_gender"|"utilisateur_organisation"
"NAME Surname"|"loginname"|"email@email.com"|0|"52,171,173,227,228"|"FR"|"M"|"util"`
All the file are correctly created (if it's necessary), but empty. (updated,created,cancelled)
I use Joomla 3.5.1, Seblod 3.8.3, php (5.6 and 7)
best regards

**Comment by GBob1789** [comment]
Hello add comment : 
If I import the same file .csv in **AJAX** mode is ok.

**Comment by klas** [comment]
Confirmed with Seblod 3.10. and importer Version 1.8.1 , still here.

**Comment by sebastienheraud** [comment]
Hello
Good catch!
Please have a try with this: https://github.com/Octopoos/SEBLOD_more/commit/4349a4013e6e3726358cea2233aa74b9429c3d56
Saba

**Comment by GBob1789** [comment]
Hello
After test , it's OK
Thank's Saba

**Comment by sebastienheraud** [comment]
Hi
Cool, thank you!
I'm closing it now.
Saba.
