### ISSUE TITLE
Feature Request: string_truncate in PHP String plugin

### ISSUE THREAD

**Issue by anjoclaudio** [Octopoos/SEBLOD#242]
Would it be possible to add to core PHP String plugin string_truncate feature? It is useful because it lets you shorten text by word rather than by character.
I've implemented this feature by adding || v == 'string_truncate' and copying and renaming substr_count in edit.php
Then in php_string.php file I added:
case 'string_truncate':
$value=JHTML::_('string.truncate', $value, $arg1 );
break;
Thanks
Anjo

**Comment by sebastienheraud** [comment]
Hi Anjo,
Thank you for the feature request.
Now that we have a dedicated repo for all "SEBLOD More" products, I moved the report there:
https://github.com/Octopoos/SEBLOD_more/issues/4
I'm closing this one, and you'll get a reply there.
Saba.
