### ISSUE TITLE
Backend controller and model missing order functions

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#244]
Drag and drop ordering does not work in backend, to fix we can copy saveOrderAjax() function from frontend controller to backend controller and saveOrder function from frontend list model to backend list model.

P.S. alternatively we could just import those functions using magic call method or similar technique to avoid code duplication

**Comment by sebastienheraud** [comment]
Hi Klas,
Here is the commit: https://github.com/Octopoos/SEBLOD/commit/7921cd20a76181a17f756da4e8db5d6ca1b393a5
Thank you.
Saba.
