### ISSUE TITLE
File Upload morph in to File Select

### ISSUE THREAD

**Issue by Bucklash** [Octopoos/SEBLOD#246]
Using Magic amend File Upload to become File Select so that a user can upload a file to a selected location, or select a file previously loaded.

At present a user can upload a file, but if they want to change it they upload a new file. Be great to have the choice :)

**Comment by klas** [comment]
Feature request

**Comment by sebastienheraud** [comment]
Hi,
This capability won't be added to the current "Upload File" field.
One way could be to setup 3 fields: a radio (with conditional states), an upload_file, and a file using this new plug-in we released https://www.seblod.com/store/extensions/602
We also have an alternative way (using a Media Manager) to provide the ability to end-users to upload new files or to select one/many from the library/site (existing items). We'll try to give more info (and to release new products) by the end of the year.
Saba.

**Comment by Bucklash** [comment]
Thanks for the idea :)
