### ISSUE TITLE
Add support $user->email to filed To in Email field

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#248]
Hi!

Please add support `$user->email` for filed **To (Fields)** in Email field for current registered user.

Tnx!

![0000 index](https://cloud.githubusercontent.com/assets/1041797/16900728/dec121e8-4c35-11e6-9430-bf02a733f742.png)

**Comment by klas** [comment]
Feature request

**Comment by sebastienheraud** [comment]
Hi,
The **To (Fields)** parameter allow you to list the name of fields from where email addresses will be retrieved. So you can add the field to the Site Form (and get the email using the Joomla User live plug-in)
Saba.
