### ISSUE TITLE
Not work $cck-> for Email plugin in To (Fields)

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#249]
I'm look this manual Option 7: http://www.seblod.com/resources/manuals/intermediate/triggering-emails

If I'm use mane field `new_useremail` — work perfectly!

But!

If I'm use `$cck->getValue('new_useremail');` — newer send :(

**Comment by klas** [comment]
Just use field_name, I took a look at the code and I would say second option is an error in the manual.

**Comment by klas** [comment]
Manual fixed, I presume this can be closed
