### ISSUE TITLE
File upload field does not validate

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#250]
The validation for file upload fields is not working.
There is no warning/validation tooltip for empty file upload fields on save and the item gets saved.

This old bug from 2013 year!

Tracker: http://www.seblod.com/resources/tracker/8223
Forum: http://www.seblod.com/community/forums/fields-plug-ins/already-set-file-fields-to-be-required-but-isn-t-validated

**Comment by klas** [comment]
Confirmed with Seblod 3.10., still here.

**Comment by sebastienheraud** [comment]
Hello,
Fixed in SEBLOD 3.11. (May 2017)
Regards,
Saba
