### ISSUE TITLE
Warning error and empty 'List & Search Type' with enable Cache (on Render)

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#251]
In the any List & Search Type in tab Configuration enable Cache (on Render).
After reload I have empty page and Warning error:
`Warning: Missing argument 7 for CCK_List::render() in W:\domains\demo.org\libraries\cck\base\list\list.php on line 351`

Tested in:
Seblod 3.8.4
Joomla! 3.5.1 and 3.6.0 (Joomla cache enable and disable too)

**Comment by kkaazzoo** [comment]
I confirmed

**Comment by klas** [comment]
thanks for the report - just a note - warning is not an error, it is a warning. Lower your error reporting level in joomla and it will be gone

**Comment by kkaazzoo** [comment]
Hi, Klas. If it's a minor warning, then breaks down why the list of materials?

That's so right.
![2016-07-22_175749](https://cloud.githubusercontent.com/assets/19167244/17061950/92b568b0-5039-11e6-8036-a532fd268a4b.jpg)

But so wrong

![2016-07-22_175718](https://cloud.githubusercontent.com/assets/19167244/17062311/23511c24-503b-11e6-8ab2-5287cb15fa5e.jpg)

**Comment by joomla-ua** [comment]
In my list with enable Cache (on Render) I have empty list without items.

**Comment by klas** [comment]
Confirmed with Seblod 3.10., still here. I made a PR to fix this.
