### ISSUE TITLE
Multisites: guest user seen as connected

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#255]
With Joomla 3.6.0 and SEBLOD 3.8.4 in a multisite environnement the site related guest user is seen as already connected.
if we create a connection menu link (or a connection module) Joomla! behaves as if the guest user is already connected.

Thanks

cyril

**Comment by pixelneco** [comment]
I can confirm this. The worst part is, that the guest user is able to change the user settings.

**Comment by brainwarp** [comment]
**I do to!** We have the same behaviour since this versions!

**Comment by pulsarinformatique** [comment]
Let's wait for Saba's return to fix this!

**Comment by castor01** [comment]
I can confirm this problem too.

**Comment by sebastienheraud** [comment]
Hello,
Issue confirmed on Joomla! 3.6.0+
Working on a fix. I'll let you test asap.
Thanks,
Saba

**Comment by pulsarinformatique** [comment]
Hi
Will it be a new seblod release or a separate fix please ?
thanks

cyril

**Comment by sebastienheraud** [comment]
Hi,
Here is the fix: https://github.com/Octopoos/SEBLOD/commit/608e552400a04070f64216c280caaf5a96cc17a8
Please have a try and let me know.
SEBLOD 3.9.0 is almost ready, and should be released by mid next week.
Saba.

**Comment by pulsarinformatique** [comment]
Works for me but the autovalidation email doesn't work in a multi sites environment. The autovalidation email is sent with the token but when we click on it we are just redirected to the home page of the site without the message telling the account has been activated.
in the back end the account is still inactive.

Don't know if it's just me nor if it's related to the previous bug

thanks

**Comment by pulsarinformatique** [comment]
Hi
We tested on several sites and we confirm there is STILL an issue on multi sites at the activation level.

The fix you wrote passes the first step: now we can login.

The same (more or less) issue is found again on the account activation level::

If you try to register (with the (AUTO Activation set to yes) you do receive the activation email BUT when you click on the link you are redirected to

index.php?option=com_users&task=registration.activate&token=<token>

as expected

BUT NOTHING happens because
in the \components\com_users\controllers\registration.php file , at line 35 (at the very beginning of the process) , there is a check:

// Check for admin activation. Don't allow non-super-admin to delete a super admin
		if ($uParams->get('useractivation') != 2 && $user->get('id'))
{
			$this->setRedirect('index.php');

			return true;
		}

but at this point, you ARE already logged as the site guest  so you are redirected to index.php WITHOUT the activation !

thanks

**Comment by pulsarinformatique** [comment]
Hi again

yes Saba, that's working!

Thanks a lot!

Cyril
