### ISSUE TITLE
Optimization SQL query for List & Search and filters

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#257]
Hi folk!

Please optimize sql-query for List & Search and filters.

For example with enable debug:
```
AND t0.cck = 'demoform'
AND t1.a_field_1 LIKE '%1%' 
AND t1.a_field_2 LIKE '%0%'
```

If field set as type int() or simple sql-query replace to:
```
AND t0.cck = 'demoform'
AND t1.a_field_1 = '1' 
AND t1.a_field_2 ='0'
```
If you need to optimize, a simple = is way better than a like.

With an = either the string is exactly the same and it's true or it doesn't match and it's false.

With a like, MySQL must compare the string and test if the other string match the mask, and that takes more time and needs more operations.

So for the sake of database, use

`SELECT * FROM 'mytable' WHERE field = "US"`

or

`SELECT * FROM 'mytable' WHERE field = "1"`

**Comment by oliviernolbert** [comment]
Hi,

If "a_field_1" and "a_field_2" in this query:

_AND t0.cck = 'demoform'
AND t1.a_field_1 LIKE '%1%' 
AND t1.a_field_2 LIKE '%0%'_

come from SEBLOD fields you've added in your search, you can change how comparison is made vs value. You can click on button '3' in the search view and change from 'Permissive (default)' to 'Exact'.

Olivier
