### ISSUE TITLE
Email field: email not sent if 

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#258]
HI
 it seems the email field no longer can send emails to the récipients when the TO (fields) is used with plain email syntax. You now have to add #email#

( tested with J3.6.0 and SEBLOD 3.8.4)

it seems the change came with seblod 3.8.3

thanks

**Comment by pixelneco** [comment]
Hi,
tested on a project with two site forms (J3.6.1 + S3.8.4):

1) On one site form both methods did not work (email, #email#). I created a new email field with the exact same settings i had before -> everything fine (with just using email)

2) Second site form -> works fine without any changing

strange...

**Comment by pulsarinformatique** [comment]
Hi again

The problem seems to be related to the Joomla version too!

With J 3.5.1 and seblod 3.8.2 the email is sent without the # tags

WIth the same seblod + joomla 3.6.2 the email is not sent unless you add the # tags

strange again but I confirm there is an issue here

**Comment by klas** [comment]
In the TO (fields) you should enter only fields name without anything else, to fields is meant to list field names like:
field1_name
field2_name
etc.

**Comment by pulsarinformatique** [comment]
yes, I know this but as I wrote in new versions of Joomla / Seblod in some cases you have to write #field_name# !

**Comment by klas** [comment]
Tested and it works correctly for me on seblod 3.84 and joomla 3.6.2 without any # around field names. You can use linebreak, comma or underscore to separate field names.

**Comment by pulsarinformatique** [comment]
No, sorry,  it doesn't and I sent you a private example of it. There must be cases where it really fails

**Comment by pixelneco** [comment]
Hey pulsar,
can you please try this: a fresh new mail-field with your old settings and without any #. It worked for me.

**Comment by pulsarinformatique** [comment]
Hi Pixelneco, I tried but it failed. I had the same result:
if we put NOTHING in the TO (fields) the mail is sent
 if we write fo_contact_email, it doesn't
 if we write #fo_contact_email# the mail is sent again

thanks

cyril

**Comment by klas** [comment]
I checked @pulsarinformatique problem and the issue was in wrong configuration, **To(fields) is meant to use value from some other field**, not from the email field itself. So unless there is another example that is not working I would say no issue here.

**Comment by pulsarinformatique** [comment]
Yes Klas but so far it worked that way and many sites are configured this way. For years we have been using email fields to allow the internet user to receive mail confirmation of his submission. We set the TO (fields) with the field alias and it worked.  Now we must leave it blank or use #xx#. So something really changed...

**Comment by klas** [comment]
Main change was that Joomla is checking email to addresses more strictly since 3.6. It might have worked before, but this is not what this feature is meant for - leaving this field empty is the right way to send email to the address recipient entered.

**Comment by pulsarinformatique** [comment]
Yes but it's not the first time seblod behaviours change without notice. May be it is written in one of the seblod change logs though but I didn't see it. We never understood we had to leave the field empty. We now have to check all our websites

thanks anyway for this confirmation !

**Comment by klas** [comment]
It was always that way http://www.seblod.com/resources/manuals/intermediate/triggering-emails . I would say this worked before for you as joomla just silently dropped your setting, so it was the same as if you had nothing in that field. Since 2.6 joomla checks email settings more closely and if they are not correct email is not sent. 

Issue can be closed IMHO.
