### ISSUE TITLE
Checkbox Dynamic & Multilanguage

### ISSUE THREAD

**Issue by Dgikar** [Octopoos/SEBLOD#261]
When I in "Options Name" and/or "Order By" writing "title_[lang]", the field Checkbox Dynamic is not working. It gives an error. If I write in "Options Name" and/or "Order By" "title_ru" - all OK... Worked...

@klas suggested I posted the issue on github:

> Judging by the code this feature is not implemented in checkbox dynamic. I suggest you open an issue on github tracker.

http://www.seblod.com/community/forums/fields-plug-ins/checkbox-dynamic-multilanguage#post46301

**Comment by klas** [comment]
Bug/ Feature request (implement same functionality as in select dynamic) - [lang] replacement is not done in construction mode, only in free query.

**Comment by sebastienheraud** [comment]
Hi,
This is fixed, and a new version 1.4.0 will be published asap.
Thanks,
Saba.
