### ISSUE TITLE
Language Restriction plugin not working on List Types headers (same column)

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#267]
Hi, the language restriction plugin does not work in List Types headers when the fields are applied to the same column: for example _title_en_ and _title_it_ fields with respective language restrictions, put in the same column of a List Type, they both show in any language.
See also Seblod forum thread: [https://www.seblod.com/community/forums/fields-plug-ins/language-restriction-problem-in-list-view](url)

**Comment by klas** [comment]
Confirmed with Seblod 3.10., still here.

**Comment by sebastienheraud** [comment]
Hello,
Here is a (partial) fix: https://github.com/Octopoos/SEBLOD/commit/523f0ed3d6fa16b189afd668c9844608e8505beb
It will be included in upcoming SEBLOD 3.13 release.
Thanks,
Saba
