### ISSUE TITLE
Video Youtube Field does not work on https-sites

### ISSUE THREAD

**Issue by jwiesel** [Octopoos/SEBLOD#270]
Hi seblod contributors,
I recently changed a site, which uses the **video_youtube** plugin from http to **https**.
Unfortunately the youtube-videos were not displayed anymore after the change.
Reason: Firefox blocks mixed content (http-content embedded in https-sites).
Solution: I updated all youtube URLs in file `plugins/cck_field/video_youtube/video_youtube.php` from `http://` to `https://`
The fix should also work for http-sites. (embedding https in http is fine as far as I know)
Would be great, if you could update the code accordingly. :-)
Best regards

**Comment by sebastienheraud** [comment]
Hi jwiesel,
A new version has been published. Could you please have a try after updating the plug-in:
https://www.seblod.com/store/extensions/40324
Thank you,
Saba

**Comment by jwiesel** [comment]
Hi @sebastienheraud,
I just installed the update. Works like a charm.
Thanks! :-)
