### ISSUE TITLE
Ability to override limit changed after 3.9

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#271]
Before 3.9 it was possible to override limit parameter to show number of items within this limit. Now this doesn't work anymore as pagination value is always applied.

I suspect this is the cause
https://github.com/Octopoos/SEBLOD/commit/ef62ac4404f973e3c17c27e5f300e451a6549901

**Comment by klas** [comment]
More info: with Native setting in pagination, limit now behaves as "pagination page size",otherwise it is just discarded.

**Comment by klas** [comment]
More info: it now only works with with Native setting in pagination and works as "pagination page size", otherwise it is just discarded. Before it worked regardless of what pagination setting was - as an override.

Is there any reason behind this change? Unless it would break something else I would suggest to restore previous behavior.

**Comment by klas** [comment]
Reference https://www.seblod.com/community/forums/lists-search-types/seblod-3-9-0-breaks-limit-override

**Comment by klas** [comment]
Related (fixed?) https://github.com/Octopoos/SEBLOD/commit/af645c3466271e7148cdd20712cf5e4c7c920abe

**Comment by sebastienheraud** [comment]
Hi Klas,

I'm closing this one as overriding the "limit" was never a feature, even if it happened to work on older versions.

With SEBLOD 3.17.2+ (and the latest version of Search Pagination plug-in) it is now possible to let end-users interact with the limit/pagination on the fly.

cf https://www.seblod.com/changelogs#SEBLOD_3172_20190131

Saba
