### ISSUE TITLE
Post-installation Messages for Joomla - bug

### ISSUE THREAD

**Issue by joomleb** [Octopoos/SEBLOD#281]
Hi guys, 
last Joomla 3.6.2 + Seblod 3.10.0, in the Post-installation Messages for Joomla:
when Joomla is selected in the Window I can see "com_cck" insted of "Seblod".
When I select "com_cck", "Seblod" appears...

**Comment by sebastienheraud** [comment]
Hi joomleb,
This commit https://github.com/Octopoos/SEBLOD/commit/5a074ead206b6312ffcc322964bc9aa97546c1c2 adds the missing string in the language file related to the SEBLOD library. It will be included in the next release.
Thank you.
Saba

**Comment by joomleb** [comment]
Well done Saba, 
many thanks!
