### ISSUE TITLE
Field Link: Show Relationship has only the option "Hide"?

### ISSUE THREAD

**Issue by hacki65** [Octopoos/SEBLOD#284]
Is this is the right behaviour? If only 1 option is possible, then the dropdown could be at status disabled.

**Screenshot:**

![seblod-field-link2](https://cloud.githubusercontent.com/assets/20481746/19197204/e16aa14e-8cb8-11e6-88b2-6b1c14152670.jpg)

**Comment by sebastienheraud** [comment]
Duplicate with https://github.com/Octopoos/SEBLOD/issues/284
I'm closing this one.
