### ISSUE TITLE
Custom attributes not working in select dynamic - free mode

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#29]
Select dynamic custom attributes are not working in Free mode, they are always empty like data-sth="". Also interface is behaving wrong, first attribute is initially shown then on toggle first one is hidden and 2-6 are shown.

**Comment by klas** [comment]
Pull for the fix: https://github.com/Octopoos/SEBLOD/pull/28

**Comment by sebastienheraud** [comment]
Fixed. Will be included in upcoming 3.7.0
Thanks.
Saba.
