### ISSUE TITLE
Bag plugin  "Button Free"

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#291]
Hi, field "Button Free" mode "Delete" does not work when the location tab of the Search Form in the forms List & Search Type .
Not removed more materials selected checkboxes using the plugin JGrid
https://www.seblod.com/community/forums/fields-plug-ins/free-button-field-settings-for-delete-article

**Comment by joomla-ua** [comment]
Hi!

Test in Joomla 3.6.2 and Seblod 3.10.1 with Klas fixed. But not work now!

**Comment by doxadigital** [comment]
I build a patch here: https://www.seblod.com/community/forums/general-discussions/delete-button-with-confirmation-not-working#post52016

**Comment by sebastienheraud** [comment]
Hello,
Upcoming SEBLOD 3.11.4 includes the following improvements.
Fix about Free Button: https://github.com/Octopoos/SEBLOD/commit/dee4ed498a7c4c31384fe4b9a17bdbb18761ea31
Fix about Delete Link: https://github.com/Octopoos/SEBLOD/commit/31daefe017e9382a88d89bb96c05b811e59bb660
Regards,
Saba
