### ISSUE TITLE
Error message with SD concat field since Seblod 3.9.0

### ISSUE THREAD

**Issue by paoprod** [Octopoos/SEBLOD#297]
Seen on this topic : https://www.seblod.com/community/forums/fields-plug-ins/sd-concat-field-broken-with-seblod-3-9-0
and met by myself on Seblod 3.10.0 / Joomla 3.6.4
**What ?**
Open a form, create new field, select SD COncat
-> Error message : Oops! Try to close the page & re-open it properly
**How to fix it :** 
Go to /plugins/cck_field/sd_field_concat/tmpl/edit.php
Open file
Find 
`$options2   =   CCK_Dev::fromJSON( $this->item->options2 );`
Change it for : 
`$options2   =   JCckDev::fromJSON( $this->item->options2 );`
**Worked for me...**
maybe this could be done on the plugin to download in Seblod store ?

**Comment by sebastienheraud** [comment]
Hello,
Yes, you are right.
We've just updated SD Concat plug-in on our store.
Thanks.
Saba.
