### ISSUE TITLE
Error decoding JSON data: unexpected end of data

### ISSUE THREAD

**Issue by schekutiev** [Octopoos/SEBLOD#298]
Hi. I use the image field with a detailed description of the image. The descriptions in Russian (Cyrillic). If the description of the image is somewhere more than a hundred characters, I get the following error when saving the content: Error decoding JSON data: unexpected end of data.
As a result, I can not edit the article. It's possible only in Legacy mode

SEBLOD 3.10.0
PHP Built On	Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64
Database Version	5.5.52-0+deb8u1
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.27-0+deb8u1
Web Server	nginx/1.6.2
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by lionelratel** [comment]
Hi schekutiev,
by default, the column type for an upload_image is VARCHAR(255).
When you are using advanced mode on an upload_image, the value, the title and the alt are stored in JSON format in the column.
So in your case, you are definitely above the 255 characters, and the JSON string is cut.

You can increase this limit to VARCHAR(2048) or by changing for TEXT type in the storage of your field. For that, simply edit the field, and on the right of the storage line, click on the "ALTER" checkbox, and change the type.

Regards.
Lionel

**Comment by schekutiev** [comment]
Many thanks, lionelratel, for your prompt and detailed reply!
