### ISSUE TITLE
Bag Select field

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#299]
Hi, in the admin part of the website is not working Select fields in List & Search Type. Seblod 3.10.0, Joomla 3.6.4
![_cr](https://cloud.githubusercontent.com/assets/19167244/19837918/102078d2-9ed5-11e6-8b34-dbc24c68b557.jpg)

**Comment by sebastienheraud** [comment]
Hi kkaazzoo,
Make sure to select "None" as the Position Variation, on the Search Type.
seb_css3 set overflow:hidden, that's why...
If no variation is applied you'll be able to see/select the options.
Regards,
Saba.
