### ISSUE TITLE
Inconsistent translation of select dynamic cascade Select label

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#300]
Select label in Select dynamic cascade is sent directly trough JText, which is not consistent with other implementations where COM_CCK_ or similar are prepended, also JText does not depend on Seblod JText setting (it is always executed)

**Comment by sebastienheraud** [comment]
Hi Klas,
Yep you are right.
It is fixed, and version 1.3.4 will be released asap.
Thanks.
Saba.
