### ISSUE TITLE
Unknown column 'a.admin_form' in 'field list' FROM #__cck_core_types

### ISSUE THREAD

**Issue by jsfernando** [Octopoos/SEBLOD#306]
In the execution of a form with 2 fields of table FREE, when accessing by the front-end or back-end appears the error mentioned in the title above.
I checked in the table #__cck_core_types the admin_form field does not exist.
What's the problem?
I noticed after upgrading to version 3.10, but other sites did not give a problem !?

**Comment by klas** [comment]
Please see https://www.seblod.com/community/forums/general-discussions/error-editing-articles-after-seblod-3-10-update#post49059
