### ISSUE TITLE
Missing language strings in Article & Category Manager

### ISSUE THREAD

**Issue by hacki65** [Octopoos/SEBLOD#313]
I found 2 missing language strings for the pre-installed List & Searchtypes "Article Manager" and "Category Manager".

![missing-string-any-category](https://cloud.githubusercontent.com/assets/20481746/20266490/9158f706-aa76-11e6-9862-efab73f08f44.jpg)

![missing-string-any-parent](https://cloud.githubusercontent.com/assets/20481746/20266498/98416300-aa76-11e6-9528-86ea6027f377.jpg)

Can this be fixed?

**Comment by sebastienheraud** [comment]
Hi,
Here is the fix https://github.com/Octopoos/SEBLOD/commit/11836832009390c283828ba3cc6e41eff25e9c21
Thank you,
Saba
