### ISSUE TITLE
Date field : day and month are switched using d/m/Y date format

### ISSUE THREAD

**Issue by Mat-o** [Octopoos/SEBLOD#317]
Hi,
I found a bug with the date field, but only when using the **d/m/Y date format** in multi-stage forms.
When going from step 1 to 2, then back to 1, the day and the month are switched.

I made [this URL ](http://mat0.odns.fr/pal.createur.pro/test-date-r-w) to show the problem.
1/ use the calendar to input the same date (ex 01/11/2016 and 01-11-2016),
2/ Click Next,
3/ Click Previous,
4/ The first date shows 11/01/2016 (day and month are switched), but the second date is correct, showing 01-11-2016.
This only happens **when "text input" is enabled**.
This doesn't happen when using the d-m-Y format, or with "text input" disabled.

Second bug : choosing a date in which the day is >12th of month makes an error (DateTime::__construct(): Failed to parse time string (14/11/2016) at position 0 (1): Unexpected character).
This also only happens when using the same parameters (d/m/Y date format, and "text input" enabled) the field with the "-" works OK.

I am using pure vanilla Joomla 3.6.4 + Seblod 3.10.0, with default calendar field parameters (except of course with "text input" enabled).
Problem has been reported [here](https://www.seblod.com/community/forums/fields-plug-ins/date-bug-in-multi-page-forms) in the forum (and confirmed by user mlep).

I guess there is a problem with the way the "/" are handled...

**Comment by klas** [comment]
How did you create Back button?

**Comment by Mat-o** [comment]
Hi Klas,
You can have the same result by using the parameters &stage=1 in the URL.
But I can answer you regarding the back button:
- Button Free with Link : Form
- in + window: edition = Yes + 1 (it's the stage number)

I hit this bug in a more complex website and created this demo site just to be able to reproduce the issue with latest & vanilla releases of Joomla and Seblod. And also to report the bug properly.

You can have admin access if needed, but really it is just that simple : the / creates a bug whereas the - does not. And most shockingly (at least to me) only when **"text input" is enabled** in the date field.

**Comment by Mat-o** [comment]
Hi Klas,
You can have the same result by using the parameters &stage=1 in the URL.
But I can answer you regarding the back button:
- Button Free with Link : Form
- in + window: edition = Yes + 1 (it's the stage number)

I hit this bug in a more complex website and created this demo site just to be able to reproduce the issue with latest & vanilla releases of Joomla and Seblod. And also to report the bug properly.

You can have admin access if needed, but really it is just that simple : the / creates a bug whereas the - does not. And most shockingly (at least to me): only when **"text input" is enabled** in the date field.

**Comment by klas** [comment]
I am asking about button as in my opinion problem is in button which contains data from previous form, somehow stored incorrectly. I will investigate.

Meanwhile please try https://github.com/Octopoos/SEBLOD/pull/199 to see if it makes any difference.

**Comment by Mat-o** [comment]
I fail to see how the button can be the cause of this bug:
My point being that when in stage 2, you can write 1 instead of 2 in the URL to get back to stage 1.
No return value involved.
In fact I can remove this button entirely and still get the bug, I just put it there for convenience.

I applied #199 but the bug remains (see online).

**Comment by Mat-o** [comment]
I applied #199, bug is still present.
The back button is just here for convenience but is not needed.
You can just replace stage=2 by stage=1 in the URL to replicate the bug, so no return value is involved.

More info:
In the database, just after a hit on "Next" button (so just after first save), I see:
2016-05-11 00:00:00 for the "date with slash" field and
2016-11-05 00:00:00 for the "date with dash" field.
So date and month are switched before saving the value in the database.

-Mato

**Comment by klas** [comment]
Ok, I'm able to confirm the problem now, but it indeed it happens only if format is d/m/Y (with slashes) - even adding hours and seconds solves the problem.  Also stages are not important - the same thing happens if you edit or display normal saved form. Could be we are hitting some weird joomla or php bug here, I'll investigate further.

**Comment by Mat-o** [comment]
OK... seems too low-level for me to debug.
By the way, I went forward regarding #283, changed the title and posted a demo URL.

**Comment by klas** [comment]
Calendar field currently only works with formats supported by strtotime http://php.net/manual/en/datetime.formats.date.php - if - are used European date format is assumed and if / are used, American format is assumed.

Additionally there is a problem with javascript when text imput is enabled (value is directly copied to hidden field without transformation).

I will make a patch to fix this issues.

**Comment by klas** [comment]
I updated #199 pull to include fix for this problem

**Comment by Mat-o** [comment]
It Works.
Thanks, Klas !

**Comment by klas** [comment]
wow, that was a fast test :)

**Comment by Mat-o** [comment]
Well, I really needed that feature ^^

**Comment by Mat-o** [comment]
There still is a bug with dates, but only when using validation plugin.
It was already there before #199, so I think I should start a specific thread instead.

It is really simple : the date validation plugin found in the store simply doesn't work and/or breaks.
Should I make a new Issue and create a demo page ?

**Comment by klas** [comment]
Hi,
yes please make a new issue, validation plugins are client side javascripts, not related to server side date conversion from this one.

**Comment by Mat-o** [comment]
Created #332 with test/demo URL.

**Comment by klas** [comment]
Please reopen this issue as it is not fixed yet in the main repository

**Comment by Mat-o** [comment]
My mistake, I don't know the release workflow of your software.
I didn't want to be responsible for an open issue, and saw this handy "Close and comment" button...
