### ISSUE TITLE
JCckContent::foreach or forloop::Nesting is Alphabetical

### ISSUE THREAD

**Issue by Bucklash** [Octopoos/SEBLOD#321]
Hi folks...

Creating USERGROUP with JCckContent....

(Not sure if this has ANYTHING AT ALL to do with Seblod....)

... choice of arrays ...
`$arrayIndexed('zebra', 'aadvark', 'dog', 'bear' );`
`$arrayAssociative(0 => 'zebra', 1 => 'aadvark', 2 => 'dog', 3 => 'bear' );`

... choice of loops ...
`for($i=0;$i<$arrayIndexed.length;$i++) {
    $newJCcKContentStuff = new JCckContent( etc....
}`
or
`foreach($arrayAssociative as $k => $v) {
    $newJCcKContentStuff = new JCckContent( etc....
}`

Either way, when the usergroup is created, the nesting is done alphabetically, rather than in the order they are created
I would expect:
`id = 1 | title = 'zebra' | lft = 1 | rgt = 2`
`id = 2 | title = 'aadvark' | lft = 3 | rgt = 4`
`id = 3 | title = 'dog' | lft = 5 | rgt = 6`
`id = 4 | title = 'bear' | lft = 7 | rgt = 8`

But I get:

`id = 1 | title = 'zebra' | lft = 7 | rgt = 8`
`id = 2 | title = 'aadvark' | lft = 1 | rgt = 2`
`id = 3 | title = 'dog' | lft = 3 | rgt = 4`
`id = 4 | title = 'bear' | lft = 5 | rgt = 6`...

Thanks

Jon

**Comment by sebastienheraud** [comment]
Hi Jon,

The tree is automatically rebuilt alphabetically after each new entry. That's on the Joomla! core side.
You'll see the same behaviour while creating using the UI.

I'm closing it now.

Saba

**Comment by Bucklash** [comment]
Ok, thanks :D

**Comment by Bucklash** [comment]
Ok, thanks for checking
