### ISSUE TITLE
Select Dynamic SQL query ignores workflow

### ISSUE THREAD

**Issue by Bucklash** [Octopoos/SEBLOD#324]
Hi Folks

Using a Select Dynamic field SQL query is performed in any workflow setting...
therefore it can causes an error... ie
my current example is in where clause:
WHERE parent_id = $uri->get('id')

When creating the content it generates an error even though workflow is 'edit'

https://www.seblod.com/community/forums/forms-content-types/sql-query-inspite-of-workflow#post50138

**Comment by Bucklash** [comment]
Hi folks

Also, conditionals have no impact, too.

Jon

**Comment by klas** [comment]
I made a PR to fix this, please test.

**Comment by Bucklash** [comment]
Hi Klas

I had a brief go, I did a straight swap,  copy and pasted code from github to my select_dynamic.php file....

But it didn't play well.

See screenshots ...

Also on front end I receive the 'Oops! Template not found.. ; (' message

I have compared my select_dynamic.php to your pr and there are quite a few differences **additional** to the changes you made.....

![current_select_dynamic](https://cloud.githubusercontent.com/assets/5124952/21032975/34453a5e-bde8-11e6-9e7a-122f40df808c.png)
![klas_select_dynamic](https://cloud.githubusercontent.com/assets/5124952/21032974/3444c894-bde8-11e6-8cb3-47425cf679a0.png)

**Comment by klas** [comment]
Hi, sorry, I forgot to set a default for those fields not suing a restriction, it should work now

**Comment by Bucklash** [comment]
Hi Klas

Will try when back from holiday

**Comment by sebastienheraud** [comment]
Hi Jon,
You shouldn't use _$uri->get('id')_.
Try _$uri->getInt('id')_ instead, so you make sure you get something (i.e "0") in return and it won't break the query. I'm closing this one now.
On the other hand, Klas' PR will remain open as this enhancement must be done someday (note: this is not specific to Dynamic Select, but will need to be applied more globally...)
Thanks,
Saba.
