### ISSUE TITLE
Missing Translation "Field Link"

### ISSUE THREAD

**Issue by hacki65** [Octopoos/SEBLOD#325]
The dropdown for the target in field link will not be translated correctly on back- & front-end.
In the formeditor it has the right translation if i edit a field from type link, but if i edit a content in the back- or front-end it grabs the string from the database without translation.

**Editing the field itself in backend:**
![correct-translation-field-link](https://cloud.githubusercontent.com/assets/20481746/20673173/655df5d4-b584-11e6-9d4a-90f0899d4a78.jpg)

**Editing a content in frontend:**
![missing-translation-field-link](https://cloud.githubusercontent.com/assets/20481746/20673183/6c9782fc-b584-11e6-84a0-28111f7c4ab8.jpg)

I have tested with the language overrides for admin and site but no result.

**Comment by sebastienheraud** [comment]
Hello,
Good catch!, and thank you for the details/screenshots.
Here is the fix: https://github.com/Octopoos/SEBLOD/commit/fb6a4e49232217db201e2f5d2ae4e5539e0e6cf2
Regards,
Saba
