### ISSUE TITLE
DE_Translation Manual 'Introducing SEBLOD Templating'

### ISSUE THREAD

**Issue by max123kl** [Octopoos/SEBLOD#328]
Hello,
as I'm just starting with Seblod and english is not so familar as my native german, I plan to translate some manual pages not yet available in german.
So if you are interested to integrate it into your manual pages, feel free to do so.
The attached zip file contains a HTML and a PDF version.

[Uploading Templating_DE.zip…]()

**Comment by sebastienlapoux** [comment]
Hi,
Thanks a lot! But wrong link to download, can you please check?

**Comment by max123kl** [comment]
Sorry, I thougt this is a direckt upload to your site
Here is a download link:
http://zsitetst.bplaced.net/uploads/Templating_DE.zip

**Comment by sebastienlapoux** [comment]
Sounds great! Thanks.

**Comment by max123kl** [comment]
There is a second templating file:
http://zsitetst.bplaced.net/uploads/Drag_and_Drop%20Templating.zip

If there are any suggestions about formating the HTML file, please let me know.

**Comment by max123kl** [comment]
Hi,
I just noticed that my translation is published now. Unfortunately, some bugs coming with.

a) Some special characters (like ä, ö, ü) have the disrupted appearance in my windows environment, within Linux they are visible in the right way. At the other hand former manuals (e.g. https://www.seblod.com/resources/manuals/building-my-first-app/creating-a-contact-form#German) is diplayed well in windows. I cannot see the difference in source code, so check please where is the difference. In the file attached, I marked the named characters. 
http://zsitetst.bplaced.net/uploads/marked.zip
If you have any tip how I can improve the result, let me know.

b) In Drag&Drop manual, first paragraph, the end of the last sentence remains in english.
It should show like this:
... <link to previous manual> definiert, wo wir das seb_one Template betrachtet haben und seine 42 verschiedenen Positionen, denen Sie Felder hinzufügen können.

Last, I prefer my nickname to be published instead of my real name.

**Comment by max123kl** [comment]
I translated the existing 'Playing with Typographies' manual now.
http://zsitetst.bplaced.net/uploads/Playing_with_Typographies.zip

If I have a look at the video, I think that the manual could have a little more further information.

**Comment by max123kl** [comment]
Here is a new manual translated
http://zsitetst.bplaced.net/uploads/Using_Position_Variations.zip

**Comment by agnesfrancomme** [comment]
Hi @max123kl,
The bugs with special characters and the others points have been corrected. 
Thanks a lot for your contribution !

**Comment by sebastienheraud** [comment]
Hello,
Thank you. It seems it was updated on the site.
Closing the issue now. If needed, please re-open.
Regards,
Saba.
