### ISSUE TITLE
Forms submited twice with Edge

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#330]
When forms are submitted using Edge browser, they get saved twice.

Reference https://www.seblod.com/community/forums/forms-content-types/double-entry-under-php-7-with-browser-edge-2#post50332

I can confirm the problem.

**Comment by sebastienheraud** [comment]
Hi Klas,
Here is the fix: https://github.com/Octopoos/SEBLOD/commit/8791ee56553a8a061b0c06dfbb687c27c9ac6b00
Thanks,
Saba.

**Comment by klas** [comment]
User reports it's working ok with the fix, thnx Saba
