### ISSUE TITLE
ColorPicker not working in List & Search Type config

### ISSUE THREAD

**Issue by viocassel** [Octopoos/SEBLOD#334]
ColorPicker not working in the List & Search Type for Validation color styles.

_List & Search Type > Configuration > Validation_

![screenshot_14](https://cloud.githubusercontent.com/assets/3341562/21012158/c2ea1f46-bd65-11e6-9e5d-15c3224fe50b.jpg)

Must be

![screenshot_16](https://cloud.githubusercontent.com/assets/3341562/21012317/7537f43e-bd66-11e6-970c-ca86f19f90b6.jpg)

**Comment by hacki65** [comment]
Confirm !!!

Seems to be that the js will not be loaded.

**Comment by kkaazzoo** [comment]
Confirm.
