### ISSUE TITLE
Bug with cck field jform_associations when creating a content from another one

### ISSUE THREAD

**Issue by raphaelthiry** [Octopoos/SEBLOD#335]
When we use the quickjump action to create a translation of an existing article (from the article manager page for example), the **_$config['id']_** variable that is stored after submitting form is not equal to "0". As a result, even if a new article is created in the #__content table, there is no corresponding item in the #__cck_core table (the system updates the primary content instead of creating a new item).

I fixed this bug by adding this short code on line 167 (plugins/cck_field/jform_associations/jform_associations.php)

```
if ( $config[ 'isNew' ] == 1 )
        {
            $config[ 'id' ] = 0;
        }

```

Tested on Joomla 3.6.4 and Seblod 3.10.0

**Comment by klas** [comment]
What do you mean with "quickjump action" ?

**Comment by klas** [comment]
Or in another words -please give us step-by-step instructions how to reproduce this.

**Comment by raphaelthiry** [comment]
Quickjump action = ability to add a translation from the joomla content manager (using the little arrow in the "status" column). When we click on the title corresponding to the language in which we want to create a translation, we open a page with a pre-filled form. The url of this page contains 2 vars : translate and translate_id...

**Comment by sebastienheraud** [comment]
Hello Raphael,
Tested with upcoming SEBLOD 3.11.4, it should work fine.
If not please re-open after upgrade (available in the upcoming days) with details
Regards,
Saba.
