### ISSUE TITLE
Bug in 'Download this APP'

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#337]
Joomla 3.6.5
Seblod 3.10.0

If download any APP display error massage:
You are not allowed to access this file.

Tested mirror site Joomla 3.6.2 and Seblod 3.10.0 — all good work!

Bug?

**Comment by viocassel** [comment]
Checked. All APPs on my sites downloads fine.
Joomla! 3.6.5
SEBLOD 3.10.0

**Comment by kkaazzoo** [comment]
Not confirmed

**Comment by joomla-ua** [comment]
Please read my fix
https://www.seblod.com/community/forums/general-discussions/bug-in-download-this-app

It's not bug in Seblod!!!
