### ISSUE TITLE
Search and Field X issues

### ISSUE THREAD

**Issue by celius** [Octopoos/SEBLOD#34]
Hi,

The setup:
In form and content type: simple select repeated with field x.

In list and search type: added the simple select field, go to 3 and click +, select permissive and the field x.

The search does not work. I've tried nomerous ways and read all I can find about it. All threads end unsolved - and the ones that are marked solved dosn't solve it.

Just some threads:
http://www.seblod.com/community/forums/fields-plug-ins/can-you-do-a-search-list-on-a-fieldx
http://www.seblod.com/community/forums/fields-plug-ins/fieldx-and-lists
http://www.seblod.com/community/forums/fields-plug-ins/fieldx-and-search
http://www.seblod.com/community/forums/general-discussions/inconsistent-documentation-regarding-storage
http://www.seblod.com/community/forums/lists-search-types/searching-article-with-field-x

I've treid different ways of setting up storage (I've set up new field and not changed storage on an created field) without luck.

Also, the articles, forum posts and tutorials around storage and field x is not telling the same story. They preach different setups.

**Comment by Octopoos-James** [comment]
When you click the + in [3] you need to select your Field X as the "Collection"

**Comment by olivier-at-octopoos** [comment]
Hi Celius,

Should we consider this issue as fixed on your side ?

As this issue is opened for more than 1 month and without feedback from you, we plan to close it in the coming days.

Thanks,
Olivier

**Comment by celius** [comment]
Hi,

Yes, I managed to solve it. I'm not sure how, but I did.

Thanks.
