### ISSUE TITLE
Bug with Joomla cache and Overrides (Live / Variation) in the Item Menu

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#344]
Hi, folk!

I'm enable Joomla! cache.
Create 2 Items Menu List & Search.
Select my Search Type (List).
In tab Overrides (Live / Variation) set category ID for field category.

Result: 
Without Joomla! cache — OK!
With enable Joomla! cache — in 2 Items Menu display information on the one or the other category.

Resume:
Menu item parameters are cached, resulting in incorrectly displayed.

**Comment by klas** [comment]
See https://github.com/Octopoos/SEBLOD/pull/171

**Comment by joomla-ua** [comment]
@klas This not work in latest Seblod and Joomla PHP7

**Comment by klas** [comment]
What kind of problem do you get? Common error when implementing this change is to miss that you need to remove search function completely. The best way to test this is to replace controler.php with https://github.com/klas/SEBLOD/blob/6d68d316fac4ef24230f7500bf8a892891118493/components/com_cck/controller.php

**Comment by joomla-ua** [comment]
@klas this fix work!

Why is not this bug fix in seblod?

Bug fixed 10 Aug 2015!!!!! Today 2017!!!! :)

**Comment by sebastienheraud** [comment]
Hello,
Merged: https://github.com/Octopoos/SEBLOD/pull/171
Saba.
