### ISSUE TITLE
User Registration and Last Visit Dates fields bug when variation set to readonly

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#346]
"User Registration Date" and "User Last Visit Date" fields behave wrongly when edited if the variation is set to Readonly (they should remain untouched):
-) Registration date field is updated to current date/time
-) Last Visit date is blanked.
No problem if the variation is default so that they can be edited (but they shouldn't also in Admin View).

Giuse

**Comment by klas** [comment]
Please check if this pull solves your problem https://github.com/Octopoos/SEBLOD/pull/199

**Comment by Giuse69** [comment]
Yes, this pull seems to solve this problem and also some calendar inconsistencies I was finding :+1:

**Comment by klas** [comment]
Thank you for testing.

**Comment by Giuse69** [comment]
Closing since #199 has been merged into 3.11
