### ISSUE TITLE
SD live does not work when used in form field

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#347]
Works ok when in module
https://www.seblod.com/community/forums/fields-plug-ins/passing-field-values-from-content-to-form#post51271
https://www.seblod.com/community/forums/forms-content-types/prefill-form-module-with-variable-from-content-type

**Comment by klas** [comment]
Fix sent to Seblod as this is commercial plugin.

**Comment by sebastienheraud** [comment]
Hi Klas,
New version has been published on the SEBLOD store
Thank you.
Saba
