### ISSUE TITLE
Alias with digits only doesn't work

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Octopoos/SEBLOD#349]
Hi there! 
I create users of my site with bridge - to create article for each user. Template for Article Name in bridge setting is #user_username#. So, users register with phone number and number is login. Article Names and Aliases also is number. URL for User page is http://site.ru/users/9101234567. The problem is - this URL result is error 404. I go to database and add any symbol to alias - 910-1234567 - URL http://site.ru/users/910-1234567 works.

**Comment by klas** [comment]
I can confirm the problem with urls, same with articles. Works if SEF setting is /id-alias, but not with /alias

**Comment by Ilya-Zhulin** [comment]
Yeah, because of it is minus sign between digits

**Comment by kkaazzoo** [comment]
Сonfirm

**Comment by viocassel** [comment]
Confirm. I have the same problem.

**Comment by sebastienheraud** [comment]
Hello,
It should be fixed with SEBLOD 3.16. Please have a try with the new release.
Thanks,
Saba
