### ISSUE TITLE
address_to_coordinates field incompatibility with seb_map

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#35]
Hi, we're trying to use the cck_field_plugin "address_to_coordinate", but we've got some problems with seb_map because the list AND the field were both loading the google api,...

So we tryed to secure it by checking in the $doc->_scripts if the script we were looking for had not been previously loaded, but here we found out that the field didn't add the api using the $doc->addScripts method, but instead were using JCckDev !

Problem here is that even if we used JCckDev, we don't really know at all how to check the previously loaded script with this method >__<
And, seblod being but one of others joomla extensions, wouldn't it be more secure to use joomla common functions in the purpose to avoid possible library conflicts ?

So, in the end, we used these lines => 
if(!isset($doc->_scripts[$lib])){
                        $doc->addScript($lib);
                }

Have a nice day

**Comment by klas** [comment]
In adress to coordinates field replace
`$doc->addScript( 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places' );`
with
`		$lib = 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places';
		if ( method_exists( 'JCckDev', 'addScript' ) ) {
			JCckDev::addScript( $lib );
		} else {
			$doc->addScript( $lib );
		}

**Comment by pulsarinformatique** [comment]
Thanks,

**Comment by sebastienheraud** [comment]
Hi,
I think this is already fixed in the current/upcoming version.
Could you please try once all new plug-ins/template will be publish on SEBLOD.com, and confirm?
Thanks,
Saba.
