### ISSUE TITLE
Fatal error with smart search - content and form field in content

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#350]
If smart search is set to Content and there is form field in content the following error appears:

`Fatal error: Cannot declare class Helper_Include, because the name is already in use in C:\xampp7\htdocs\seblod-testing\components\com_cck\helpers\helper_include.php on line 14
Call Stack
#	Time	Memory	Function	Location
1	0.2008	396704	{main}( )	...\index.php:0
2	0.2726	3909064	JApplicationCms->execute( )	...\index.php:51
3	0.2726	3909064	JApplicationAdministrator->doExecute( )	...\cms.php:261
4	0.3131	6086576	JApplicationAdministrator->dispatch( )	...\administrator.php:152
5	0.3175	6319640	JComponentHelper::renderComponent( )	...\administrator.php:98
6	0.3197	6430984	JComponentHelper::executeComponent( )	...\helper.php:380
7	0.3200	6455504	require_once( 'C:\xampp7\htdocs\seblod-testing\administrator\components\com_cck\cck.php' )	...\helper.php:405
8	0.3285	6959608	JControllerLegacy->execute( )	...\cck.php:32
9	0.3285	6959608	CCKControllerForm->save( )	...\legacy.php:702
10	0.3305	6989824	CCKModelForm->store( )	...\form.php:60
11	0.3318	7066872	include_once( 'C:\xampp7\htdocs\seblod-testing\libraries\cck\base\form\store_inc.php' )	...\form.php:22
12	0.5112	14762280	JEventDispatcher->trigger( )	...\store_inc.php:253
13	0.5112	14762352	JEvent->update( )	...\dispatcher.php:159
14	0.5112	14762352	plgCCK_Storage_LocationJoomla_Article->onCCK_Storage_LocationStore( )	...\event.php:69
15	0.5112	14762352	plgCCK_Storage_LocationJoomla_Article->_core( )	...\joomla_article.php:317
16	1.0415	16569416	JEventDispatcher->trigger( )	...\joomla_article.php:445
17	1.0416	16569488	JEvent->update( )	...\dispatcher.php:159
18	1.0416	16569488	PlgContentFinder->onContentAfterSave( )	...\event.php:69
19	1.0416	16569800	JEventDispatcher->trigger( )	...\finder.php:38
20	1.0416	16570096	JEvent->update( )	...\dispatcher.php:159
21	1.0416	16570096	PlgFinderContent->onFinderAfterSave( )	...\event.php:69
22	1.0416	16570096	FinderIndexerAdapter->reindex( )	...\content.php:151
23	1.0445	16600680	PlgFinderContent->index( )	...\adapter.php:332
24	1.0459	16653176	FinderIndexerHelper::prepareContent( )	...\content.php:265
25	1.0460	16657056	JEventDispatcher->trigger( )	...\helper.php:483
26	1.0461	16657128	JEvent->update( )	...\dispatcher.php:159
27	1.0461	16657128	plgContentCCK->onContentPrepare( )	...\event.php:69
28	1.0461	16657128	plgContentCCK->_prepare( )	...\cck.php:223
29	1.0505	16699240	plgContentCCK->_render( )	...\cck.php:370
30	1.2025	17588840	JEventDispatcher->trigger( )	...\cck.php:481
31	1.2029	17588912	JEvent->update( )	...\dispatcher.php:159
32	1.2029	17588912	plgCCK_FieldCCK_Form->onCCK_FieldPrepareContent( )	...\event.php:69
33	1.2130	17610232	require_once( 'C:\xampp7\htdocs\seblod-testing\components\com_cck\helpers\helper_include.php' )	...\cck_form.php:67`

In my opinion proper solution is to rename one of helper_include those classes

**Comment by sebastienheraud** [comment]
Hello Klas,
The addValidation() method has moved to JCckDev, and various require_once for Helper_Include have been removed.
https://github.com/Octopoos/SEBLOD/commit/77a94ccda477ada1f600c1467cc6b1738810452a
https://github.com/Octopoos/SEBLOD/commit/7435225018bfc3edf2ec917db4fb83378c60c689
https://github.com/Octopoos/SEBLOD_vip/commit/9b96d6b5742b518ec28a282a63ae45d74af76f87 (protected)
It should fix the issue. One require_once remains in the front-end component's entry point, and will be removed in the next release (after 3.11).
Thanks,
Saba
