### ISSUE TITLE
Parent cck: error on saving

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#351]
With Joomla 3.6.5 + SEBLOD 3.10 when you try to create a new content type that inherits from another, when you save the new content type you get this error :
Oops! Try to close the page & re-open it properly.

Looks this only happens when you have not created any fields in the parent and since tables for the parent ct were not created. Creation of single new field in the parent fixes it.

Cyril

**Comment by sebastienheraud** [comment]
Hi Cyril,
Please have a try with this fix: https://github.com/Octopoos/SEBLOD/commit/543db1667a6db83058a8b588c93b4a564344a9cc
Thank you,
Saba.
