### ISSUE TITLE
Helper_Workshop::getDefaultStyle()

### ISSUE THREAD

**Issue by ralle73** [Octopoos/SEBLOD#354]
Hello im have following prob in my seblod installation:

Too few arguments to function Helper_Workshop::getDefaultStyle(), 0 passed in XXXX\www\administrator\components\com_cck\models\type.php on line 165 and exactly 1 expected

code in line:165    file: \com_cck\models\type.php
$default=Helper_Workshop::getDefaultStyle();

code in line 201  file \administrator\components\com_cck\helpers\helper_workshop.php

public static function getDefaultStyle( $template ) { 

static $styles=array();

if ( !$template ) { 

$template=self::getDefaultTemplate(); }

what must i do to fix this?

thank you for your attention and support
![fehler](https://cloud.githubusercontent.com/assets/25591083/22658035/f65132ea-ec98-11e6-93f3-0d8ebdd9fb17.jpg)

**Comment by sebastienheraud** [comment]
Hello,
Already fixed here: https://github.com/Octopoos/SEBLOD/commit/668e3175ae9ebd5d4198b2f4c69bcbfb8427429e
Thanks,
Saba

**Comment by ralle73** [comment]
Thanks so much - now it works verry well !!!
