### ISSUE TITLE
Data integrity check failed

### ISSUE THREAD

**Issue by adegard** [Octopoos/SEBLOD#359]
HI,
As reported in old track forum "https://www.seblod.com/resources/tracker/6199"
I have the same issues of "Data integrity check failed, you are not allowed to save this item."
suddently appeared when editing forms. 
I tried caching cancelling and disabling SEO glob. setting switching to OFF. 
But again the same error
Someone found a solution?

**Comment by klas** [comment]
​This is not something that would be happening regularly, so it must be something specific to your site. Try disabling any plugins you have installed / caching and try if it happens is you use Joomla tempalte.

**Comment by adegard** [comment]
Hi Klas, Thanks for your answer.
I didn't not install or change anything from 1-2 year... it suddently appear. Template is the same from also a long time. I have Seblod Versione 3.4.2 install on joomla 2.5. Is it possibile to update on Seblod 3.10?

**Comment by step-di** [comment]
К сожалению невозможно одному пользователю одновременно создавать или редактировать несколько материалов принадлежащих к одному ТК в нескольких вкладках браузера. Это не баг, это фича.
Итак, пойдем в файл libraries\cck\base\form\store_inc.php и закомментируем следующий код  

if ( $app->isSite() && ( $hash != $hashed ) ) {
$app->enqueueMessage( JText::_( 'COM_CCK_ERROR_DATA_INTEGRITY_CHECK_FAILED' ), 'error' );
return 0;
}
я например заменил 
if ( $app->isSite() && ( $hash != $hashed ) )  
на
if ( $app->isSite() && ( $hash != $hashed ) and 1==2  )

**Comment by adegard** [comment]
да, ну сейчас, это работает! Спасибо, я должен тебе кофе "(или водка?)
yes, well now, it works! Many Thanks, I owe you a coffee '(or vodka?)
