### ISSUE TITLE
Add custom JavaScript to a site or search form

### ISSUE THREAD

**Issue by drobert99** [Octopoos/SEBLOD#36]
Hi All,
I want to add custom Javascript to my forms - the existing 'conditional states' are too limiting.

I don't want this custom JavaScript available to all pages because it's form specific, so adding a file and changing the template has too broad of scope.

I'd like to see a field in the template or the configuration tab that would allow entry of general JavaScript.  While you are at it, a CSS entry would be nice to... for those fiddling adjustments that are local to one page.

Anyone know enough SEBLOD to do this?

Thanks!
-dr

**Comment by klas** [comment]
This is not support forum, this is issue tracker

**Comment by drobert99** [comment]
It wasn't a support request but a feature request.  Where should those be added now?

**Comment by Octopoos-James** [comment]
This can be achieved using a position override already, and including the javascript and CSS in your override file.
http://www.seblod.com/resources/manuals/designer/overriding-a-position

In a field setup configurations as well you can scroll down and click on the orange down chevron and it opens up some options for adding Javascript and CSS - this will be included on the pages where that field is, essentially solving this issue as well.

**Comment by klas** [comment]
There is already a field for this in code pack http://www.seblod.com/products/1854
