### ISSUE TITLE
user object export: issues with custom fields

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#365]
Hi

Tested on several sites (Joomla 3.6.5 + seblod 3.10)

1- create some custom fields (locked or unlocked) on the user content type. the bridge is not activated

2- fill these fields in admin form

3- export the users with the 1.6.0 SEBLOD exporter (select the object 'user' and the right content type) and select to export all the fields

4- the CSV that is generated has problems with columns: some values are not in the right column

thanks

cyril

**Comment by ViktorIwan** [comment]
Confirmed the bug !

**Comment by ViktorIwan** [comment]
Correction... some part of the export function actually is already build in onto seblod core... pull request sent !

**Comment by sebastienheraud** [comment]
Hello,
PR merged.
Thanks

**Comment by pulsarinformatique** [comment]
Hi
In confirm, it's working! thanks

cyril
