### ISSUE TITLE
List Module: Does Not Output Once I add Group X to Item View

### ISSUE THREAD

**Issue by Bonitto** [Octopoos/SEBLOD#367]
Hi,

So I have a weird issue where I have an Item view template override with seb_minima template and for some odd reason, whenever I add my Group X field to the Item View, the module no longer loads any data. However, when I remove it, I am able to see data when I var_dump( $cck ); in the seb_minima template.

I am not sure if there's a limit to the amount of fields (I literally mean SEBLOD fields and not items) that a Seblod List Module can output but I can't figure out why does the module no longer output if I add my Group X field.

**Comment by Bonitto** [comment]
Ok so from what I have found, there seems so be some sort of limitations with the Intro View. I have a Content Type - Object: None that is meant to just hold a group of fields for Group X. My Group X field is set to be repeated up to 21 times, however I am able to confirm that my List Module will only output if I have no more than 7 repeated fields that have been entered. Once I get to my saving my 8th repeated field, var_dump($cck) no longer shows any data. I have debugging turned on and can confirm that the db query doesn't change so I am unsure as to what is the problem.
[Here is a snapshot for the fields that I have in my Intro View](https://trello-attachments.s3.amazonaws.com/5524009de42fade8035f9cf8/58c621163424b942fc239ec3/82c54e1610c438882f1ee84221e2dd52/dept_hrs_intro_view.png). Please note that all of the fields in this view have their storage set to unlocked and follow the principles discussed here: https://www.seblod.com/community/forums/fields-plug-ins/field-x-my-learning-process-shared-2#post52114

**Comment by klas** [comment]
Intro view is mainly used by some Joomla native views, why don't you add your fields into list/item view of your list type?

**Comment by klas** [comment]
This was caused by an override
