### ISSUE TITLE
Values Property For Group X Does Not Work

### ISSUE THREAD

**Issue by Bonitto** [Octopoos/SEBLOD#368]
Your documentation or tutorial (here: https://www.seblod.com/resources/tutorials/calling-field-x-and-group-x-content-in-an-override) states that you can use the values property to access/loop through Group X and Field X fields. Bucklash and I have confirmed that the values property does not work, however the value property does.

**Comment by klas** [comment]
That was an error in the manual, ​manual was corrected, values only applyto beforeStore and afterStore code events, not to overrides.

**Comment by Bonitto** [comment]
Ok thank you for the update
