### ISSUE TITLE
Multi sites and access on front end forms

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#369]
Hi

Here is a problem we saw on all our seblod multi sites: 

* create a multi sites project (SITE1 and SITE2)
* each site comes with its ACLs
* create a contact form for site1
* put the article access field in the front end form 
* in (2) force the access level to any value you try (site1-registered for instance)

--> whatever dynamic value you set, the access level will be reset to the site public access level (site1).

The only way I succeeded in forcing the access level is to use a conditional state on a condition that is always true

Thanks 

cyril

**Comment by klas** [comment]
Are you saying that live value is not used on access level field on multisites?

**Comment by pulsarinformatique** [comment]
Hi Klas
Not live values in general (I don't know franckly) but live value on the Article Access field in a multisites project as I described.
We tested it on 3 different projects with the same result.

thanks

cyril

**Comment by sebastienheraud** [comment]
Hello,
Fixed here: https://github.com/Octopoos/SEBLOD/commit/fa3a2f00b13bf75c5b014c4eaf48fa7972bcf54e, alongside with another improvement.
Regards,
Saba

**Comment by pulsarinformatique** [comment]
Thanks Saba

cyril
