### ISSUE TITLE
Search by Tag for custom content type has SQL error

### ISSUE THREAD

**Issue by thebeuving** [Octopoos/SEBLOD#37]
## Steps To Reproduce
1. Create a content type with that uses article tags
2. Create a search/list view that allows you to search using article tags
3. Create a menu item that goes to that search/list view
4. Add a few articles of the new content type
5. Go to the new menu item on the frontend and attempt a earch

## Expected behavior
1. it should bring up all the results that match the search

## Actual Results / Error message. 
A Joomla error page with this message:
Unknown column 't1.tags' in 'where clause' SQL=SELECT t0.id AS pid,t0.pk AS pk,t0.pkb AS pkb,t0.cck AS cck,t0.storage_location AS loc,tt.id AS type_id,tt.alias AS type_alias FROM `j_cck_core` AS t0 LEFT JOIN `j_content` AS t1 ON t1.id = t0.pk LEFT JOIN `j_cck_core_types` AS tt ON tt.name = t0.cck WHERE t1.state = 1 AND t1.access IN (1,1,5) AND ( t1.publish_up = '0000-00-00 00:00:00' OR t1.publish_up <= '2015-03-18 20:49:59' ) AND ( t1.publish_down = '0000-00-00 00:00:00' OR t1.publish_down >= '2015-03-18 20:49:59' ) AND t0.cck = 'test' AND t1.tags LIKE '%%' GROUP BY t0.pk ORDER BY t1.title ASC

**Comment by lionelratel** [comment]
Confirmed.
Searching the solution.

**Comment by klas** [comment]
Workaround until this is fixed: http://www.seblod.com/resources/tutorials/workaround-for-search-by-tag-issues

**Comment by sebastienheraud** [comment]
Klas' PR merged.
Closing this report.
Thanks,
Saba.
