### ISSUE TITLE
 inherit the permissions is only available to content types

### ISSUE THREAD

**Issue by helgator** [Octopoos/SEBLOD#372]
Currently inheritance of the permissions is only available to content types but should be to categories, like Joomla native.

Example: I have 2 categories. In A the user is not allowed to edit, in B his is allowed.
I have a content type X and an article of that content type X.
Depending on the category the article is in, the permissions of the category should be applied. Which is the way native Joomla content works.

In Joomla the articles inherit the permissions from the category, not so in SEBLOD. I think SEBLOD should behave like native Joomla.

**Comment by klas** [comment]
In my opinion category is just a way to categorise content, it should not have any implications on permissions, the same as tags don't, so it is Joomla who is doing it wrong, not Seblod.

**Comment by helgator** [comment]
Appart from that SEBLOD is a component for Joomla and not the other way arround hence it should act like being part of the mother system, how do you propose permissions should be applied to content if not via categories?

**Comment by klas** [comment]
In Seblod, permissions can be applied on component level, on content type and on individual fields. Joomla does not have content type level or field level, so the 2 can't work exactly the same in any case. 

Please note all written here this is just my opinion.

**Comment by helgator** [comment]
"Please note all written here this is just my opinion."
 > noted, so who in the end decides if a bug gets solved?

"In Seblod, permissions can be applied on component level, on content type and on individual fields" 
> very good, but that should not destroy the native CMS behavior seblod is built upon, from a workflow perspective, that is a major bug

**Comment by sebastienheraud** [comment]
Hello,
To complete what Klas said, I will add the following.
In most cases, permissions from the content type are enough to meet the needs, that is why it has been designed like that.
Of course in a few cases, you need to apply both (content type + categories) and indeed currently content/category are not applied natively by the core, but you can choose to do it manually, using 

SEBLOD Break
https://www.seblod.com/store/extensions/25892
Joomla! ACL Pack
https://www.seblod.com/store/extensions/10872
(cf screenshot)
<img width="624" alt="joomla-permissions-restriction" src="https://cloud.githubusercontent.com/assets/1101317/23900796/c99572aa-08ba-11e7-8e99-0d9d084f4322.png">

Regards,
Saba.

**Comment by helgator** [comment]
Thank you for the hints but I still consider something being a bug when you install a component (here seblod) and the CMS looses functionality. That should not happen hence it is a bug. And secondly the seblod plugins do not provide the same functionality as the Joomla permissions on categories, plus you have to do a lot of work setting permissions on each single content type - in my case 2 content types with each consisting of 30 fields ... I cant use the break since that would destroy the order of the fields which need to be ordered in a useful way.
Therefore please consider resolving this issue and let Joomla work as expected.

**Comment by sebastienlapoux** [comment]
@helgator, please be sure of what you write before to do it.

You can always disable SEBLOD on Joomla Category and Article. Nothing is broken!
Joomla has none notion of content type. And permissions on content type are lot more important than on category.

About permission on content type, it's not concerning your number of fields but the content type only (on fields it's about access view!). Please click on the blue arrow then on permission button.
![image](https://cloud.githubusercontent.com/assets/13470265/23938056/e5bf62e2-095a-11e7-825b-ff80bb9a1105.png)

Thanks.

**Comment by klas** [comment]
Yes, as @sebastienheraud suggested you can use break plugin to hide all fields.  

If you add Redirection plugin to the mix https://www.seblod.com/store/extensions/40381 you can get almost exactly the same behaviour as with Joomla (redirect and display message if user is not authorized). 

Please note permission restriction plugin from ACL pack DOES use category permissions.

**Comment by helgator** [comment]
Thanks for the hint but that is not what I am talking about. Again: I have articles made of two content types sitting in 5 different categories which need to be set to be editable to different user groups - depending on the category, not on the content type. Why would you say that permissions on content type are "a lot" more important. No, they are not, not in my project anyway and I guess not to anybody who organises content in categories.
"You can always disable SEBLOD on Joomla Category and Article." >>> what exactly does that mean and how does that work? Why would I install and set up seblod only to disable it later on?

**Comment by klas** [comment]
Please read my answer, you can get what you need, plugin from acl pack uses category permissions.

**Comment by helgator** [comment]
@klas "permission restriction plugin from ACL pack DOES use category permissions" >>> that is good news. But would it not be better UX to just adopt the Joomla way and take the Joomla category settings into account instead of the user having another additional plugin to set up?
Anyway I will try that plugin then and see, thanks.

**Comment by klas** [comment]
I made s short tutorial https://www.seblod.com/resources/tutorials/how-to-apply-category-permissions

**Comment by helgator** [comment]
that is very helpful, thanks
