### ISSUE TITLE
conditions with radio buttons do not work

### ISSUE THREAD

**Issue by helgator** [Octopoos/SEBLOD#374]
reproduce:

- set up a radio group with 4 buttons in a content type
- set up a textfield that will be conditioned by the radios
- set conditions on the radios: textfield > show for the first 2 radios, > hide for the last two radios
- go to the frontend and check that the conditions work

expected:

- condrions are applied

actual:

- only the 2nd and the 4th button control the condition
- confirmed by Klas in [the forum](https://www.seblod.com/community/forums/fields-plug-ins/conditional-with-select)

**Comment by sebastienheraud** [comment]
Hello,
Not able to replicate.

If you set up only the first condition (show for the first 2 radios) = it works as expected.
If you set up both conditions (or more than one condition for the same field) you need to disable the "Auto Revert" option.

_AUTO REVERT: by default, if a conditional statement (trigger side) is not met,
the reverse state will be activated automatically. You can choose to disable it
using the suitable checkbox, and thus setup each state manually._

Regards,
Saba.
