### ISSUE TITLE
cancelled.csv contains only the heading but no data

### ISSUE THREAD

**Issue by helgator** [Octopoos/SEBLOD#376]
When items cant be imported they should appear in cancelled.csv but that file is empty and so is updated.csv.

**Comment by klas** [comment]
Did you try changing output mode and folder settings (in component configuration) ?

**Comment by klas** [comment]
I can confirm this problem with 1.8.1. (last one available for download), same problem with created and updated csv

**Comment by sebastienheraud** [comment]
Hello,
It has been fixed here: https://github.com/Octopoos/SEBLOD_more/commit/4349a4013e6e3726358cea2233aa74b9429c3d56, but not released yet.
Saba.

**Comment by klas** [comment]
Thnx Saba - I did look in commits but haven't noticed this one. I can confirm it fixes the issue.
