### ISSUE TITLE
SEB_map error with PHP 7.1.2

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#378]
Hi

seb_map crashes with PHP 7.1.2 while it works with php 7.0 

With PHP 7.1.2 we get the error message:

0
Erreur: 0
Cannot use object of type stdClass as array

Thanks

Cyril

**Comment by sebastienheraud** [comment]
Hello,
I guess this has already been fixed.
Closing it now. Please re-open if needed.
Regards,
Saba.
