### ISSUE TITLE
Article Access Level Seblod Multi site

### ISSUE THREAD

**Issue by antonio92cop** [Octopoos/SEBLOD#379]
Hello,
I have 2 sites:
SITE A with ACL (SITE A, SITE A GUEST, SITE A ADMINISTRATOR)
SITE B with ACL(SITEB, SITE B GUEST, SITE B ADMINISTRATOR)
When I login into backend SITE A and create an article... The Access article contains ACL of site A and site B.
Is possible show only ACL of site A. ??
Thanks

**Comment by sebastienlapoux** [comment]
No support by Git. Please use https://www.seblod.com/community/forums.
Thanks
