### ISSUE TITLE
500 error on form parent != ''

### ISSUE THREAD

**Issue by PierreCorell** [Octopoos/SEBLOD#380]
Hello Octopoos and friends,

Joomla! 3.6.5
SEBLOD 3.10.0b
PHP 7.0.14-nmm1
Browser: Google Chrome Version 57.0.2987.133 (64-bit)

I found a possible bug in the backend form creation form, It depends on any selection of a parent formtype. I checked in various types (just with adminform), with a new form and with existing ones. Errormessage is "Oops! Try to close the page & re-open it properly." as you can see in the enhanced screenshot.
If I deselect the parent to 'none' and save the form again, all is fine again.

Enhanced you find the webinspector har document (renamed to txt to get it uploaded here) - I just changed the real url with mysite.com

Best regards, 
Pierre.

![screenshot-2017-04-20_seb-error](https://cloud.githubusercontent.com/assets/3313934/25222970/4b758c26-25ba-11e7-9aa3-7ea337a9d34f.png)

[seblod_issue-formInherit.txt](https://github.com/Octopoos/SEBLOD/files/941882/seblod_issue-formInherit.txt)

**Comment by sebastienheraud** [comment]
Hello Pierre,
Thanks for the report.
Please have a try with this fix. It should work fine: https://github.com/Octopoos/SEBLOD/commit/543db1667a6db83058a8b588c93b4a564344a9cc
(already included in the upcoming SEBLOD 3.11 :))
Regards,
Saba.

**Comment by PierreCorell** [comment]
Oh perfect, thank you Saba - I didn't found a ticket at a fast search.
best regards, Pierre.
