### ISSUE TITLE
A Tale of 2 Accordion Lists in the Same Content View

### ISSUE THREAD

**Issue by Bonitto** [Octopoos/SEBLOD#381]
I referenced this problem [in the SEBLOD forums](https://www.seblod.com/community/forums/lists-search-types/problem-a-tale-of-2-accordion-lists-in-the-same-content-view#post52668). I am posting here because this should be fixed for the community.

**Problem:** 
I have an issue where I am using 2 accordion list templates in a the same Content View. The problem is that the first accordion template conflicts with the second where they both share the same anchor tag id. 

Therefore when you click on the second accordion template's items, it opens up the items of the first.

**Solution:**
I have found a possible solution by manipulating the accordion template's index.php file (located in /templates/seb_accordion/index.php) on line 81 and concatenating the $accordion_id variable in addition to it's loop value ($i).

I believe this should provide enough uniqueness where more than one accordion list won't share the same anchor tag id. 

Here's the following code below for anyone that ends up running into this issue.

`$slide=JHtml::_( 'bootstrap.addSlide', $accordion_id.'_accordion', $heading, $accordion_id .'_collapse_' .$i++ );`
You will also need to modify the line of code that will leave the first accordion group element active on line 34.

`$params	=	( $active ) ? array( 'active'=> $accordion_id . '_collapse_0' ) : array();`

**Comment by sebastienheraud** [comment]
Hi,

Fixed in upcoming version.
It should be released when we'll launch SEBLOD 3.17 (Sep. or Oct.)

Regards,
Saba

**Comment by sebastienheraud** [comment]
Hi,

It should work fine with the latest version, released today alongside SEBLOD 3.17:
https://www.seblod.com/community/blog/new-release-seblod-3-17-0

Saba.
