### ISSUE TITLE
Content - SEBLOD plugin conflict with latest EasyBlog 5.1.5

### ISSUE THREAD

**Issue by sparkosis23** [Octopoos/SEBLOD#382]
After updating StackIdeas' EasyBlog component from version 5.0.44 to 5.1.5, the blog page on frontend returns "Error: 0 - Call to a member function set() on string" 

I disabled some plugins and found when I disable Content - SEBLOD plugin the blog page works as expected.

Support ticket with StackIdeas suggests the Content - SEBLOD plugin code doesn't add a proper check whether the param really received the value or not. See StackIdeas forum post at https://stackideas.com/forums/easyblog-5-1-x-conflict-with-seblod-content-plugin#reply-332296

In /plugins/content/cck/cck.php :

```
public function onContentBeforeDisplay( $context, &$article, &$params, $limitstart = 0 )
{ 
        if ( JCck::getConfig_Param( 'hide_edit_icon', 0 ) ) { 
                  if (isset($article->params)) { 
                      $article->params->set( 'access-edit', false ); 
                   } 
       } 
       return ''; 
}
```

Replace with the following fixes the problem:

```
public function onContentBeforeDisplay( $context, &$article, &$params, $limitstart = 0 )
{ 
        if ( JCck::getConfig_Param( 'hide_edit_icon', 0 ) ) { 
                 
                   if (isset($article->params) && $article->params) {
                      $article->params->set( 'access-edit', false ); 
                   } 
       } 
       return ''; 
}
```

This was also reported to SEBLOD forum at https://www.seblod.com/community/forums/general-discussions/content-seblod-plugin-conflict-with-latest-easyblog-5-1-5#post52810

**Comment by sebastienheraud** [comment]
Hello,
Thank you for the report.
Please have a try: https://github.com/Octopoos/SEBLOD/commit/385c87efa1b9176584cfe6a454475cb4f9308777
Regards,
Saba

**Comment by sparkosis23** [comment]
I tested the modified code provided and it works for me. EasyBlog pages now display correctly.

**Comment by sebastienheraud** [comment]
Thanks.
