### ISSUE TITLE
Edit articles in featured view

### ISSUE THREAD

**Issue by cladellas** [Octopoos/SEBLOD#383]
When you edit an article from featured view in menu sidebar (in content articles left), article opens as Joomla article, opening it from articles is displayed well, can be configured to allow editing articles in featured view also?

Edit as Seblod
index.php?option=com_content&view=articles

Same article edit as Joomla in
index.php?option=com_content&view=featured

Thanks,

**Comment by klas** [comment]
Works ok for me with seblod 3.7

**Comment by Verloc17** [comment]
Same problem

Edit via Menu -> Content -> Articles works fine
URL: index.php?option=**com_cck**&view=form&return_o=content&type=article&id=

Edit via Menu -> Content -> Featured Articles shows cck salad
URL: index.php?option=**com_content**&view=article&return=featured&layout=edit&id=1682

Seblod Version: 3.11.2
Joomla Version: 3.7.2

**Comment by sebastienheraud** [comment]
Hello,
Fixed here: https://github.com/Octopoos/SEBLOD/commit/23915ac6ffca5aac567092cb28f096a43c45d09c
It will be included in upcoming SEBLOD 3.11.4 release
Thanks for reporting!
Saba
