### ISSUE TITLE
Field Add Save not working

### ISSUE THREAD

**Issue by LazybonesMungo** [Octopoos/SEBLOD#40]
I am unable to save new fields. If I disable the field name availability check (by removing the validate class from the form field using browser dev tools) I am able to save normally.

This bug appears in Safari, Chrome and IE. If I click Save twice quickly in IE the field is saved normally.

This appears to be a Javascript problem of some sort. Somehow the availability check is interfering with the form post.

Merci beaucoup mes amis.

Joomla! 3.4.1 Stable, Seblod 3.5.1, PHP 5.6.3, MySQL 5.6.21

**Comment by Octopoos-James** [comment]
Hi,

This should be posted in the forum please: http://www.seblod.com/community/forums

To try and help quickly: please update your SEBLOD version to 3.6.2 first. Second, please check max_input_vars is set sufficiently high on your server.

James

**Comment by olivier-at-octopoos** [comment]
Hi LazybonesMungo ,

Have you had a chance to check what James mentioned ?

As this issue is opened for more than 1 month and without feedback from you, we plan to close it in the coming days.

Thanks,
Olivier

**Comment by LazybonesMungo** [comment]
Sadly the original poster has died of old age. His relatives would like to pass on their thanks for your response.

**Comment by olivier-at-octopoos** [comment]
We are sad to hear this news and are sorry for your loss. Our condolences.
