### ISSUE TITLE
Feature Request: Copressed Seblod .js Files

### ISSUE THREAD

**Issue by designbengel** [Octopoos/SEBLOD#41]
Hello! 
For SEO i need to compress the seblod .js files, but with standard tools there are always conflicts then.
It would be great to have a possibility to compress the seblod   *.js files.

**Comment by Octopoos-James** [comment]
Hi Elisa,

This functionality is available in a SEBLOD add-on that will be released in future (sorry I can't give you a date at this time). It's currently in alpha testing.

James

**Comment by sebastienheraud** [comment]
Closing this.
We'll try to publish this add-on asap.
Saba.
