### ISSUE TITLE
Small bag css

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#411]
Hi! A small error in the css in the Fulltext field in the default Article content type, on the Admin tab Form. The field name moves editor menu to the right.
![2017-05-11_194818](https://cloud.githubusercontent.com/assets/19167244/25963320/85c2d9e4-3689-11e7-8b2e-0ade7e014f8e.jpg)

**Comment by joomla-ua** [comment]
This bug in SEBLOD 3.11.0 and J! 3.7.x?
Back-End or Front-End?

**Comment by kkaazzoo** [comment]
Yes, a clean installation of Joomla 3.7.x and Seblod 3.11, back-end

**Comment by kkaazzoo** [comment]
Clarify, the bug is in all content types where the field is applied Wysiwyg Editor.

**Comment by sebastienheraud** [comment]
Hello,
Thanks for the report.
Quick fix: https://github.com/Octopoos/SEBLOD/commit/2ad1c8866abe2c99cbc7f90c1935c12503df5320
Saba.
