### ISSUE TITLE
editor CodeMirror disables modal in list types

### ISSUE THREAD

**Issue by helgator** [Octopoos/SEBLOD#414]
reproduce:
- set CodeMirror as default editor
- in a List & Search Type edit the description

expected:
- possible to enter text and save

actual:
- possible to enter text, save not possible

**Comment by sebastienheraud** [comment]
Hello,
Here is the fix: https://github.com/Octopoos/SEBLOD/commit/881cdabec0fb50d8d14f8b98f9acddbeb6fb6064
It will be included in upcoming SEBLOD 3.11.4
Thanks,
Saba
