### ISSUE TITLE
USER plugin can't access #__cck_store_item_users table

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#415]
Hi

The user live value plugin can't retrieve values that are stored in the #__cck_store_item_users table.
When we use this plugin in a site form we can easily retrieve any values stored in the #__users or #__cck_store_form_user tables but never from the #__cck_store_item_users table.

This is all the more disturbing since the #__cck_store_item_users table is the table SEBLOD natively created.

thanks

cyril

**Comment by sebastienheraud** [comment]
Hello,
Not able to replicate. (and we use this feature on **all** our projects)
If needed, please report on our forums, with more details.
Regards,
Saba.
