### ISSUE TITLE
Only 1 result in seb_blog template used with the list field

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#42]
When seb_blog is used as the list template within a list field, it will only display 1 result. If seb_table or seb_list is used, there is no issue.

Issue originally reported and confirmed here - with some further debugging information as well: http://www.seblod.com/community/forums/standard-premium-memberships/seblod-list-plugin-always-returns-only-1-item

**Comment by pulsarinformatique** [comment]
Hi

any update on this issue please ?
thanks

cyril

**Comment by olivier-at-octopoos** [comment]
Hi Cyril,

At least, we've found what the problem is.
We're still checking how we can handle this without breaking anything.

Olivier

**Comment by designbengel** [comment]
I have this issue too :) following thread

**Comment by sebastienheraud** [comment]
Hi,
This is fixed in the "master".
Will be included in upcoming SEBLOD 3.8.0 release.
Saba.
