### ISSUE TITLE
j3.7+seb 3.11 calendars : can't detect the value change

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#420]
Hi

HI, has anybody detected with SEBLOD 3.11.2 that a change on the calendar value is no more detected by jQuery ?
in a front form within a JS code field the following code

 $( "#calendar_field").change( function()  {alert("test");  } ) 

no longer works

This is Something that worked as with any other field in previous versions

Same issue with the Jform Calendar and the SEBLOD calendar.

thanks

cyril

**Comment by coolcat-creations** [comment]
same here

**Comment by pulsarinformatique** [comment]
Klas found the solution in calendar.php line 439

replace $js .= 'this.hide();  }';
with
		$js .= 'this.hide(); jQuery("#'.$id.'").trigger("change"); }';

Thanks Klas !

**Comment by klas** [comment]
Fixed https://github.com/Octopoos/SEBLOD/commit/b9b7256f13014629af7974c0767df7cd936786e7

**Comment by klas** [comment]
So this can be closed.
