### ISSUE TITLE
groupX style=table values not visible

### ISSUE THREAD

**Issue by PierreCorell** [Octopoos/SEBLOD#421]
Hello, 

I found a minor bug in:
Backend, Isis template, CCK Admin form, SEB 3.11.2, J! 3.7.2

When you integrate a groupX with the table style, the values are not visible of some fieldtypes, I found it at calendar and select, see screenshot. The select stays empty, the calendar value is filled correctly in the source value, but is not visible to the admin, too.
![2017-06-02_cck_admin_groupx](https://cloud.githubusercontent.com/assets/3313934/26714447/b60076e0-4771-11e7-9ba8-b72dccc40008.png)

I may this is caused by the missing / not assigned rule of cck.admin.css:48
`div.cck_forms.cck_admin div.cck_form.cck_form_calendar.input-append input, div.cck_forms.cck_admin div.cck_form.cck_form_jform_calendar .input-append input {
    font-size: 13px !important;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
    border-right: none;
}`

I tested some things - and found a possible solution by changing the outer div-class of the groupX from cck_forms to cck_form
see screenshot 2 and belonging code extract:
`<!-- inputs are hidden:: --><div id="cck1r_GROUPXNAME" class="cck_forms cck_form cck_admin cck_group_x cck_GROUPXNAME"></div><!-- works:: --><div id="cck1r_GROUPXNAME" class="cck_form cck_form cck_admin cck_group_x cck_GROUPXNAME"></div>`
![2017-06-02_cck_admin_groupx-solution](https://cloud.githubusercontent.com/assets/3313934/26714465/c6f1b6b2-4771-11e7-8f02-14c22c8cad81.png)

Best regards, 
Pierre.

**Comment by sebastienheraud** [comment]
Hello Pierre,
Fix: https://github.com/Octopoos/SEBLOD/commit/54f7c4b75bbce87c5d9c505bf50dec8ef8faeee8
(not able to replicate for select)
Thanks,
Saba.
