### ISSUE TITLE
global config Email from field not retrieved

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#422]
with joomla 7.2 +seblod 3.11.2 it seems that if you set DEFAULT to the from (name) field in a email field it doesn't take the joomla global config email from field.

thanks

cyril

**Comment by klas** [comment]
I can confirm this problem,

**Comment by sebastienheraud** [comment]
Hello,
Here is the fix: https://github.com/Octopoos/SEBLOD/commit/8d89dbcbcf6f2f2d91beff59f939be1cbe307a45
Regards,
Saba
