### ISSUE TITLE
Can't use function return value in write context

### ISSUE THREAD

**Issue by harald-konrad** [Octopoos/SEBLOD#427]
Seblod Version 3.11.3
Joomla! 3.7.2
This error appears while opening any existing 
Forms & Content Types
Fields
List & Search Types

and also while trying to create new items
 
Fatal error: Can't use function return value in write context in /var/www/xxx/plugins/cck_field/calendar/calendar.php on line 102

**Comment by sebastienheraud** [comment]
Hello,
It seems that your site runs under PHP 5.4, which is no longer supported but the PHP Dev Team.
We strongly advise you to upgrade to a newer PHP version if you are able to.
If you can't, please let us know.
Saba.

**Comment by sebastienheraud** [comment]
Here is the fix if you can't upgrade: https://github.com/Octopoos/SEBLOD/commit/142504ee61ad48fdb179d6b41f56164d4471977d
Saba

**Comment by harald-konrad** [comment]
Yes the site runs under 5.4 at the moment. I will upgrade! Thanks for this advice.
