### ISSUE TITLE
Seblod list field and before render code

### ISSUE THREAD

**Issue by lepache** [Octopoos/SEBLOD#428]
It seems like a regression after update to SEBLOD 3.11.x 
Before update, I had a parent list within a child list called by a SEBLOD list fields. The option of the seblod list field was calculated (or just add a value) in a Before Render field in parent list.

After update, option is no longer calculated. I have tried with calendar fields and with text field.

[Explanations here](https://www.seblod.com/community/forums/fields-plug-ins/seblod-list-field-and-before-render-code#post53622)

**Comment by lepache** [comment]
No reply ? Nothing new ?

**Comment by sebastienheraud** [comment]
Hello,
A new major release of SEBLOD (3.13) is almost ready. It will be published next week.
Code Pack 1.5.0 will be released alongside the Core package, and it brings the ability to select a custom Priority (per BeforeRender Field) in the Processing stack.
Currently it is equal to **5** (last), selecting **3** should match the behaviour that you had with SEBLOD 3.10.x (i.e. equal to the List field -- and so based on the Fields order), and selecting **2** will mean prior to the List field. 
Please confirm when it's available.
Regards,
Saba

**Comment by lepache** [comment]
Thank you Sebastien,
After upgrade I have put the priority to 2 and it works fine.

**Comment by sebastienheraud** [comment]
Hello,
Thanks for the feedback.
Saba.
