### ISSUE TITLE
Missing JTEXT for COM_CCK_Article_Associations

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#429]
As title says

**Comment by sebastienheraud** [comment]
Hello,

- COM_CCK_ASSOCIATIONS translation added
- Missing Label input added to the plug-in
- "Associations" set in install.sql on both Article/Category fields

Related commits:
https://github.com/Octopoos/SEBLOD/commit/83be5a96c547a9513acebc029165ce83093f16d7
https://github.com/Octopoos/SEBLOD/commit/557a7e1f2d60966469c0def5a3d44ec34d0230d0
https://github.com/Octopoos/SEBLOD/commit/408db1ff0b800d2fa9f9c97a4a789800d4fd5579

For existing sites, you'll just need to use "Associations" as the label.
Thank you for the report.
Regards,
Saba.
