### ISSUE TITLE
New Calendar Field always saves seconds like ":00"

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#432]
Two bugs:

1. If select TODAY in datepicker set date and time as 2017-06-29 04:17:47 but after save replace date and time as 2017-06-29 04:17:00

2. Always save article with seconds like ":00"

**Comment by viocassel** [comment]
🐛 J!Bug -> [Calendar form field doesn't allow inputting seconds](https://github.com/joomla/joomla-cms/issues/16084)

**Comment by joomla-ua** [comment]
Yes, it's bud from joomla calendar xml field.

**Comment by sebastienlapoux** [comment]
Fixed and closed yesterday on https://github.com/joomla/joomla-cms/issues/16084 
Joomla 3.8...

**Comment by sebastienheraud** [comment]
Hello,
Confirmed, after testing the Joomla! 3.8 PR! 👍 
Thanks,
Saba.
