### ISSUE TITLE
No button text editor

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#435]
Hi, in Seblod settings associated with a text editor has no button Menu, Image, etc.
![2017-07-02_110130](https://user-images.githubusercontent.com/19167244/27909286-a3a564c2-6258-11e7-8485-933bac8b0e3c.jpg)
![2017-07-02_110714](https://user-images.githubusercontent.com/19167244/27909285-a3a524bc-6258-11e7-9b88-78299057b3a9.jpg)

**Comment by sebastienheraud** [comment]
Hello,
Yes a new parameter has been added in a previous release.
If you need to enable them, go the Field Manager, and search for Name: "core_description", with "All Status" or "Off". Edit the field, and you'll find "Show Buttons" parameter.
Saba
