### ISSUE TITLE
Warning when installing the application

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#436]
Hi, when I install your app it appear warning. Seblod 3.11.3 and Joomla 3.7.2
![2017-07-05_172752](https://user-images.githubusercontent.com/19167244/27909536-cafffff4-6259-11e7-9bb8-0c6869ef36d7.jpg)

**Comment by sebastienheraud** [comment]
Hello,
Notices fixed here: https://github.com/Octopoos/SEBLOD_more/commit/244922203a4aa0cb3c058c7ef0722d00a611a69e and https://github.com/Octopoos/SEBLOD_more/commit/63820602bc09649a82337a193b85e49c65eb8d07 
Joomla! Article Field Plug-in 3.8.3 released: https://www.seblod.com/store/extensions/40326
Thank you,
Saba
