### ISSUE TITLE
1.30 code field and link plugin

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#437]
Hi

With Joomla 3.7.3 + seblod 3.11.3 + code field 1.30:

Let's have a my_free_text free text field in your content view. This free text is empty and is filled by a BEFORE RENDER php code.

In the  BEFORE RENDER php code you write
$fields['my_free_text']->value="some text";

If you add some VIEW link plugin over the my_free_text field, the "some text" disappears

If you revert to 1.22 code field, there is no issue 

Thanks

Cyril

**Comment by klas** [comment]
what is look plugin

**Comment by pulsarinformatique** [comment]
Sorry this is the VIEW standard link plugin :)

**Comment by pulsarinformatique** [comment]
I modified the initial post with the right name of the plugin so that you can try to reproduce the issue
thanks

**Comment by pulsarinformatique** [comment]
I confirm the issue on several sites.

**Comment by pulsarinformatique** [comment]
Hi,

Nobody can confirm it too please ?

thanks

cyril

**Comment by pulsarinformatique** [comment]
Hi 

the issue remains with the 1.4.0 code field. 

thanks

cyril

**Comment by klas** [comment]
I can confirm the problem with Seblod 3.12 and field 1.4. I suspect it is related to processing priorities introduced in 3.11.

**Comment by pulsarinformatique** [comment]
Thanks, at last it is confirmed :)

you wrote I should use the following syntax as a workaround:

$fields['yourfield']->html = str_replace('#xy#', 'toto', $fields['yourfield']->html );

With this code doesn(t work in a multi language site:

The field becomes visible again with the right link above it BUT the html is not replaced with 'toto' but COM_CCK_toto !!

thanks
cyril

**Comment by pulsarinformatique** [comment]
Hi,

Any update on the fix please ?

thanks

cyril

**Comment by klas** [comment]
As you can see in the code base there is no update.

**Comment by pulsarinformatique** [comment]
Yes I saw but is there a plan to fix it ?

**Comment by sebastienheraud** [comment]
Hello,
A new major release of SEBLOD (3.13) is almost ready. It will be published next week.
Code Pack 1.5.0 will be released alongside the Core package, and it brings the ability to select a custom Priority (per BeforeRender Field) in the Processing stack.
Please confirm when it's available.
Regards,
Saba

**Comment by klas** [comment]
Unfortunatelly priorities don't change anything as html is rendered on the field before beforeRenderContent is executed regardless what priority is set on the process..

**Comment by pulsarinformatique** [comment]
With the 1.5 version the problem is solved when playing with the priorities

thanks!

cyril

**Comment by sebastienheraud** [comment]
Hey Cyril,
Thank you.
Saba.
