### ISSUE TITLE
Error during new installation Seblod 3.11.3

### ISSUE THREAD

**Issue by joomleb** [Octopoos/SEBLOD#438]
PHP 7.1.7 MySQLi 5.6.23-cll-lve, on a new Joomla 3.7.3, installing a new Seblod 3.11.3 I have back:

> **Warning**
> Error loading component: com_cck, Component not found. 
> Incorrect key file for table '/var/db/mysql-tmp/#sql_21c88_0.MYI'; try to repair it 
> Package Install: There was an error installing an extension: plg_content_cck.zip

Reinstalling Seblod 3.11.3 on that corrupted installation I have back:
> **Warning**
> Duplicate entry '92-0' for key 'PRIMARY' Package Install:
> There was an error installing an extension: plg_content_cck.zip

Going to Extensions > Plug-in Manager > select type “content” from the drop down list: “Content - SEBLOD” is not listed !

Seem that the installation process has been stopped...

**Comment by sebastienheraud** [comment]
Hello,
Not able to replicate. You may not be using an Official/English Joomla! package.
I'm closing it now. If you still have issues, please report on our forums.
Regards,
Saba.

**Comment by joomleb** [comment]
Hi Sebastien, 
if can be useful I have an AkeebaBackup copy of that site...
