### ISSUE TITLE
$cck->getValue method not working on HTML typo in INTRO view

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#44]
The method to use $cck->getValue('field_name') to retrieve the value of a field within the HTML typo used on a field in the INTRO view of a Content Type does not render the value. It just shows the code.

**Comment by olivier-at-octopoos** [comment]
James,

Could you detail how to reproduce this as I've created a Category blog menu item which is displaying the INTRO view of my content type and everything's ok; The HTML Typo is processed and the final result is correct.

Thanks,

Olivier

**Comment by Octopoos-James** [comment]
Hi Olivier,

 

You are right, I have just tried to reproduce and it works. Perhaps it was a syntax error on my side initially. You can close this issue.

 

Thanks,

James
