### ISSUE TITLE
invisible records in the database.

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#442]
Hi, noticed a bug, it can be seen only during a clean install of Joomla and Seblod, the latest version. Is created in the database invisible the content type with id 500. It can be seen in the admin site. Shows "empty" value in the list and using the source code to see what is there. As an invisible record with id 500 exists in other database tables Seblod.

![2017-08-06_201717](https://user-images.githubusercontent.com/19167244/29168859-835da48a-7dd9-11e7-9e08-a341826c3d75.jpg)

![2017-08-07_081410](https://user-images.githubusercontent.com/19167244/29168860-838c6928-7dd9-11e7-8d47-29206c9cbb05.jpg)

**Comment by sebastienheraud** [comment]
Hello,
Good catch! Thank you.
Fix here: https://github.com/Octopoos/SEBLOD/commit/0b2d4c074290a488d6d8be7234a1eb5d734590d6
These entries are used to keep the AUTO_INCREMENT, but shouldn't be visible.
Regards,
Saba.
