### ISSUE TITLE
Seblod importer : translation pb to French

### ISSUE THREAD

**Issue by Hableur** [Octopoos/SEBLOD#444]
I think it would be good to translate 'clear' by ' mdp en clair' instead of 'Effacer', et 'md5' en 'mdp en md 5' in the french translation, it would be more easy to understand.

**Comment by Hableur** [comment]
changed

**Comment by sebastienheraud** [comment]
Hello,
French translation updated here: https://github.com/Octopoos/SEBLOD/commit/2e05f55408b141052caf03daa6545d73ace91361
Merci ;)
Saba
