### ISSUE TITLE
Address to Coordinates french language

### ISSUE THREAD

**Issue by Hableur** [Octopoos/SEBLOD#445]
Fr-fr langages files are not in UTF8 mode. So name of the field is clear in the list of field.
Remplacing them with the same saved in UTF8 work fine. 

fr-FR.plg_cck_field_address_to_coordinates.sys.ini

fr-FR.plg_cck_field_address_to_coordinates.ini

**Comment by sebastienheraud** [comment]
Hello,
Fixed here: https://github.com/Octopoos/SEBLOD_more/commit/af1ca986c55974df85a77133b49a0760f13a8930
1.3.3 is now available: https://www.seblod.com/store/extensions/920
Thanks!
Saba
