### ISSUE TITLE
When creating field with unlocked storage storage is reset to Custom

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#446]
When creating field with unlocked storage, regardles whether this is from content type or from fields manager,   storage is reset to Custom - Article - Introtext. I guess this default is completely wrong

**Comment by viocassel** [comment]
I agree with you @klas

**Comment by sebastienheraud** [comment]
Hello,
Yes, and here are various improvements. :)  https://github.com/Octopoos/SEBLOD/commit/62b7edbb9e0560c01b9937f199159569206a235e
Regards,
Saba
