### ISSUE TITLE
GroupX +/- buttons in a form module doesn't work

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#452]
Hi
if you call a groupX from a SEBLOD form module the +/- buttons don't work. 
verified with J 3.7.5 + seblod 3.12.2
Can you confirm please ? 
thanks
cyril

**Comment by sebastienlapoux** [comment]
Hi Cyril,
Can you please check with the Joomla front-end default template? And with a very simple page (article view example) to be sure no conflict with other elements of the page.
Thanks.

**Comment by pulsarinformatique** [comment]
Hi Seb

confirmed with the Joomla front-end default template and with a very simple page. No Js conflict in the console either

thanks

cyril.

**Comment by klas** [comment]
Confirmed. 

Problem lies in this javascript from script2.js as elem is still empty after this lines due to hardcoded id or missing external class (not sure which one should match):
`				if ($(this).hasClass('external')) {
					elem = root.children().last();
				} else {
					elem = $(this).closest('[id^="cck1r_forms_'+name+'"]');
				}`

**Comment by pulsarinformatique** [comment]
HI, Do you believe a fix can be provided in the following weeks please ?
thanks

**Comment by sebastienheraud** [comment]
Hello,
Here is a fix: https://github.com/Octopoos/SEBLOD/commit/ed661660957d13f3604aa9dfcedd29585697a5f2
Please have a try.

**Comment by pulsarinformatique** [comment]
Hi Saba

tested it and seems to work. Thanks a lot !!

Cyril

**Comment by sebastienheraud** [comment]
Thanks

**Comment by pulsarinformatique** [comment]
still not ported on Seblod 3.15.0

**Comment by klas** [comment]
cyril, you previously claimed it works for you, this code is the same as in 3.15. Try refreshing your caches.
