### ISSUE TITLE
Error in function load( $identifier ) 

### ISSUE THREAD

**Issue by joomla-ua** [Octopoos/SEBLOD#459]
`			$core					=	JCckDatabase::loadObject( $query.' WHERE a.id = '.(int)$identifier );
`

replace a.id to a.pk

Path:  SEBLOD/libraries/cms/cck/content.php

**Comment by sebastienheraud** [comment]
Hello,
Nop. Current behaviour is correct.
The identifier is either:
- an INT >> unique ID of SEBLOD
OR 
- an ARRAY >> object and pk (primary key of the base table), ex: array( 'joomla_article', 123 ) 

By the way you shoudn't use _JCckContent::load(...)_ but
`$content = JCckContent::getInstance(...);`
OR
```
$content = new JCckContentJoomla_Article;
$content->load(...);
```
Regards,
Saba.

**Comment by sebastienheraud** [comment]
One improvement could be add support of the suggested implementation (pk as the identifier), for the following use:
```
$content = new JCckContentJoomla_Article;
$content->load(...);
```
as it makes no sense to have the array with the object name.

We'll have a look.
Thanks.
Saba.

**Comment by sebastienheraud** [comment]
I guess **this is it**! https://github.com/Octopoos/SEBLOD/commit/67ba8d67bf3adac6924eeb943a9c6cee094172ad

```
$content = new JCckContentJoomla_Article;
$content->load( $pk );
```

`$content = JCckContent::getInstance( $id );`

`$content = JCckContent::getInstance( array( 'joomla_article', $pk ) );`

`$content = JCckContentJoomla_Article::getInstance( $pk );`

All of the above code will work and make sense. Right?

The only way to load a Content that we should NOT use it now:
$content = new JCckContent(...); whatever is args is... as the object won't use the correct class.

And nothing changed to create content, we still use the following method:

```
$content = new JCckContentJoomla_Article;
$content->create( $data, $data_more );
```

Feel free to test, and let me know your thoughts.
Thank you!
Saba.

**Comment by sebastienheraud** [comment]
Hey Denis,
A lot more changes  https://github.com/Octopoos/SEBLOD/commit/e5e851c99f554b96bae7174099e7a8158570c64b#diff-786b2a6f8376ba3dc4f4fbc5c93a0c8c are coming in SEBLOD 3.15 :), and we are working on the documentation to explain all capabilities and uses.
Saba

**Comment by joomla-ua** [comment]
Hello, @sebastienheraud !

How correctly to display data articles (title, create date, author, etc. from Joomla! and all my fields from TK SEBLOD)?

I use this code:
```
$content = JCckContentJoomla_Article::getInstance( '10660' );
print_r($content);
```
'10660' - article ID

It's correctly?

But I'm get many data from Joomla and SEBLOD Objects. Please look to attach.
[data.txt](https://github.com/Octopoos/SEBLOD/files/1411994/data.txt)

It seems to me that this code is not complete! :-)

And one more idea!

Could you add the possibility of getting a link to an article without SEF based on the field (for example, the text field) that could be written as an argument?

It would be very convenient to use.

Something like this:
```
$content = JCckContent::getInstance(
    array(
        'joomla_article',
        'title', // If use link in title field. Display as: index.php?option=com_content....&id=9999:alias&Itemid=9999
        $pk
    )
);
```

Thank you!

**Comment by oliviernolbert** [comment]
Hi,

For your first question:

```
$content = JCckContentJoomla_Article::getInstance( '10660' );
$content->getProperty( 'title' );
$content->getProperty( 'created' );
$content->getProperty( 'created_by' );
$content->getProperty( 'custom_1' ); //Assumes you have a field with storage "Standard / Article / custom_1"
....
```

Regards,
