### ISSUE TITLE
Feature request: enable usage of JForm User in front end for all users

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#492]
Currently JForm User is working in front-end only for superadministrator (so for example a live value for a guest or for a registered user on this field has no effect).
JForm User is much better than a select dynamic field since it does not load all values from the DB into the client and allows filters for searching.
This issue is for requesting this field to be usable, maybe with an option, also for the other access level users.
See also [https://www.seblod.com/community/forums/fields-plug-ins/jform-user-restricted-access](url)

**Comment by klas** [comment]
This is a limitation that comes from Joomla, Seblod just displays Joomla field when you are using any JForm field.

**Comment by Giuse69** [comment]
Ok but the other JForms (calendar, Access Level, Association for existing items, Timezone.. ) work. Just User has this problem, it's weird.

**Comment by Giuse69** [comment]
Ok, I close this feature request. It would be very useful to have a similar field in Seblod (a modal window to select from a table without loading all values from the table).

**Comment by sebastienlapoux** [comment]
@Giuse69 we developed the SEBLOD technology (not public currently) to build such manager to select an item (whatever the content type). Contact Octopoos if interested to support it.

**Comment by Giuse69** [comment]
Thanks Sebastien, I was told by Seba also at last JWC in Rome of this interesting field in development. I will contact him back.
