### ISSUE TITLE
[lang] returns an upper case string in select cascade

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#493]
[lang] is a variable used for multilanguage sites like in <fieldname>_[lang].
Actually if used in an expression (e.g. to extract a value from a JSON field with `JSON_VALUE(<fieldname>, "$.[lang]")`) it returns an uppercase, like "EN", that is not correct since language codes are lowercase and infact the JSON_VALUE does not work and it is necessary to write `LOWER("$.[lang]")`.
Verified this in select dynamic cascade - I dont know in other fields
**update:** verified that select dynamic (non cascade) the issue is not present

**Comment by sebastienheraud** [comment]
Hello,
Fixed with Select Dynamic Cascade 1.4.1 release (published just now).
Regards,
Saba.
