### ISSUE TITLE
Can not use more than one chart / graph in a page

### ISSUE THREAD

**Issue by shubhaanshu** [Octopoos/SEBLOD#495]
Hi, I am using seb chart template to create a dashboard of a list for my content type, but there is a problem that it does not show more than one chart/ graph in a page...

**Comment by sebastienheraud** [comment]
Hi,

Fixed in upcoming version.
It should be released when we'll launch SEBLOD 3.17 (Sep. or Oct.)

Regards,
Saba

**Comment by sebastienheraud** [comment]
Hi,

It should work fine with the latest version, released today alongside SEBLOD 3.17:
https://www.seblod.com/community/blog/new-release-seblod-3-17-0

Saba.
