### ISSUE TITLE
Persistant search does not work in the Seblod search module

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#497]
Hello!
Refering to this topic, there seems to be a bug in the module, or the feature was not added yet... Persistant search is missing there:
https://www.seblod.com/community/forums/lists-search-types/persistant-search-module#post56793

Is there an easy fix for it?

Thanks.

**Comment by sebastienheraud** [comment]
Hi,
This should make it work: https://github.com/Octopoos/SEBLOD/commit/866c3937447327ce5b255dc139ac3f8b3adbb6bb

Included in upcoming SEBLOD 3.17 release.

Sebastien

**Comment by sebastienheraud** [comment]
Hi,

SEBLOD 3.17 was released today, feel free to have a try:
https://www.seblod.com/community/blog/new-release-seblod-3-17-0

Saba.

**Comment by coolcat-creations** [comment]
Thank you Saba, will test it as soon as possible :)
