### ISSUE TITLE
Print button broken after this change

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#499]
After this print button doesn't work anymore
https://github.com/Octopoos/SEBLOD/commit/0c42146b3ad0fe6e6d4df04c34f9ad5109042a19

it is creating links like that: 

onclick="window.open(this.href,'win2','status=no,toolbar=no,scrollbars=yes,titlebar=no,menubar=no,resizable=yes,width=640,height=480,directories=no,location=no'); return false;**else{document.location.href='http://testplatz.ch/demoshop/papiere/455-1131021?tmpl=component&print=1'}**;"

**Comment by sebastienheraud** [comment]
Hello Klas,
Actually, it is this change https://github.com/Octopoos/SEBLOD/commit/dee4ed498a7c4c31384fe4b9a17bdbb18761ea31#diff-18dc7f59824b030bdd4c6f6211525c35 which breaks it.
I'm fixing it.
Thanks,
Saba.

**Comment by sebastienheraud** [comment]
And I'm gonna check this one as well https://github.com/Octopoos/SEBLOD_more/pull/3
Saba

**Comment by klas** [comment]
Hi, yes, this is the one, I somehow copied the wrong commit. 
Thnx.

**Comment by sebastienheraud** [comment]
The following fix should be okay: https://github.com/Octopoos/SEBLOD_more/commit/d08b49bc9c4968b6ae753db6a217c1cf205e94cf
Another change has been applied to Free Button, but I can't sync it for now.
Regards,
Saba.
