### ISSUE TITLE
replaceLive() gets Value only

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Octopoos/SEBLOD#50]
Hello everybody.
I found new and vrey useful function **replaceLive($attr)**. Thats great!
But I see that:
file **\libraries\cck\rendering\rendering.php**
**string 983**: $get		=	'get'.$target;
but next
**string 984**: $replace	=	$this->getValue( $fieldname );
and $get variable isn't used. I think that it should be
**string 984**: $replace	=	$this->$get( $fieldname );
to have not only Value but Attributes, Text etc...
Thanks!

**Comment by sebastienheraud** [comment]
Hi
Thank you for the report and fix.
This is merged for both Content and List rendering processes.
Saba
