### ISSUE TITLE
plgCCK_Storage_Locationnone not found

### ISSUE THREAD

**Issue by compep** [Octopoos/SEBLOD#501]
i tried to create a form with 3 pages. I created a new forms and content type, also created several fields, set Site Form/Configuration->Stages Count 3, 

In Site Form-Fields I set the stages for every field, put a next-button there for every stage and a submit button withh an hidden email-field in the final stage.

The Form in the frontend does not work. when I open the Form (menu-item seblod Form), i see the Fields of the first stage, when I clickt on the next-button, i get a 404 with the message "0class 'plgCCK_Storage_Locationnone' not found. I have no idea, whats wrong. All the permissons are correct.

Does anyone have an idea?

**Comment by sebastienheraud** [comment]
Hello,
Not able to replicate this issue.
Feel free to execute this query with PhpMyAdmin to find field(s) with error:

> SELECT * FROM `ghmfx_cck_core_fields` WHERE `storage_location` = "none"

With the UI, it should be impossible to have "none" as value for the Object (= storage_location)

Regards,
Saba.
