### ISSUE TITLE
Amdmdin menu left over on Seblo uninstall

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#502]
When Seblod is uninstalled Admin Menu - Seblod remains, causing repeated admin menus in the top bar. 

To completely remove Seblod one has to go to Modules, switch to Administrator modules menus and delete Admin Menu - Seblod

Reference https://www.seblod.com/community/forums/general-discussions/admin-menu-problems-when-uninstalling-seblod#post56909

**Comment by sebastienheraud** [comment]
Hi Klas,
Below a quick note from a reply we posted on the JED some months ago...

> Joomla! core has a fallback behaviour to load the "joomla/default" preset when the requested one is not found. The thing is... it would be better to execute this fallback only once, which is currently not the case.

Saba
