### ISSUE TITLE
CSS change needed to toggle on conditional states

### ISSUE THREAD

**Issue by celius** [Octopoos/SEBLOD#509]
There is a float:left; there that's creating a unwanted look. See attached screenshots.

![screenshot-nordcon webist no-2018 03 02-08-38-55](https://user-images.githubusercontent.com/4268181/36888339-5d1da09c-1df5-11e8-9ae1-b32f5f2e4cce.png)
![seblod](https://user-images.githubusercontent.com/4268181/36888340-5d3c2b5c-1df5-11e8-9b55-3568950db7c2.jpg)

**Comment by sebastienheraud** [comment]
Hello,
Fixed in upcoming SEBLOD 3.16.1 https://github.com/Octopoos/SEBLOD/commit/d1e4d712fd3c1b44f49e5cf187701f341058fb18
Thanks!
Saba
