### ISSUE TITLE
Option None missing from Integration->Article->Add Button

### ISSUE THREAD

**Issue by klas** [Octopoos/SEBLOD#513]
Due to CSS bug Option None is 
![ed95d6e7a9e69578793d160ee4d79f0923a2a7fc1c3fd9e320 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/331352/37821170-3b98df88-2e83-11e8-8595-76766c1e8858.jpg)
missing from Integration->Article->Add Button

Solution:
https://www.seblod.com/community/forums/general-discussions/disable-seblod-for-articles#post57586

**Comment by sebastienheraud** [comment]
Hello Klas,

Thank you.
Fixed in upcoming SEBLOD 3.16

Regards,
Saba
