### ISSUE TITLE
Travelpayouts

### ISSUE THREAD

**Issue by kartjuction** [Octopoos/SEBLOD#517]
Hi Everyone,

I have problem to set travelpayouts.com whitelabel on sub domain.

Set search form on my main domain with white label using my sub domain and when visitor clik on search bar the results are OOPS! THAT PAGE CAN’T BE FOUND.
It looks like nothing was found at this location. Maybe try a search?

Please guide me how can i set properly .

Regards,

**Comment by klas** [comment]
Spam, @sebastienheraud please close
