### ISSUE TITLE
Cache for large searches

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#518]
Hi
On J3.8.7 + S3.15:

We have an issue with the SEARCH CACHE (not the renderer cache) in the list settings. When we turn it on the search is very fast but we lost the pagination numbers!!

thanks

cyril

**Comment by vnnguyendung** [comment]
You could read this article https://www.seblod.com/community/forums/general-discussions/seblod-site-performance

**Comment by pulsarinformatique** [comment]
Hi
yes I already read it but it didn't solve the issue :)

thanks

cyril

**Comment by vnnguyendung** [comment]
- Turn off Global Cache System (Menu Global Configuration >> tab System >> Cache Settings >> System Cache >> select **OFF - Caching disabled**)
- Go to Lists & Search Types, select list, go to tab Configuration, turn on **Cache (on Search)** AND **Cache (on Render)** select **Off**

**Comment by pulsarinformatique** [comment]
thanks :) but we already know that. 
the issue is real, it has nothing to do with "how to use the list cache" but with the pagination that is lost. please re read

thanks

cyril

**Comment by pulsarinformatique** [comment]
Hi
No confirmation please ?

thanks

cyril

**Comment by sebastienlapoux** [comment]
@klas please test

**Comment by klas** [comment]
Listing cache seems totally broken on Seblod 3.16.2, Joomla 3.8.10 and php 7

- With Cache (on Search)  I can confirm what @pulsarinformatique claims, pagination is gone when you reload the page (it is ok on the first load)
- With Cache (on Render) I get no results at all and Warning: Parameter 7 to CCK_List::render() expected to be a reference, value given in C:\xampp7\htdocs\seblod-testing\libraries\src\Cache\Controller\CallbackController.php on line 173

**Comment by sebastienheraud** [comment]
Hello,

Here is a commit that should help: https://github.com/Octopoos/SEBLOD/commit/8d0bb61adce8a75ce1cf34da23ec505d3b872a7e

Regards,
Saba

**Comment by pulsarinformatique** [comment]
Hi

tested it (afer the 3.16.3 update) and it now works keeping the pagniation !

thanks a lot

where are described the cache option (global / splitted / anyone / per user) ??

thanks


cyril

**Comment by sebastienheraud** [comment]
Hi,

> tested it (afer the 3.16.3 update) and it now works keeping the pagniation !

Thanks for the feedback.

> where are described the cache option (global / splitted / anyone / per user) ??

Yes, I guess it is missing for now. Feel free to open a thread on the forums.

Closing this issue now.
Saba
