### ISSUE TITLE
How to create programly article in Free object?

### ISSUE THREAD

**Issue by evolvens** [Octopoos/SEBLOD#519]

**Comment by sebastienheraud** [comment]
Hello,
It is currently not supported.
Regards,
Saba

**Comment by sebastienheraud** [comment]
Hello Denys,

Good news! SEBLOD 3.16.4 will bring support of Free object to JCckContent.
Feel free to test after applying the following commits: 

- https://github.com/Octopoos/SEBLOD/commit/635581292fb4b46be3db734c17869c522f68ee0e
- https://github.com/Octopoos/SEBLOD/commit/3cb97bbc43d9411d78f8ac9e5ec65b32e9e58bbe
- https://github.com/Octopoos/SEBLOD/commit/d5fdd4f4ae1882056e5b5054dec7467e82134635

We'll publish a new page in manuals when we'll release the version, but here is what you need to start playing with it:

```
$content = new JCckContentFree;
$content->setTable( '#__my_own_table' );
```
Saba

**Comment by joomla-ua** [comment]
Thank you! It's good news!

**Comment by sebastienheraud** [comment]
Hi,

SEBLOD 3.17 was released today, feel free to have a try, and read those:
* https://www.seblod.com/community/blog/new-release-seblod-3-17-0
* https://www.seblod.com/resources/manuals/developer/manipulating-content-free

Saba.
