### ISSUE TITLE
FieldX Upload Image, minimum value changes when edit an article

### ISSUE THREAD

**Issue by proelgiz** [Octopoos/SEBLOD#52]
I have a gallery FieldX Upload Image. Default value is 10, maximum value is 10 and minimum value is 10. So when user create new article he can see 10 input file boxes. If user upload two images and save an article next time when he edit an article there will be two thumbnails and only two input file boxes.. But there is NO other (8) input file boxes. To upload more images user has to click green button (add image button). According to default settings it must be 10 input file boxes. So 8 input file boxes are missing.
It's a serious issue because some users doesn't click green button.

**Comment by proelgiz** [comment]
![capture1](https://cloud.githubusercontent.com/assets/12431916/7625989/ac4d1c06-fa21-11e4-9d5f-6fb595837982.PNG)

**Comment by sebastienheraud** [comment]
Hi,
Here is the fix we've applied: https://github.com/Octopoos/SEBLOD/commit/137443cb85c95141b8f7de8b5d4896d474bb2de1
This is including in upcoming SEBLOD 3.7.0
Thanks,
Saba.
