### ISSUE TITLE
Validation plugin - Availability - error when restricting existence check

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#522]
The availability check in the validation offers a "Fields" parameter to type additional fields that can restrict the query of availability of the value so that the value is searched adding WHERE clause with the additional fields compared to the values of current form.
These fields must be written separated by "||" (double pipe - undocumented feature in the user manual) but then I get a Error 500 Server Error.
Klas probably found another issue in the same php file: 
https://www.seblod.com/community/forums/fields-plug-ins/validation-availability-additional-fields

**Comment by sebastienheraud** [comment]
Thanks @Lio3w73.

---

Hi @Giuse69,

A fix is applied on the query for multiple where parts, in SEBLOD 4.0.0 Release Preview 1.
Also please note that all columns should be stored on the same table.

Saba
