### ISSUE TITLE
Checkbox field - single unchecked checkbox returns a warning (before store)

### ISSUE THREAD

**Issue by michalmariasek** [Octopoos/SEBLOD#524]
Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\dt\plugins\cck_field\checkbox\checkbox.php on line 333

**Comment by hamby** [comment]
Got the same warning on field image by uploading. The images size was 1MB. Seblod 3.16.3. Reducing the image to 50kb made no more warnings.

Warning: count(): Parameter must be an array or an object that implements Countable in /plugins/cck_field/checkbox/checkbox.php on line 333

**Comment by sebastienheraud** [comment]
Hi,

https://github.com/Octopoos/SEBLOD/commit/e9b124fe0738c8771bdced6bd12f5a5f7646c18c should  fix those.
It will be included in upcoming SEBLOD 3.17.4 (later this month).

Saba
