### ISSUE TITLE
Error 500 after Update from 3.15.0 to 3.16.0

### ISSUE THREAD

**Issue by creative-resort** [Octopoos/SEBLOD#532]
After updating from 3.15.0 to 3.16.0 and later
I'm getting an Error 500 (only) when accessing Joomla's Control Panel,
even with all SEBLOD plugins disabled.

using Joomla 3.8.11
PHP 7.1

**Comment by creative-resort** [comment]
UPDATE: even from 3.15.0 to 3.16.0,
I see the same issue.

**Comment by viocassel** [comment]
Confirm

**Comment by sebastienheraud** [comment]
Hello,
Could you provide more details (enabling error_reporting?) please?

Regards,
Saba

**Comment by klas** [comment]
You need to find out what the real error is first, 500 is internal server error used by mod_Security and similar systems to mack real error which most likely is some sort of missing database columns that were not updated.

**Comment by creative-resort** [comment]
@sebastienheraud, @klas 
The error is still there, even after updating just now. Joomla 3.9.1 + SEBLOD  3.17.0 

Here is what I'm getting:
```
HP Warning:  require_once(/www/htdocs//test/multisite/components/com_cck/helpers/helper_include.php): failed to open stream: No such file or directory in /www/htdocs/test/multisite/administrator/modules/mod_cck_list/mod_cck_list.php on line 34
PHP Fatal error:  require_once(): Failed opening required '/www/htdocs/test/multisite/components/com_cck/helpers/helper_include.php' (include_path='.:/usr/share/php:..') in /www/htdocs/test/multisite/administrator/modules/mod_cck_list/mod_cck_list.php on line 34
```

**Comment by klas** [comment]
Something went wrong with your updates, there is no administrator/modules/mod_cck_list https://github.com/Octopoos/SEBLOD/tree/master/administrator/modules

With the file management from your hosting (or ftp if you have it) delete administrator/modules/mod_cck_list, than log in and delete this module also from modules management.

**Comment by creative-resort** [comment]
Thank you so much!
Everything is fine now.
