### ISSUE TITLE
Allow Form submission without storage

### ISSUE THREAD

**Issue by sebastienheraud** [Octopoos/SEBLOD#534]
Hello,

Ref: https://www.seblod.com/community/forums/forms-content-types/an-error-has-occurred-while-sending-form

Regards,
Saba

**Comment by coolcat-creations** [comment]
@sebastienheraud its a huge issue for sites that use seblod as mail forms. Can you give an advise how at least to temporary fix it? Thanks!

**Comment by sebastienheraud** [comment]
Hi,

Emails were properly sent, only the message was wrong.
A simple/temporary workaround was to assign "Article Access" (or any other field) to get the right  message.

Anyway please have a try with this fix: https://github.com/Octopoos/SEBLOD/commit/7fa87428aade1ec8bbbbdc5dfb5d6fb521681b61

Regards,
Saba

**Comment by coolcat-creations** [comment]
Thanks a lot - the fix works for the message, but my mail is not sent - seems to be another issue too ;(

**Comment by coolcat-creations** [comment]
Got the sent issue sorted, i cant hide the email field. thanks a lot!

**Comment by sebastienheraud** [comment]
Hi,

Thanks for the feedback.
Closing it now.

Saba
