### ISSUE TITLE
2 GMAP list on the same page

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#535]
Hi

Is that normal we can't display two gmap lists on the same page? I guess there is some settings to allow two maps ?

thanks

cyril

**Comment by sebastienheraud** [comment]
Hi,

Fixed in upcoming version.
It should be released when we launch SEBLOD 3.17 (Sep. or Oct.)

Regards,
Saba

**Comment by pulsarinformatique** [comment]
Hi SAba

Thanks

cyril

**Comment by sebastienheraud** [comment]
Hi,

It should work fine with the latest version, released today alongside SEBLOD 3.17:
https://www.seblod.com/community/blog/new-release-seblod-3-17-0

Saba.
