### ISSUE TITLE
helper define missing 

### ISSUE THREAD

**Issue by joomkit** [Octopoos/SEBLOD#537]
After upgrade to lastets Joomla and seblod 3.16.3 articles that show a list of other articles via search module/list are showing this error:

Warning: require_once(/pathway//public_html/components/com_cck/helpers/helper_define.php): failed to open stream: No such file or directory in /pathway/public_html/plugins/cck_field/cck_list/cck_list.php on line 75

Fatal error: require_once(): Failed opening required '/pathway/public_html/components/com_cck/helpers/helper_define.php' (include_path='.:/opt/cpanel/ea-php71/root/usr/share/pear') in /pathway/public_html/plugins/cck_field/cck_list/cck_list.php on line 75

Is it looking for the help in the wrong place?

**Comment by sebastienheraud** [comment]
Hi,

These helpers were removed from core, as they have no use.
Feel free to update following plugins to their latest version:
https://www.seblod.com/store/extensions/8538

Issue will be fixed then.

Regards,
Saba

**Comment by sebastienheraud** [comment]
Not sure, please open a thread on our forums, with details.

Saba
