### ISSUE TITLE
Update to seb list template overwrites wrapper class

### ISSUE THREAD

**Issue by joomkit** [Octopoos/SEBLOD#538]
JUst had my site design elements collapse after updating to the latest form and list and seb lsit templates. The wrapper div class specified seems to get over written. Great (not)

**Comment by sebastienheraud** [comment]
Hi,

We are not aware of any issue with the wrapper class on the last version of List template.
Feel free to use a previous version of the template, if this helps.

Closing this issue now.  
Saba
