### ISSUE TITLE
Overriding the page title actually overrides the article title

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#544]
Hi

There is a strange behavior on the SEBLOD breadcrumb if you configure it on the "menu item" rule and if you override the seo TITLE tag in content type.

Please try the following:

1-in the ARTICLE content type add a text field (AR_art_seo_title for example) in the admin form and in the content view. 

2-in the content view config override the PAGE title with the AR_art_seo_title field

3- create some articles in a given category (mycat) and fill the AR_art_seo_title field of these articles

4-create a blog menu item on this category. let's name this menu item 'mymenu'

5-display this menu item on the front

6-click on one of the articles to enter the content page (detail page)

7- the breadcrumb will display  home > mymenu > [value of the seo title tag instead of the title of the article]

The breadcrumb doesn't display the actual title of the article but the seo title ????

Any clue why?

I must add that overriding the PAGE TITLE actually override the ARTICLE TITLE also. 

I had to hide the article title display in the global configuration and add the ART_TITLE field in the content view to display the right article title

It seems that SEBLOD overrides the article title in the content view knowing that Joomla will take this data for the page title. Unfortunately it confuses the breadcrumb

Thanks

cyril

**Comment by sebastienheraud** [comment]
Hi Cyril,

This one https://github.com/Octopoos/SEBLOD/commit/603c1aa0520d8e8105e9daa072c7d0756f4ae99a should fix it.
Please have a try and confirm.

Thank you,
Saba
