### ISSUE TITLE
Add core Article note field from Joomal! 3.9

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#549]
Joomla 3.9 introduced the note field for articles. Seblod should have a new Article Note field in the core with storage Standard / Article / note.

**Comment by sebastienheraud** [comment]
Hi Giuse,

Ok, the "art_note" field will be included in upcoming SEBLOD 3.17.4 https://github.com/Octopoos/SEBLOD/commit/eb5e42cf508545ea658c8a3729bbb46bbf9720fa
Not assigned to any content type though.

Thanks,  
Saba

**Comment by Giuse69** [comment]
thanks Klas for keeping Seblod compatible with new Joomla features
