### ISSUE TITLE
Override page title does not include site name

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#550]
The configuration option in Content View to override page title does not respect Joomla option to postpone/prepend site name to page title.

**Comment by sebastienheraud** [comment]
Hi Giuse,

This one https://github.com/Octopoos/SEBLOD/commit/603c1aa0520d8e8105e9daa072c7d0756f4ae99a should fix it.
Please have a try and confirm.

Thank you,
Saba

**Comment by Giuse69** [comment]
With that fix the title in the _browser window_ is ok (it now includes sitename) but the _page_ title gets broken: I have {"en-GB":"page_title_en","it-IT":"page_title_it"} as title override and with this fix the override is no more used in the page (it was before this fix) since the Joomla article title is used instead.
let me know if you need more tests.
cheers

Giuse

**Comment by sebastienheraud** [comment]
Hi Giuse,

Please add some screenshots, as I'm not able to understand/replicate the issue.

Thanks,
Saba

**Comment by Giuse69** [comment]
Hi, I can describe hereafter in more details and later (probably tomorrow morning) add also screenshots:
**Settings**
List Type:
- Name = "Mount"
- Fields: mount_name_en, mount_name_it. Each with a Language restriction to show only en/it field based on current language.
- Content Configuration: Override Page Title = {"en-GB":"mount_name_en","it-IT":"mount_name_it"}
One Content Item of type "mount"
- article title "Mount - Panasonic"
- mount_name_en = "Micro Four Thirds"
- mount_name_it = "Micro Quattro Terzi"

**Before the fixes (Front End, English)**
Browser title: "Micro Four Thirds"
==> Bug since it should be "Micro Four Thirds - Sitename", Sitename is missing
Page header (class="page-header"><h2 itemprop="headline">): "Micro Four Thirds"
==> OK

**After the fixes (Front End, English)**
Browser title: "Micro Four Thirds - Sitename"
==> fixed, sitename has been added
Page header (class="page-header"><h2 itemprop="headline">): "Mount - Panasonic"
==> Bug, since this is article title and not mount_name_en that should override that.

Is it more clearer in this way?
cheers

Giuse

**Comment by sebastienheraud** [comment]
Hi Giuse,

Thanks for the details.
So if you speak about the _page header/healine_ and not about the _page title_, then yes I understand.
And yes it has changed as the override was not supposed to alter the article title, but only the page title.

The commit fixes both the issue you reported and this one: https://github.com/Octopoos/SEBLOD/issues/544

Saba
