### ISSUE TITLE
Problem with the content plugin

### ISSUE THREAD

**Issue by philigrane** [Octopoos/SEBLOD#552]
Hey, Sorry for my english. There must be a problem with the Content SEBLOD plugin. When it is active all codes of other plugins appear instead of being managed. I changed the order but nothing works.
Joomla 3.9.3 Stable - Seblod 3.17.3 (Chrome, Safari, Firefox)
Regards

**Comment by sebastienheraud** [comment]
Hi,

Please post this issue on our forums, including additional details (with which 3rd party content plug-in, settings, on which view, ...).

There has been no change with the way our content plug-in works for a long long time.
The following things can help:
* Changing this ordering of plug-in
* SEBLOD Options > General > Prepare Content

and in any case some plug-ins which truncate/alter the introtext are just not compatible.

I'm closing this issue for now.
Saba
