### ISSUE TITLE
Free Content Type - $content->delete( $pk ); <<-- does not update #__cck_core

### ISSUE THREAD

**Issue by Bucklash** [Octopoos/SEBLOD#554]
Hi folks

I created a table:
#__cck_store_free_map

I created the corresponding content type (FREE)

CREATE
`$content->create( $content_type, $data )`
#__cck_store_free_map = UPDATED
#__cck_core = UPDATED

DELETE
`$content->delete( $pk )`
#__cck_store_free_map = UPDATED
#__cck_core = **NOT UPDATED**

Is this confirmed?

Thanks

Jon :D

[https://www.seblod.com/community/forums/forms-content-types/free-content-type-content-delete-pk](url)

**Comment by sebastienheraud** [comment]
Hi Jon,

I would guess for no issue with the code, but only a missing entry in the #__cck_core_objects table.
Please try to run the SQL query found in the following file: https://github.com/Octopoos/SEBLOD/blob/master/administrator/components/com_cck/install/upgrades/3.16.4.sql

Saba
