### ISSUE TITLE
PHP Warnings in checkbox.php and checkbox_dynamic.php

### ISSUE THREAD

**Issue by Ptacku** [Octopoos/SEBLOD#557]
I'm seeing a lot of two similar warnings in my Apache logs:

PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/plugins/cck_field/checkbox/checkbox.php on line 333\n

PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/plugins/cck_field/checkbox_dynamic/checkbox_dynamic.php on line 385\n

I'm not aware of any actual malfunctions, it's probably just a warning, but maybe it could be fixed anyway.

**Comment by sebastienheraud** [comment]
Hi,

Thank you. Looks like the same as https://github.com/Octopoos/SEBLOD/issues/524 and will be fixed (cf commit) in upcoming 3.17.4 and “More” plugins will be released with similar fix as well in a few days.

Regards,
Saba
