### ISSUE TITLE
link_options size of #__cck_core_search_field and #__cck_core_type_field.

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#57]
Hi, 

we would like to expand the size of the columns link_options in the tables #__cck_core_search_field and #__cck_core_type_field.

Currently the size is varchar(1024) and we would like TEXT because we need to add more options in some plugins of ours.

thanks

**Comment by Lazerproof** [comment]
+ 1 for that. Please, make us feel a little bit happier.

**Comment by klas** [comment]
Confirmed, still here.

**Comment by sebastienheraud** [comment]
Hi,
This has been changed for all new installations (only). https://github.com/Octopoos/SEBLOD/commit/d6fddd522b2ed2e332a20fc26c4f64c26003cda1
And it will be available starting the next release.
Regards,
Saba.
