### ISSUE TITLE
Calendar form field ignores the Storage Field of "raw"

### ISSUE THREAD

**Issue by jessedyck** [Octopoos/SEBLOD#581]
# Issue
JForm - Calendar field ignores the Storage Field option of "raw" when generating a form field, and instead will use User UTC. This is primarily an issue on imported dates without time strings, as the value will get converted to an incorrect timezone when displaying the form, and then will be saved with that incorrect timezone.

# Fix
We can tweak the ternary for the [filter in the field's XML](https://github.com/Octopoos/SEBLOD/blob/master/plugins/cck_field/jform_calendar/jform_calendar.php#L163) to allow the *raw* value to be used. I've used the same logic as [Joomla's Calendar field](https://github.com/joomla/joomla-cms/blob/3.9.13/libraries/joomla/form/fields/calendar.php#L165), the 'raw' option will take effect.

From:
````
filter="'.( isset( $options2['format_filter'] ) && $options2['format_filter'] ? 'user_utc' : 'server_utc' ).'"
````

To:
````
filter="'.( (string) $options2['format_filter'] ? (string) $options2['format_filter'] : 'USER_UTC' ).'"
````

I'll submitted a PR with this change.

**Comment by sebastienheraud** [comment]
Thanks @jessedyck.
https://github.com/Octopoos/SEBLOD/pull/582 was merged, and a slight update https://github.com/Octopoos/SEBLOD/commit/7a3cec485ee7df78eb269a07cdf57e62630dcadf after that, but it should be fine.
Saba
