### ISSUE TITLE
Select Dynamic Cascade - language selection for options on ajax task does not work

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#585]
In Select Dynamic Cascade, language selection for picking up values from <table_name>_[lang] does not work correctly in select dynamic field after the first one but always select main site language.
From my investigations, that's why the language is retrieved via an ajax call made by the browser to _select_dynamic_cascade/tmpl/form.php_ and in Joomla 3.x current language cannot be retrieved in an external script (_tmpl\form.php_ is external since it is called by the browser).
An easy fix is to change _assets/js/script-1.5.0.min.js_ in line 16 (after prettifying the JS):
change
`var s = d + "index.php?option=com_cck&format=raw&task=ajax&" + Joomla.getOptions("csrf.token") + "=1&referrer=plugin.cck_field.select_dynamic_cascade&file=plugins/cck_field/select_dynamic_cascade/tmpl/form.php";
`
to
`var s = d + "index.php?option=com_cck&format=raw&task=ajax&" + Joomla.getOptions("csrf.token") + "=1&referrer=plugin.cck_field.select_dynamic_cascade&file=plugins/cck_field/select_dynamic_cascade/tmpl/form.php`&lang=`"` + document.documentElement.lang`;`

This sets current language from the caller and so backend can use the correct language.
cheers

Giuse

**Comment by Giuse69** [comment]
hi, any update on this? I can do a simple PR if needed
regards,

Giuse

**Comment by Giuse69** [comment]
A new version 1.6 of Seelct Cascade has just been published and now I don't see anymore the problem, so I am closing this issue, though I'd have liked to see a feedback/confirmation

**Comment by sebastienlapoux** [comment]
Thank a lot @Giuse69 !
