### ISSUE TITLE
Joomla Extension Update System is NOT updating SEBLOD

### ISSUE THREAD

**Issue by Sophist-UK** [Octopoos/SEBLOD#600]
The Joomla Extension Update System is NOT updating SEBLOD. I believe that this is because the SEBLOD update server http://update.seblod.com/pkg_cck.xml is not in the list of update servers in my Joomla Extension / Update Sites list. The entry in the [SEBLOD package manifest](https://github.com/Octopoos/SEBLOD/blob/master/administrator/manifests/packages/pkg_cck.xml) says:
```
	<updateservers>
		<server type="extension" priority="1" name="SEBLOD 3.x Core Updates">http://update.seblod.com/pkg_cck.xml</server>
	</updateservers>
```
which according to the [Joomla documentation](https://docs.joomla.org/Deploying_an_Update_Server) is correct for a single package like SEBLOD.

So I cannot explain why it was not added to the Update List when I installed SEBLOD. But when I clicked Rebuild in the Update List it was added to the list and the latest version was found.

**Comment by joomleb** [comment]
Hi guys, 
on 4 p9 release, this is still an open issue, Right ?

**Comment by joomleb** [comment]
Hi guys,
@sebastienheraud
on Joomla 4.3.1 + SEBLOD 4.0.4 release, this is still an open issue, Right ?
Please, Can you confirm it ?

**Comment by joomleb** [comment]
Hi,
@sebastienheraud on Joomla.4.3.2 + Seblod 4.0.5 the availability of 4.0.6 version appeared, so,  I suppose you worked and solved this issue.

Please, Can you confirm and close the ticket ?

**Comment by sebastienheraud** [comment]
Hi @joomleb,
The XML has been updated yes.
Thanks,
Saba
