### ISSUE TITLE
Security updates in core and waiting for Seblod compatability

### ISSUE THREAD

**Issue by joomkit** [Octopoos/SEBLOD#603]
IF the latest Joomla version of Joomla is 3.9.20 but Seblod is only compatible to 3.9.19 aren't we left exposed to security vulnerabilities in Core Joomla whilst we wait for Seblod to 'catch up'? How can we avoid this (apart from the obvious)

**Comment by sebastienheraud** [comment]
Hi,
SEBLOD (almost) never needs to "catch up", as the latest SEBLOD release is (almost) always compatible without any change to any minor version of Joomla!. I'd guess that this one is fine as well, we haven't confirmed it.
As long as a Joomla! minor version does not break stuff (from previous release) or keeps B/C we are good to go.
We'll confirm on the home page of SEBLOD.com on Monday.
Saba
