### ISSUE TITLE
PHP notice for undefined var in free storage location

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#604]
When saving a content type object of type "free", I am getting these PHP notices in the log
`Undefined` index: join in /var/www/html/plugins/cck_storage_location/free/free.php on line 272
PHP Notice:  Undefined index: join in /var/www/html/plugins/cck_storage_location/free/free.php on line 311`

**Comment by sebastienheraud** [comment]
Hi Giuse,
This one https://github.com/Octopoos/SEBLOD/commit/ed3e6d80b9f97967181b58401b1e3cdf71e2660f should remove the notice.
Thanks,
Saba
