### ISSUE TITLE
Only the first groupx is stored (if groupx storage isn't introtex)

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#61]
Hi

If you have more than one groupX in a form and each groupX is stored in another place than the Introtext, only the first Groupx fields are stored when you save the content.

Example:

1. Create a group1 content type with two fields:
- group1_storage (Text area, 4096 long), discard it from the form
- group1_name (text, no storage)

2. Create a group2 content type with two fields:
- group2_storage (Text area, 4096 long), discard it from the form
- group2_name (text, no storage)

3. Create your main content type myContent with two fields
- mygroup1 : GroupX on group1. Storage = custom / free/ #__cck_store_form_group1 / group1_storage
- mygroup2 : GroupX on group2. Storage = custom / free/ #__cck_store_form_group2 / group2_storage

4. In back (or front) try to create some myContents. 
Only the first groupX will be stored

thanks

cyril

**Comment by lionelratel** [comment]
No bug, simply a misunderstood on the storage CUSTOM.
closed
