### ISSUE TITLE
Webp support issue

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#612]
Hi, I have enabled Webp support. The webp images were created successfully, but they do not display correctly in the browser. Images are of the form name_file.webpjpg
![2020-12-15_194817](https://user-images.githubusercontent.com/19167244/102246210-8ac29780-3f0f-11eb-9514-059eee8f2f03.jpg)

**Comment by sebastienheraud** [comment]
Hi @kkaazzoo,

Thanks, we'll check asap and apply a fix (as for now we have only used it by calling path from an HTML typo to output a <picture></picture>)

Sebastien

**Comment by sebastienheraud** [comment]
Hi @kkaazzoo,

Please have a try with SEBLOD 3.20.1, it should be OK now.

Thanks,  
Saba

**Comment by kkaazzoo** [comment]
> Hi @kkaazzoo,
> 
> Please have a try with SEBLOD 3.20.1, it should be OK now.
> 
> Thanks,
> Saba

thanks, now it works

**Comment by sebastienheraud** [comment]
Thanks.
