### ISSUE TITLE
Import bug ?

### ISSUE THREAD

**Issue by pulsarinformatique** [Octopoos/SEBLOD#613]
Hi 

with seblod 3.19.0 with importer 1.12.0 when we try to import a very simple CSV file (without any seblod custom fields) everything works as expected except the introtext which is always the FIRST value in the CSV file for all the contents that are created:

if you try:

title;alias;introtext;state;catid;created;created_by;created_by_alias;modified;modified_by;publish_up;publish_down;images;urls;attribs;version;ordering;metakey;metadesc;access;hits;metadata;featured;language;xreference;note;tags title1;title1;cont1;1;22;08/01/2020 17:23;431;;17/12/2020 07:21;0;17/12/2020 07:21;0000-00-00 00:00:00;{};{};{};1;0;;;1;2277;{};0;*;;; 

title2;title2;cont2;1;22;14/06/2020 11:29;431;;17/12/2020 07:21;0;17/12/2020 07:21;0000-00-00 00:00:00;{};{};{};1;0;;;1;2804;{};0;*;;;

you willimport title1 and title2 articles but both of them will have "cont1" in their introtext.

is it a bug?

thanks

Cyril

**Comment by pulsarinformatique** [comment]
Hello .
Can anyone confirm it please ?

**Comment by pulsarinformatique** [comment]
Hi

still no answer please ?

thanks

cyril

**Comment by sebastienheraud** [comment]
Thank you @pulsarinformatique!

Closing this issue now, as SEBLOD Importer 1.13 includes a fix.

Saba
