### ISSUE TITLE
Button Free Action = Edit problem upgrading to Seblod 3.20.1

### ISSUE THREAD

**Issue by narcisob** [Octopoos/SEBLOD#617]
When upgrading to Seblod 3.20.1, Button Free fields changes in "Link" -> "Form" -> "+" -> "Action". After upgrading, we find existing "button free" fields with Action = Edit, and many forms with custom variables now saves in another content type!! (the one in the List where we have the button free field to create a new entry in another Content Type). Changing to Action = Add restores original behaviour.

Pre Seblod 3.20.1:
List (Content Type 1) + Button Free -> Form + Content Type (Form) = Content Type 2  ==> when we click the button we create a new entry in Content Type 2

Seblod 3.20.1:
List (Content Type 1) + Button Free -> Form + Action=Edit (by deafult); Content Type (Form) = Content Type 2  ==> when we click the button we change the Content Type 1 article to Content Type 2, and we lost Content Type 1 field information!!!

If we change Action = Add, we get pre Seblod 3.20.1 behaviour: OK

It is very dangerous we get Action = Edit by default after upgrading.

Regards,

Narciso Benedicto.

**Comment by sebastienheraud** [comment]
Hi @narcisob,

Thanks for the sharing the issue, and related details. We published a new release (and some info) on the changelog: https://www.seblod.com/changelogs#SEBLOD_3202_20210308 and https://github.com/Octopoos/SEBLOD/commit/1bae1dc325f430b49a35515ae3cf85536054dc97

Saba
