### ISSUE TITLE
Change in method from $site->groups to $site->usergroups not documented or included in changelogs.

### ISSUE THREAD

**Issue by steve-genilogic** [Octopoos/SEBLOD#618]
Upgrading from 3.18.2 to 3.20.1 introduced various errors across our site due to `$site->groups` no longer returning a value. I needed to go through and change all occurrences in all fields to `$site->usergroups` for this to work.

I feel this should have been documented or included in the changelogs.

**Comment by steve-genilogic** [comment]
This is the commit that drops it https://github.com/Octopoos/SEBLOD/commit/cf259e3035e16972a197ae705c369e9c7b807dd5#diff-5e79ed267cfe012d852eb72c18311cc0ad2c5fe351a17088cca5b143022ebcc3.

**Comment by sebastienheraud** [comment]
Hi Steve,

On the 3.19.0 changelog, there is the following line:
```
# Multi-sites system on MySQL 8.0 issue fixed.
```
as "group" is restricted/disallowed on the version 8.0

Indeed, it could have been more clear about the change itself, but in the meantime, this change only affect custom query/code.

Sebastien
