### ISSUE TITLE
permissions dont work

### ISSUE THREAD

**Issue by helgator** [Octopoos/SEBLOD#62]
Permissions and inherritance dont work at all in SEBLOD. The only thing that works is setting permissions on the content type. But that's about it. You cannot even set permissions on the article level not to mention categories although the permissions tab is there. 
The user would expect the same behavior in SEBLOD as in native Joomla content as outlined by the Joomla permissions creator Andrew Eddie :
http://www.theartofjoomla.com/home/5-commentary/84-introducing-the-new-permissions-in-joomla-16.html

**Comment by melihtas** [comment]
Confirmed. Single article and category level permissions are not working.

**Comment by klas** [comment]
I tested edit permission on article level and it works ok with seblod 3.7.2 with native button. Will do some further tests with seblod buttons and direct access to edit form.

**Comment by klas** [comment]
Please give us step by step instructions how to reproduce this.

**Comment by sebastienheraud** [comment]
Hi,
SEBLOD uses the permissions based on the content types.. which makes more sense.
And indeed, the 2nd path of permissions, let's say "Content" permissions are not natively applied.
There is one way to manually apply them on Forms or Content/List using the following plug-ins:
- on Forms: you should use a Break field with the Permissions restriction plug-in applied on it.
- on Content/List: you can apply the Permissions restriction plug-in on your Edit button.
Joomla! ACL Pack: http://www.seblod.com/store/extensions/10872
SEBLOD Break Field: http://www.seblod.com/store/extensions/25892
I'm closing this issue. And of course, we'll see if it can be improved in the future to be natively supported.
Regards,
Saba.
