### ISSUE TITLE
support php 8.x

### ISSUE THREAD

**Issue by step-di** [Octopoos/SEBLOD#623]
Please test seblod on php 8.x.
When updating, specify in the change log about the support for php 8, when it will be implemented.
I am having problems with seblod when enabling php 8.0.5

**Comment by sebastienheraud** [comment]
Hi @step-di,

* 3.23: https://github.com/Octopoos/SEBLOD/blob/master/administrator/components/com_cck/_CHANGELOG.php
* 4.0 RP 5: https://github.com/Octopoos/SEBLOD/blob/4.0/administrator/components/com_cck/_CHANGELOG.php

Feel free to test with upcoming releases, and please open another GitHub issue (including details/screenshots) if you notice any specific error.

Thanks,
Saba

**Comment by sebastienheraud** [comment]
Hi @step-di,

Release Preview 5 is now available: https://github.com/Octopoos/SEBLOD/releases/tag/4.0.0-rp5

Currently not aware of any specific issue on PHP 8.1.6.
https://demo.seblod.com runs PHP 8.1.10 and it seems OK

Please share any issue if you find one.

Thanks,
Saba
