### ISSUE TITLE
Field X broken

### ISSUE THREAD

**Issue by olegischinski** [Octopoos/SEBLOD#626]
Field X seems to be broken since 3.21.3.
E.g. in connection with an image upload field it does not save any value, but writes ::array:: into the database.
If you open and save an existing article, former values will be deleted.

**Comment by sebastienheraud** [comment]
Hi,
**upload_file** and **upload_image** updates uploaded here: https://github.com/Octopoos/SEBLOD/releases/tag/3.21.3
Could you please have a try and confirm? Once confirmed those will be included in SEBLOD 3.21.4
Thanks,
Saba

**Comment by olegischinski** [comment]
hello Saba,
the updated plug-ins seem to work. I can confirm this for the image upload field, everything works as expected. (I do not use the file upload field on my site).
Thank you very much!
Oleg

**Comment by sebastienheraud** [comment]
Hi Oleg,
Thank you.
A new package will be released this week.
Saba

**Comment by stefeschefe** [comment]
After a customer reported problems, I also applied the patch. I can confirm that now both the image and the image title are saved and output correctly again.

**Comment by sebastienheraud** [comment]
Thanks

**Comment by sebastienheraud** [comment]
Hi,
SEBLOD 3.21.4 is released: https://github.com/Octopoos/SEBLOD/releases/tag/3.21.4
Saba
