### ISSUE TITLE
Accordion Template doesn't work in Helix Ultimate template

### ISSUE THREAD

**Issue by nicolastorgato** [Octopoos/SEBLOD#637]
Hi,

I'm using the Accordion list template in a [website](http://93.62.181.49/sad-treviso/index.php/helix) with Helix Ultimate template by Joomshaper, and as you can see the accordion functionality doesn't work.

I've already asked on StackOverflow (https://stackoverflow.com/questions/71296787/accordion-list-doesnt-work-in-helix-ultimate-template) and apparently your Accordion code uses Jquery methods, which Bootstrap5 does not support. I'm wondering if the Accordion code will be updated in order to be compatible with Bootstrap5. Otherwise, how could I solve the problem?

Thanks!

**Comment by sebastienheraud** [comment]
Hi Nicola,

The Accordion template uses the Bootstrap version included in Joomla.
So yes on a Joomla! 3, as Bootstrap 2 is included it would work properly with protostar (or any other bootstrap 2 template).
Helix Ultimate runs its own version of Bootstrap (version 5 I guess) so it may not work.

Joomla! 4 includes the latest Bootstrap (version 5), and as you can see on our demo site for Joomla! 4, the accordion template works https://demo.seblod.com/joomla4/seblod-templates/accordion/standard.
Only a minor issue about the first pane (not open by default).

Saba
