### ISSUE TITLE
Deprecated MessagesSeblod for Joomla 4 RC3

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#639]
Hi there! I just tested the Seblod RC3 and have this deprecated messages, maybe it's helpful:

Deprecated
: Required parameter $user follows optional parameter $config in
/joomla/plugins/cck_storage_location/free/free.php
on line
156

Deprecated
: Required parameter $user follows optional parameter $config in
joomla/plugins/cck_storage_location/joomla_article/joomla_article.php
on line
263

Deprecated
: Required parameter $user follows optional parameter $config in
joomla/plugins/cck_storage_location/joomla_category/joomla_category.php
on line
242

Deprecated
: Required parameter $user follows optional parameter $config in
joomla/plugins/cck_storage_location/joomla_user/joomla_user.php
on line
191

Deprecated
: Required parameter $user follows optional parameter $config in
joomla/plugins/cck_storage_location/joomla_user_group/joomla_user_group.php
on line
169

**Comment by sebastienheraud** [comment]
Hi Elisa,
This is fixed in upcoming Release Preview 2.
Note: those are not related to SEBLOD 4 nor Joomla! 4, but related to PHP 8.x
Full PHP 8.x support for SEBLOD has not be announced  yet, so additional issues may be found.
Saba
