### ISSUE TITLE
Seblod 4 RC3 - Seblod Dashboard not reachable

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#641]
When I click on components » Seblod 4 the submenu opens with importer, exporter and updater but its not possible to reach the seblod dashboard

**Comment by sebastienheraud** [comment]
Hi Elisa,
"Core" is available (as a submenu item - and should remain there) in upcoming package... in order to access SEBLOD 4.
Thanks,
Saba

**Comment by coolcat-creations** [comment]
Hi Saba, but when will the next Package be available, will it be already a stable release? thank you  :-)
