### ISSUE TITLE
Seblod 4 RC3: error 500 when I create a list then I click on list view

### ISSUE THREAD

**Issue by KillianCoulange** [Octopoos/SEBLOD#643]
I create a blank list.
I give it a name.
then I click on list view button
the page is loading and got an error 500 (index.php?option=com_cck&task=search.apply)
and when I scroll an error says "mainPos is undefined" in cck.backend-3.22.0.min.js:224:12

**Comment by sebastienheraud** [comment]
Hi Killian,
Fixed in upcoming package as well.
Thanks,
Saba
