### ISSUE TITLE
Insufficient filtering of url parameters in seblod lists

### ISSUE THREAD

**Issue by kureshtar** [Octopoos/SEBLOD#645]
XSS example:
https://www.seblod.com/community/blog?%22%3E%3Cqss%3E=
result:
![image](https://user-images.githubusercontent.com/52793935/169691927-4d431332-4452-4ab9-90f8-376c5ece071b.png)
PS: There is no such problem in Joomla lists.

**Comment by sebastienheraud** [comment]
Hi @kureshtar,
Thank you for reporting.
Indeed this was specific to the pagination links.
A fix has been deployed on the site, and an upcoming package will be released shortly.
Thanks!
Saba
