### ISSUE TITLE
Field 'fulltext' doesn't have a default value

### ISSUE THREAD

**Issue by salahjaafar** [Octopoos/SEBLOD#647]
Hello, I work under joomla 4 and seblod preview 2

when submitting the form I receive this message "Field 'fulltext' doesn't have a default value"
![Screenshot 2022-08-05 at 11-54-42 أضف متربص - منظومة إدارة المتربصين](https://user-images.githubusercontent.com/47123877/183063304-d769cd22-0bdd-4519-b619-7657d5084005.png)

**Comment by sebastienheraud** [comment]
Hi,
Thanks for reporting.
This is fixed in upcoming Release Preview 3
Saba

**Comment by coolcat-creations** [comment]
I still have this error :(

**Comment by salahjaafar** [comment]
Install latest versions and enable joomla 3 lagacy mode
![Screenshot 2023-07-15 at 09-26-09 SEBLOD Options - Psychotrope V 4 2 - Administration](https://github.com/Octopoos/SEBLOD/assets/47123877/a8072cf0-8ff7-4b14-94e2-fc91a95c9efe)

**Comment by coolcat-creations** [comment]
Thank you, the after install screen was not clear for me, I thought this Option sets itself. solved indeed.
