### ISSUE TITLE
"Joomla! Article" field. Compile Error: require_once(): Failed opening required

### ISSUE THREAD

**Issue by schekutiev** [Octopoos/SEBLOD#649]
Hi. I'm testing pkg_seblod_4.0.0.Release.Preview.2b on Joomla 4.1.5. Just upgraded from 3.10.11 via instruction https://www.seblod.com/community/blog/seblod-4-0-series-2). 
Using seb_minima template. Some articles use "Field X". At first, I thought "Field X" cause problems. "Article (related)" does.  "Joomla! Article" field.  I can not even change related item. Changing, saving - item is still marked as chosen. 
On frontend, while accessing article, getting following error:

`Compile Error: require_once(): Failed opening required '/home/user/project/www/components/com_content/helpers/route.php' (include_path='.:/usr/share/php')`

**Symfony\Component\ErrorHandler\Error\
FatalError**

.../www/plugins/cck_storage_location/joomla_article/joomla_article.php (line 867)

`require_once JPATH_SITE.'/components/com_content/helpers/route.php';`

Joomla 4.1.5
seblod_4.0.0.Release.Preview.2b
Cassiopeia

Linux debian 5.10.0-16-amd64
10.5.15-MariaDB-0+deb11u1
utf8mb4_general_ci
PHP	7.4.30

**Comment by sebastienheraud** [comment]
Hi Eugene,

Thank you for reporting.
Old Joomla! router files are no more loaded in upcoming Release Preview 5 (on Joomla! 4.x).
Please have a try once it is available, and feel free to confirm.

Saba

**Comment by schekutiev** [comment]
Sebastien, thank  you for the response!
I just upgraded my project locally from Joomla 3.10.11 to Joomla 4.2.3 (with SEBLOD 4.0.1.Release.Preview.5) and everything works great now even on PHP 8.1.11. I'm still testing it though.
Thanks again!

**Comment by sebastienheraud** [comment]
Sounds great! Thank you for the feedback Eugene.
A small package (RP6) which includes 2 additional PHP 8.x fixes is now available.
Closing this issue now.
Saba
