### ISSUE TITLE
Adding item in a groupX in frontend don't work (JS error)

### ISSUE THREAD

**Issue by lionelratel** [Octopoos/SEBLOD#65]
SEBLOD 3.6.2
In frontend, When editing an article which have a GroupX, clicking on the "+" of the groupX generate a JS error and no item is added.

**Comment by sebastienheraud** [comment]
Hi Lionel,

Thanks for the fix. Merged in master.
https://github.com/Octopoos/SEBLOD/commit/a0b016e130c5f79873a66975a1659f9668c2bb48?diff=unified

Saba
