### ISSUE TITLE
Error message when you call the Updater component

### ISSUE THREAD

**Issue by castor01** [Octopoos/SEBLOD#652]
used: PHP 8.1.2
![update_not_possible_3](https://user-images.githubusercontent.com/13590527/186609711-cc116847-bbfe-4a1f-9f78-3779a70cb98a.jpg)

**Comment by kimbare** [comment]
I am also having this problem, even after updating to SEBLOD 4.0.1 Preview 5

**Comment by castor01** [comment]
This problem still exists, even after updating to SEBLOD 4.0.1 Preview 5

**Comment by castor01** [comment]
This problem still exists, even after updating to SEBLOD 4.0.1 Preview 6

**Comment by castor01** [comment]
This problem still exists, even after updating to SEBLOD 4.0.1 Preview 7

**Comment by joomleb** [comment]
Hi guys, 
PHP 7.4.33 + Joomla 4.2.8 + Seblod 4.0.2 rp8 + Updater 1.4.3

An error has occurred.
0 Class 'InstallerModelUpdate' not found 

Call stack

1 | () | JROOT/administrator/components/com_cck_updater/models/cck_updater.php:16
2 | require_once() | JROOT/libraries/src/MVC/Model/LegacyModelLoaderTrait.php:89
3 | Joomla\CMS\MVC\Model\BaseModel::getInstance() | JROOT/libraries/src/MVC/Factory/LegacyFactory.php:71
4 | Joomla\CMS\MVC\Factory\LegacyFactory->createModel() | JROOT/libraries/src/MVC/Controller/BaseController.php:537
5 | Joomla\CMS\MVC\Controller\BaseController->createModel() | JROOT/libraries/src/MVC/Controller/BaseController.php:703
6 | Joomla\CMS\MVC\Controller\BaseController->getModel() | JROOT/libraries/src/MVC/Controller/BaseController.php:605
7 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_cck_updater/controller.php:32
8 | CCK_UpdaterController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_cck_updater/cck_updater.php:27
10 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
12 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
13 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
14 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
15 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
16 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
17 | require_once() | JROOT/administrator/index.php:32

**Comment by joomleb** [comment]
Hi guys,
PHP 7.4.33 + Joomla 4.3.1 + Seblod 4.0.2 rp9 + Updater 1.4.3

Please, Do you have any roadmap for this fixing ?

**Comment by sebastienheraud** [comment]
Hi All,
SEBLOD Updater 1.5.0 will be released tomorrow.
Saba
