### ISSUE TITLE
Cancel Button in "New Form & Content Type" Modal does not work

### ISSUE THREAD

**Issue by svenlewerentz** [Octopoos/SEBLOD#654]
The "Cancel button" in the modal window which lets me select a content type does not work (J.4.2.2 and Seblod Release Preview 4)

![image](https://user-images.githubusercontent.com/351596/188654862-2d330a20-2588-4682-ad79-3bab78ce39ca.png)

**Comment by sebastienheraud** [comment]
Hi Sven,

Thank you for reporting.
Fixed in upcoming Release Preview 5.

Saba
