### ISSUE TITLE
Form & Content Type Error

### ISSUE THREAD

**Issue by ChiptunerUkraine** [Octopoos/SEBLOD#657]
when trying to enter the Form and Content Type: the page does not open, it asks to reload again. The site is still working. Tried hosting and open server. What could be the problem?
What other information to provide?
![2022-09-13_193555](https://user-images.githubusercontent.com/19249433/189958443-4f3d1bc2-012a-4d5a-b00a-ec8d4f60bdac.png)

![2022-09-13_193655](https://user-images.githubusercontent.com/19249433/189958438-66da26f8-4c48-46b2-ab0a-929b02784b41.png)

**Comment by sebastienlapoux** [comment]
Hi @ChiptunerUkraine,

Check apache max_input_vars and put it to 4000.

**Comment by ChiptunerUkraine** [comment]
Did! Did not help. Problem still exists.

**Comment by Grag1** [comment]
I have also noticed the same problem. It also exists with list and search types, but only when PHP 8.0 (8.1 ?) is used. I can open the page as many times as I want, the error keeps happening. With PHP 7.4 the program works as it should.

Nevertheless PHP 7.4 will have reached EOL in a short time. So it is not a solution to stay with PHP 7.4.

Best regards.

**Comment by sebastienheraud** [comment]
Hi,

This PHP 8.0 issue (in the back-end UI) is fixed in upcoming SEBLOD 3.23 release.
Feel free to open another GitHub issue if you notice any another error once the release is available.

Thanks,
Saba
