### ISSUE TITLE
Default image or default file deleted when content deleted

### ISSUE THREAD

**Issue by lionelratel** [Octopoos/SEBLOD#66]
SEBLOD 3.6.2 - 
Context : on ulpoad_file or upload_image when settind a default value.
Bug : when deleting the content, the default image/file is deleted too.

**Comment by sebastienheraud** [comment]
Hi Lionel,
Thank you for the fix.
Here is the commit: https://github.com/Octopoos/SEBLOD/commit/ee4853ae4b9dd28b826f32719398049ac8ad880d
Saba.
