### ISSUE TITLE
Cannot add a beforestore field

### ISSUE THREAD

**Issue by kimbare** [Octopoos/SEBLOD#660]
With both Seblod 4.0.1 Release Preview 4 and Preview 5 I cannot add a before store field.  It hangs up for ever with the message "PLG_CCK_FIELD_VALIDATION_AJAX_AVAILABILITY_ALERT3 and won't go any further until I click on the COM_CCK_CLOSE button.  And yes, the code pack is installed.  (I have not tried any of the others in the code pack to see if they work.)
![Cannot add beforestore](https://user-images.githubusercontent.com/24217410/193375882-b8580981-8013-4607-95a3-7f6ac7ea2c44.jpg)

**Comment by sebastienheraud** [comment]
Hi @kimbare,
Thank you for noticing/reporting.
Fixed in upcoming rp8.
Saba
