### ISSUE TITLE
Upload Image Notice during saving

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Octopoos/SEBLOD#662]
Hi.
I stopped saving before AferStore event and find this message. 
`Notice: Undefined index: name in .../data/www/inoposter.ru/plugins/cck_field/upload_image/upload_image.php on line 535`
It;s not a bug, of course, but we can make SEBLOD better ;)

**Comment by sebastienheraud** [comment]
Hi Ilya,
OK, notice should be fixed with https://github.com/Octopoos/SEBLOD/commit/2af509ffd8a969b0230afcf64916bbe8c6c02147.
Thank you.
Saba
