### ISSUE TITLE
Warning Duplicate column name 'path'. Package Update: There was an error installing an extension: plg_content_cck.zip

### ISSUE THREAD

**Issue by schekutiev** [Octopoos/SEBLOD#663]
**Error
Error installing package.**

Hi everyone. With last SEBLOD releases (Release Preview 5, Release Preview 6) I'm getting warning after first attempt to upgrade  SEBLOD from current v 3.23.0 to v 4.0.1. Looks like it is warning only as package still upgrades. If I do upgrade one more time system does not give any errors at all and everything looks ok except 'Getting started with SEBLOD 3.X' message. On the components page it is [SEBLOD Core](https://www.seblod.com/) is a powerful App Builder & CCK for Joomla!
Version 4.0.1 Release.Preview.6 © 2009 - 2022. (check screenshots)

If I do upgrade SEBLOD  on PHP **7.4.32**, even I'm getting the warning after first attempt to upgrade SEBLOD on **Joomla 3** I have access to the Content Types in  Form & Content Type Manager and looks like everything works fine. In List & Search Type I have access to items, but markup is broken and I don't have full access to Fields tab and Template tab. Configuration tab looks blank and all other tabs do not respond at all. (check last two screenshots). **THIS IS OK** - SEBLOD 4.x has different markup and it does not mean to be used with Joomla 3. After upgrade to Joomla 4 everything will work just fine!

**Upgrade SEBLOD 3x to 4x using PHP 8.x does not work...**

![error](https://user-images.githubusercontent.com/15309520/194627916-3c3ac804-3070-4bc3-a57a-e122a68c0d60.png)

If I do SEBLOD upgrade using PHP 8.x (8.0.24 or 8.1.11) I'm getting an error (check screenshot above) which remains even after Joomla upgrade. To me the easiest and safest way to jump from Joomla 3/Seblod3 to Joomla 4/Seblod4 is updating using PHP 7.4. **The problem**:  after switching back to PHP 8.x error is still there...

![php8_error](https://user-images.githubusercontent.com/15309520/194636462-04079d80-86ae-4ec8-8c04-5830e9e0df8a.png)

PHP setting pretty much defaults, besides:

- max_input_vars = 3000
- post_max_size = 10M
- upload_max_filesize = 10M
- max_file_uploads = 50

### Warning Duplicate column name 'path'. Joomla 3.x => Seblod 3.x to Seblod 4.x Package Update

![install_warning_1](https://user-images.githubusercontent.com/15309520/194616709-197a74dc-ee38-4525-963b-091c9b8e0cac.png)
![install_warning_2](https://user-images.githubusercontent.com/15309520/194616713-af3f3b23-ae05-4bf1-bdee-bf7a45516964.png)
![install_warning_3](https://user-images.githubusercontent.com/15309520/194616715-5bb9b696-4b18-4b57-a30d-aeec5c4e334d.png)
![install_warning_4](https://user-images.githubusercontent.com/15309520/194616719-5af5076e-e2c3-4095-a080-df002ef4d5f4.png)
![install_warning_5](https://user-images.githubusercontent.com/15309520/194616720-a83f3d69-7a76-44dd-9b84-0b4182236b81.png)
![install_warning_6](https://user-images.githubusercontent.com/15309520/194616721-3b3f1c83-b601-42e6-bd09-1006feb46b2f.png)
![2022-10-07_103059](https://user-images.githubusercontent.com/15309520/194616723-1874db21-c7bf-44b7-b128-37cdd60b0858.png)

### List & Search Type items | SEBLOD 4.x on Joomla 3.x

![install_warning_7](https://user-images.githubusercontent.com/15309520/194620438-d8e1a35b-7a6f-4666-9ae3-97db162263b5.png)
![install_warning_8](https://user-images.githubusercontent.com/15309520/194620440-ed726050-3715-4aac-9e40-206f2c032f4c.png)

**Comment by sebastienheraud** [comment]
Hi @schekutiev,
The issue Duplicate column name 'path' is fixed using latest package.
There was a regression in the upgrade process since the release of SEBLOD 3.23.x
Feel free to open a new thread, if you see another issue.
Thanks,  
Saba
