### ISSUE TITLE
Error when using the importer under Joomla 3 with PHP 8.0

### ISSUE THREAD

**Issue by Grag1** [Octopoos/SEBLOD#664]
Hello,

thanks for fixing the many PHP 8 issues the other day.

But unfortunately the importer plugin seems to be affected as well.

I get the following error message:

0 Non-static method plgCCK_Storage_LocationJoomla_Article::_initTable() cannot be called statically. 

There are no issues with PHP 7.4.

Thank you very much.

Best regards.

**Comment by rpoy** [comment]
HI!
I am also able to duplicate this same issue.  I am running Joomla 3.10.11 and SEBLOD 3.23.1.

thanks

**Comment by sebastienheraud** [comment]
Hi All,
Thanks, this should be fixed in upcoming packages (tomorrow)
Saba
