### ISSUE TITLE
issue on saving article php 8.1.x

### ISSUE THREAD

**Issue by raramuridesign** [Octopoos/SEBLOD#665]
@sebastienheraud 
There is an error we are getting on save

php: 8.1.x
Joomla: 3.10.11

```
0 count(): Argument #1 ($value) must be of type Countable|array, null given
```

Do you have any idea what this is about?

If you could provide a reply as soon as possible as this is preventing adding content to a site.
Thanks
Matthew

**Comment by raramuridesign** [comment]
@sebastienheraud @sebastienlapoux 
Please note this error also occurs on PHP 8.0.x

M

**Comment by sebastienheraud** [comment]
Hi @raramuridesign,

Please enable the debug and provide the full stack trace.
The above is not enough to easily/quickly answer.

Saba

**Comment by raramuridesign** [comment]
@sebastienheraud I cannot seem to get a stack trace in the backend - the backend then stops working and shows a blank page.
Any ideas?

**Comment by raramuridesign** [comment]
@sebastienheraud @sebastienlapoux 
It seems this has to with the tags from Joomla - ie the inbuilt tags.
Any idea what we can do to sort this out?
M

**Comment by raramuridesign** [comment]
@sebastienheraud Here is the debug info, which is finally showing, seems admin cached hid this.

`<html>
<body>
<h1 class="page-header" style="margin: 2px 0px 10px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 28px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 26px; padding-bottom: 5px; border-bottom: 1px solid rgb(238, 238, 238); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An error has occurred.</h1><blockquote style="padding: 0px 0px 0px 15px; margin: 0px 0px 18px; border-left: 5px solid rgb(238, 238, 238); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="label label-inverse" style="display: inline-block; padding: 2px 4px; font-size: 10.998px; font-weight: bold; line-height: 14px; color: rgb(255, 255, 255); vertical-align: baseline; white-space: nowrap; text-shadow: none; background-color: rgb(51, 51, 51); border-radius: 3px;">0</span><span> </span>count(): Argument #1 ($value) must be of type Countable|array, null given<br>/usr/www/users/agoa/plugins/cck_field_validation/tags/tags.php:56</blockquote><div style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/cck_field_validation/tags/tags.php:56
2 | plgCCK_Field_ValidationTags::onCCK_Field_ValidationPrepareStore() | JROOT/libraries/cms/cck/cck.php:32
3 | JCck::callFunc_Array() | JROOT/libraries/cms/cck/plugin/field.php:1065
4 | JCckPluginField->g_onCCK_FieldPrepareStore_Validation() | JROOT/plugins/cck_field/jform_tag/jform_tag.php:306
5 | plgCCK_FieldJform_Tag->onCCK_FieldPrepareStore() | JROOT/libraries/joomla/event/event.php:70
6 | JEvent->update() | JROOT/libraries/joomla/event/dispatcher.php:160
7 | JEventDispatcher->trigger() | JROOT/libraries/src/Application/BaseApplication.php:108
8 | Joomla\CMS\Application\BaseApplication->triggerEvent() | JROOT/libraries/cck/base/form/store_inc.php:226
9 | include_once() | JROOT/administrator/components/com_cck/models/form.php:22
10 | CCKModelForm->store() | JROOT/administrator/components/com_cck/controllers/form.php:52
11 | CCKControllerForm->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:702
12 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_cck/cck.php:31
13 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:402
14 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:377
15 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
16 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
17 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:225
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:51

</div>
</body>
</html>`

**Comment by raramuridesign** [comment]
I need a fix, as this is causing editing issues on a site.
Thanks.

**Comment by raramuridesign** [comment]
@sebastienheraud I have disabled validation on the 2 fields 
Internal joomla tags
Seblod Tags field
This seemed to have caused the issue
Would you mind investigating this?

**Comment by sebastienheraud** [comment]
Hi,
This may be an old plug-in, but it is not part of the current SEBLOD core, nor SEBLOD Store.
Feel free to add an `is_array( ... )` check before or around the `count( ... )` which may trigger the error when no tag attached.
Closing this one.
Saba
