### ISSUE TITLE
Seblod Options - Integrations - don't save any settings & Deprecated (php 8.1)

### ISSUE THREAD

**Issue by step-di** [Octopoos/SEBLOD#666]
Seblod Options - Integrations - don't save any settings after click button Save

and lot of Deprecated (php 8.1)

Deprecated : Optional parameter $inherit declared before required parameter $user is implicitly treated as a required parameter in 
/plugins/cck_storage_location/joomla_menu_item/joomla_menu_item.php on line 164

Deprecated : strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in
/plugins/system/cck/cck.php on line 146

Deprecated : trim(): Passing null to parameter #1 ($string) of type string is deprecated in
/plugins/cck_field/button_submit/button_submit.php on line 171

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /administrator/components/com_cck/views/type/view.raw.php on line 228

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /administrator/components/com_cck/views/type/view.raw.php on line 230

Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /components/com_cck/views/form/view.html.php on line 57

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /components/com_cck/views/form/view.html.php on line 93

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in 
/libraries/cck/base/form/form_inc.php on line 189

Deprecated: Optional parameter $name declared before required parameter $config is implicitly treated as a required parameter in /plugins/cck_field/upload_jquery/upload_jquery.php on line 608

**Comment by joomleb** [comment]
Hi guys, 
+1 on PHP 8.1.13 I'm having back this deprecated message too:

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in/home/…/plugins/system/cck/**cck.php** on **line146**

**Comment by sebastienheraud** [comment]
Hi,
Thanks. Most warning have been fixed in upcoming package.
Will check asap for integration
Saba

**Comment by sebastienheraud** [comment]
Hi,
Fixed in upcoming package.
Saba
