### ISSUE TITLE
Add "rel" attribute to Link plugin

### ISSUE THREAD

**Issue by jwiesel** [Octopoos/SEBLOD#67]
Dear Seblod-team,
I just saw a nice opportunity to improve the "Link" Field-Plugin. A new option to add a "rel" attribute would be nice. I use the Link-Plugin especially for outgoing links. it would be nice to be able to set rel="nofollow" to avoid losing too much link-juice and therefore to improve SEO.
Best Regards

**Comment by sebastienheraud** [comment]
Hi,
Thanks for the request.
This will be available in upcoming SEBLOD 3.8.0
You can find it here: https://github.com/Octopoos/SEBLOD/commit/ff87c8b7b753c940b98b54c257eb5e3de750b82c
Regards,
Saba.
