### ISSUE TITLE
FAILED OPENING REQUIRED '/ADMINISTRATOR/COMPONENTS/COM_USERS/HELPERS/HTML/USERS.PHP' (INCLUDE_PATH='.:')

### ISSUE THREAD

**Issue by shellok** [Octopoos/SEBLOD#670]
Joomla 4.2.5 Версия 4.0.1 Release.Preview.7 when trying to open joomla manager from the front

**Comment by shellok** [comment]
but I don't see this address, in which file there is a link to this address May be correct /ADMINISTRATOR/COMPONENTS/COM_USERS/HELPERS/USERS.PHP
??

**Comment by shellok** [comment]
This will help fix 500 error&

**Comment by sebastienheraud** [comment]
Hi @shellok,
Thank you for reporting.
This is fixed in upcoming rp8 https://github.com/Octopoos/SEBLOD/commit/8424096cbce8240138c39b6cb9ae691930054869
Saba
