### ISSUE TITLE
Deprecated After installation error inline 600 Document.php

### ISSUE THREAD

**Issue by shellok** [Octopoos/SEBLOD#671]
Deprecated After installation: Automatic conversion of false to array deprecated in /var/www/u0250078/data/www/medical.insky.by/libraries/src/Document/Document.php on line 600

**Comment by EWG65** [comment]
Yes, this error appears on PHP 8.1. On PHP 8.0.22 I do not have it.

**Comment by joomleb** [comment]
+1 on PHP 8.1.13 - I add an image for you
![Seblod-Quick-Icons-deprecated](https://user-images.githubusercontent.com/14607633/206785019-6b4aa8b4-e734-4b4f-be48-bd36e1a42e12.jpg)

**Comment by sebastienheraud** [comment]
Hi,
Thanks for reporting.
A few of those (for PHP 8.1) are fixed with https://github.com/Octopoos/SEBLOD/commit/74410b747fa7280ad4c32a4b5e93c13382eecd36, and this will be included in upcoming rp8 (today).
Saba
