### ISSUE TITLE
Cache settings from List and Search Types is throwing an error

### ISSUE THREAD

**Issue by uGE70** [Octopoos/SEBLOD#672]
Platform :
Joomla 4.2.5, Seblod Version 4.0.1 Release.Preview.7, PHP 8.0.8 +, Joomla cache on or off, no SEO plugin

Steps to reproduce
Go to List and Search Types and click on Article or any Article based content types
Click on configuration
Set Cache (on Search) or Cache (on Render) to On (any type)

Actual result
The following error is displayed on frontend (Search results):
call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Joomla\CMS\Cache\Cache does not have a method "call"
from file:
JROOT/libraries/cck/base/list/list.php:206

Thanks for your work

**Comment by sebastienheraud** [comment]
Hi @uGE70,
Thank you for reporting. This should be fixed with the upcoming rp8.
Feel free to have a try, and please re-open if needed.
Thanks,
Saba
