### ISSUE TITLE
JText does not work

### ISSUE THREAD

**Issue by EWG65** [Octopoos/SEBLOD#673]
Hello!
Platform :
Joomla 4.2.5, Seblod Version 4.0.1 Release.Preview.7, PHP 8.0.22,
If the Frontend language is set to not English and not French, then JText does not work with any language settings (YES/NO/Yes, but english).
![Screenshot](https://user-images.githubusercontent.com/67538006/203851047-66439bb8-5281-472c-993c-6b52fefbdf34.PNG)
In addition, JText stops working for other third-party Joomla components.
![Screenshot-1](https://user-images.githubusercontent.com/67538006/203861367-158d827e-5160-4646-8464-c4c5bb6c9946.PNG)

**Comment by sebastienheraud** [comment]
Hi @EWG65,
This is fixed with SEBLOD 4.0.4
Saba
