### ISSUE TITLE
SEBLOD - Quick Add module makes the system inoperable

### ISSUE THREAD

**Issue by EWG65** [Octopoos/SEBLOD#674]
Platform :
Joomla 4.2.5, Seblod Version 4.0.1 Release.Preview.7, PHP 8.0.22,
The SEBLOD - Quick Add module makes the system inoperable if it is published in any position.
![Screenshot-2](https://user-images.githubusercontent.com/67538006/203862389-d6f9d75c-dea6-4598-8c9c-628ed7ff0f76.PNG)

**Comment by sebastienheraud** [comment]
Hi @EWG65,

Quick add is deprecated and removed from SEBLOD 4

Sebastien
