### ISSUE TITLE
Application Download Broken on Joomla 3/4

### ISSUE THREAD

**Issue by karlawill** [Octopoos/SEBLOD#678]
Application download is broken on Joomla 4 using preview 7 and all PHP versions including 7.4, 8.0 and 8.1. Clicking the 'Down this app' results in the following error.

An error has occurred.
0 htmlspecialchars(): Argument #1 ($string) must be of type string, Joomla\CMS\Helper\TagsHelper given

Also appears to be broken on Joomla 3.10.11 using PHP 8.0 and 8.1. 

Application download is critical to usage. Any assistance in getting this working again would be greatly appreciated.

**Comment by sebastienheraud** [comment]
Hi @karlawill,
Thanks for reporting the issue.
This https://github.com/Octopoos/SEBLOD/commit/f8fe270e075ff07e11053e4ebb7a35943671001e should fix it.
Feel free to have a try with upcoming packages: SEBLOD 4 rp8 and/or SEBLOD 3.22.2
Please re-open if needed.
Thank you.
Saba
