### ISSUE TITLE
On PHP 8.0 with Bridge enabled error occured when creating a new user or when saving an existing one

### ISSUE THREAD

**Issue by kureshtar** [Octopoos/SEBLOD#680]
Hello.
Seblod v 3.23.1
Joomla v 3.10.11
php v 8.0.22

On php 8.0 with Bridge enabled when creating a new user or when saving an existing one the following error appears:
Non-static method JCckPluginLocation::g_doBridge() cannot be called statically

The following entry appears in the log file:
PHP Warning: Undefined array key "block" in \plugins\cck_storage_location\joomla_user\joomla_user.php on line 403

With the bridge disabled, the error does not occur on php 8.0.

**Comment by Ilya-Zhulin** [comment]
Hi. Can you create a new user with this congiguration?

**Comment by kureshtar** [comment]
New users are also not created.

**Comment by kureshtar** [comment]
Enabled Bridge

**Comment by sebastienheraud** [comment]
Hi All,
Thanks, this is fixed in upcoming package (tomorrow).
Saba
