### ISSUE TITLE
J4 - Upgrade Seblod 3 > 4 Crash 

### ISSUE THREAD

**Issue by joomleb** [Octopoos/SEBLOD#684]
Hi guys, 
during upgrading I had back some crashes (really during looking into Users after Seblod upgrade) like:

**0 Class 'JCckToolbox' not found**

**Call stack**
1 | () | JROOT/plugins/user/cck/cck.php:90
2 | plgUserCCK->onUserLogin() | JROOT/libraries/src/Plugin/CMSPlugin.php:279
3 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
4 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:107
5 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/libraries/src/Application/CMSApplication.php:860
6 | Joomla\CMS\Application\CMSApplication->login() | JROOT/libraries/src/Application/AdministratorApplication.php:337
7 | Joomla\CMS\Application\AdministratorApplication->login() | JROOT/administrator/components/com_login/src/Controller/DisplayController.php:82
8 | Joomla\Component\Login\Administrator\Controller\DisplayController->login() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
10 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/administrator/components/com_login/src/Dispatcher/Dispatcher.php:45
11 | Joomla\Component\Login\Administrator\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
16 | require_once() | JROOT/administrator/index.php:32

Before to going on I want be sure I made all in the right way and I want to replicate the crash isolating the issue giving back to you more datas as possible. So:

PHP 7.4.33 + Joomla 3.10.11 + Seblod 3.23.1

As you [described here](https://www.seblod.com/community/blog/seblod-4-0-series-3) I upgraded Seblod to 4.0.1  p7 and then I upgraded Joomla to 4.2.6.

Then, on J4, I reinstalled the Seblod 4.0.1 p7. When finished I have to choose the option:
- A - to update Seblod to General > SQL Mode Legacy
- B - or to Review Database Tables

Being that I was testing on a site with just one old User created through the Seblod bridge (now disabled), I choose to click on B and I had back this "anonymous" page:

![Seblod4-J4-DB](https://user-images.githubusercontent.com/14607633/210440254-10e85ac2-210d-4ef2-a35a-efa1e7d8d0a0.jpg)

SQL Tables:
- f5n2z_cck_store_item_categories
- f5n2z_cck_store_item_content
- f5n2z_cck_store_item_users

SQL Queries:
ALTER TABLE `f5n2z_cck_store_item_categories` ALTER `cck` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_content` ALTER `cck` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `cck` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `gender` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `last_name` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `first_name` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` MODIFY `about_me` text;
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `avatar` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` MODIFY `address1` text;
ALTER TABLE `f5n2z_cck_store_item_users` MODIFY `address2` text;
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `city` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `postal_code` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `region` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `country` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `phone` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `website` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` MODIFY `birthdate` datetime;
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `birthplace` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `company` SET DEFAULT "";
ALTER TABLE `f5n2z_cck_store_item_users` ALTER `company_vat_id` SET DEFAULT "";

Now, before to going on, I have a small / big question:
- That page is showing me what Seblod run OR what I have to do ?
- Is it a "success" message OR an "error" message ?

In case we have to do something through phpMyAdmin, Please, Can you give us detailed instructions ?

**Comment by joomleb** [comment]
Hi guys, 
I suppose that SEBLOD 4.0.3:

STRICT_TRANS_TABLES solution (2/2) implemented.
  >> no one-click update, but all SQL queries listed (to copy/paste and run on PhpMyAdmin, if needed)

is the answer to my previous question...

**Comment by sebastienheraud** [comment]
Hi @joomleb,
> is the answer to my previous question...

Yes
Saba
