### ISSUE TITLE
Warning in cck_field_typo

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#686]
With the latest RC7 I have the following warning: 
Warning: Undefined property: stdClass::$image_alt in ..../plugins/cck_field_typo/image/image.php on line 125

**Comment by sebastienheraud** [comment]
Hi Elisa,
Not sure which field is used here, but this one https://github.com/Octopoos/SEBLOD/commit/790e7edde5610a07ab87da320fbd843f7879ba58 should fix the notice.
Thanks,
Saba
