### ISSUE TITLE
MultiLanguage

### ISSUE THREAD

**Issue by MiniHief** [Octopoos/SEBLOD#689]
Hello Seblod.
Fresh Joomla4 and Seblod4 v7.
Installed: 3 test languages

Is this an error in the MultiLanguage configuration?
Field tab - Language selection and song end.
And other options with language selection.

**500 Unknown column 'a.language' in 'where clause' Unknown column 'a.language' in 'where clause'**

What to do?
Will there be a fix? wait for updates or can i fix it myself?
Step by step.
Thanks.

**Comment by sebastienheraud** [comment]
Hi @MiniHief,

Thank you for reporting.
Indeed this part was not complete in rp7, but it will be fixed in upcoming rp8 (today or tomorrow).

Saba
