### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1

### ISSUE THREAD

**Issue by salahjaafar** [Octopoos/SEBLOD#690]
Error 
![Screenshot 2023-02-02 at 09-28-15 Ajouter une fiche Type de contenu](https://user-images.githubusercontent.com/47123877/216271678-11881861-354d-4685-8d1c-fcd2612a3401.png)

**Comment by sebastienheraud** [comment]
Hi @salahjaafar,

Please upgrade with the upcoming rp8 (today or tomorrow) and let us know if this is not fixed afterwards.
Feel free to re-open if needed.

Saba
