### ISSUE TITLE
Code Pack v1.7 broken in back-end on PHP 8.1 Joomla 3

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#692]
I just updated Code Pack from 1.6 to 1.7 on Joomla 3.10 and PHP 8.1 and the update breaks the plugin in the backend (opening the field throws an error), I needed to rollback to 1.6

**Comment by sebastienheraud** [comment]
Hi @Giuse69,
1.7 should work well, but the Updater may have downloaded the 1.8 (even if it was showing 1.7 available)

Feel free to download/update manually:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1101317/222110541-90672bc2-ce76-4085-b596-c3682c128ed8.png">

We'll see if we can find a way to have the specific/right download URL.
As this is a known issue with the updater, I'm closing this one.
Saba
