### ISSUE TITLE
Warning: Undefined array key "permissions"

### ISSUE THREAD

**Issue by lionated88** [Octopoos/SEBLOD#696]
In the app folder settings -> permission tab

Warning: Undefined array key "permissions" in /var/www/vhosts/...administrator/components/com_cck/views/folder/tmpl/edit.php on line 55

**Comment by sebastienheraud** [comment]
Hi @lionated88,
Thanks.
Fixed here: https://github.com/Octopoos/SEBLOD/pull/710 and included in upcoming package.
Saba
