### ISSUE TITLE
category Associations fields can't be displayed

### ISSUE THREAD

**Issue by KillianCoulange** [Octopoos/SEBLOD#700]
In the file plugins/cck_storage_location/joomla_category/joomla_category.php line 674
call to a file which don't exist.

So the class_exists($name) return false;
and plgCCK_Storage_LocationJoomla_Category_Helper::getAssociationsForm return ''; that can't display fields.

**Comment by sebastienheraud** [comment]
Hi @KillianCoulange,
Thank you. Fixed in upcoming packages (tomorrow)
Saba
