### ISSUE TITLE
Error at Seblod installation on Joomla 4

### ISSUE THREAD

**Issue by jppjpp** [Octopoos/SEBLOD#701]
Hi
I try to install Seblod on a joomla 4 (4.28) php 8.0.28 migrated from j.3.10

With 3.23.3 version I have this error message
JInstaller: :Install: erreur SQL Incorrect integer value: '' for column 'storage_mode' at row 146

With  4.0.2.Release.Preview.8 version I have this error message
Unknown column 'language' in 'field list'
If I install on new joomla 4 site installed from scratch. Installation is OK 

Even with error report set to maximum I have no additional information 
At the moment I have no Seblod application and I would prefer to start with version 4 

As additional information, when I install on new joomla 4 site built from scratch, there is no issue.
Thank you for your help

**Comment by sebastienheraud** [comment]
Hi @jppjpp,
There was a regression in the upgrade process, this should be fixed now.
If not feel free to re-open and share all details/steps to replicate (install, upgrades).
Thanks,
Saba
