### ISSUE TITLE
Conditional States Display problem

### ISSUE THREAD

**Issue by salahjaafar** [Octopoos/SEBLOD#705]
Display problem when selecting Conditional States options
I am using joomla 4.2.9 & Seblod 4.0.2 Release.Preview.8

![Screenshot 2023-03-16 at 12-04-31 Ajouter un patient Content Type](https://user-images.githubusercontent.com/47123877/225598500-8cff8e19-46eb-4d88-8435-d7af944f1c18.png)

**Comment by sebastienheraud** [comment]
Hi @salahjaafar,
This will be improved/fixed in upcoming package.
Thanks,
Saba
