### ISSUE TITLE
Search Total 1.5.0 fails to install

### ISSUE THREAD

**Issue by Giuse69** [Octopoos/SEBLOD#719]
Tried to install Search Total 1.5.0 on Seblod 4.0.5 on Joomla 4.3, PHP 8.1 and it fails with
"Unknown column 'params' in 'field list'"
cheers

Giuse

**Comment by sebastienheraud** [comment]
Hi @Giuse69,

OK we were able to replicate the upgrade issue, and the thing is the following:
The SEBLOD 4 package (depending on which one and when you try to update) may not be aware of the SEBLOD 3 release... it's trying to update. And it that case the SQL queries update fails.
ex:
* SEBLOD 3.24 can be upgraded with SEBLOD 4.0.5 without any issue
* SEBLOD 3.25 is released and trying to update an existing 3.25 site with SEBLOD 4.0.5 will fail.
* the existing 3.25 site will require the 4.0.6 package so the upgrade is completed properly

So we need to release a new 4.x package after each 3.x package, and you (when upgrading a 3.x site) need to make sure you have the latest 4.x available (if it was updated to the latest SEBLOD 3.x)

On a site where the upgrade failed the 1st time, you just need to manually run ALL queries found in /administrator/components/com_cck/install/upgrades/4.x.x.sql (each 4.x.x file) via PhpMyAdmin to have the SQL schema up-to-date.

Saba

**Comment by Giuse69** [comment]
Thanks @sebastienheraud , infact I found many differences in the DB between a v3 => v4 upgraded site and a brand new v4 site, now it's clear. Also I deleted all ‘com_cck.folder.<n>’ rows from '#__assets' since I see that Seblod v4 no more stores cck folders as joomla assets
