### ISSUE TITLE
Problems when trying to delete any menu item

### ISSUE THREAD

**Issue by EWG65** [Octopoos/SEBLOD#721]
Joomla 4.3.1
Seblod 4.0.5
PHP 8.1.9
When trying to remove any menu items from the trash, it gives an error.
`0 Failed opening required '/plugins/cck_storage_location/joomla_menu_item/joomla_menu_item.php' (include_path='.')`
On the same version of Joomla without Seblod, this works without errors.
![Снимок1](https://github.com/Octopoos/SEBLOD/assets/67538006/86c884dd-9c59-480a-ac1a-00052d1bec43)

**Comment by sebastienheraud** [comment]
Hi @EWG65,
Thanks for reporting.
Fixed with https://github.com/Octopoos/SEBLOD/commit/0a2f108706a1da9861e465b391269e6e4d44645d included in upcoming SEBLOD 4.1 release.
Saba

**Comment by hammerteni** [comment]
Joomla 5.2.2
Seblod 4.5.1
PHP 8.2.4
The same problem.
When trying to remove any menu items from the trash, it gives an error.
0 Failed opening required '/plugins/cck_storage_location/joomla_menu_item/joomla_menu_item.php'
