### ISSUE TITLE
SEBLOD: Can't add field into list and search item

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#732]
When trying to add a field in list and search item it does not save it. 
Max input Vars is set to 10000

**Comment by coolcat-creations** [comment]
Happens in Joomla 4 with Seblod 4.0.5

**Comment by olivier-nolbert** [comment]
Hi Elisa,

Problem still here with SEBLOD 4.0.6 ?

Thx

**Comment by coolcat-creations** [comment]
Hi Olivier, no its solved, thank you!
