### ISSUE TITLE
seblod.com site redirecting new member signups to 404 

### ISSUE THREAD

**Issue by M4dKiwi** [Octopoos/SEBLOD#733]
Hi there 
I am currently trying out Sebold Core - extension for Joomla 4 
However in wanting to try out & download plugins from the Sebold site 
but users are required to log in or sign up ..... but I keep getting redirected to a 404 error page
after ( attempting confirmation (new user) ) registration form submission,
which is a shame ... hopefully this will be a quick fix so that I can sign up :) 
Thanks for reading :+1:

**Comment by sebastienheraud** [comment]
Hi,
We just tried the registration workflow, and were able to register and confirm via the link without any issue.
Feel free to contact us from the contact page on SEBLOD.com, by sharing the username/email of your account, and we will have a look at your account.
Thanks,
Saba
