### ISSUE TITLE
"Seblod Version 4.0.5 and Joomla 4.3.2: Content Addition Issue and SQL Mode Activation"

### ISSUE THREAD

**Issue by salahjaafar** [Octopoos/SEBLOD#735]
Dear GitHub Seblod team,
I would like to report an issue I am facing with content creation using Seblod Version 4.0.5 and Joomla 4.3.2. Although the content creation message indicates success, the data is not being saved properly.
Upon further investigation, I have found that the data gets saved correctly after enabling the SQL Mode: Legacy (Joomla! 3) setting.
I would greatly appreciate your assistance in resolving this issue and finding a solution that allows data to be saved without having to enable the SQL Mode: Legacy. Please keep me updated on any progress made in resolving this issue.
Thank you very much for your attention and support.
Best regards,
Salah JAAFAR

**Comment by sebastienheraud** [comment]
Hi Salah,
No issue with the core package here, feel free to use the forum.
You'll find also additional info on the blog post (when we spoke about upgrading an existing site - could be applied for installing an old app as well). You need to look at the structure of your table, and apply some default value / change null|not null info.
Or just use the legacy mode, if it's too complex/long to change the structure of your existing table.
Saba
