### ISSUE TITLE
Call to undefined method CCKController::setError() 

### ISSUE THREAD

**Issue by denysdesign** [Octopoos/SEBLOD#740]
Hi!

Find this error for SEBLOD 4.

`0 Call to undefined method CCKController::setError() `

| # | Function | Location |
| -------- | ------- | ------- |
| 1 | () | JROOT/administrator/components/com_cck/controller.php:311 |
| 2 | CCKController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:678 |
| 3 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_cck/cck.php:34 |
| 4 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71 |
| 5 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73 |
| 6 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361 |
| 7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143 |
| 8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186 |
| 9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293 |
| 10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61 |
| 11 | require_once() | JROOT/administrator/index.php:32|

**Comment by sebastienheraud** [comment]
Hi @denysdesign,
Fixed in upcoming SEBLOD 4.1 release.
Saba
