### ISSUE TITLE
Save failed with the following error: BLOB, TEXT, GEOMETRY or JSON column 'fulldescription' can't have a default value

### ISSUE THREAD

**Issue by poguanzi** [Octopoos/SEBLOD#743]
Joomla 4.3.3 / Seblod 4.06

**System Information**

**php:** Windows 10 build 19044 (Windows 10) AMD64
**dbserver:** mysql
**dbversion:** 8.0.31
**dbcollation:** utf8mb4_0900_ai_ci
**dbconnectioncollation:** utf8mb4_0900_ai_ci
**dbconnectionencryption:** 
**dbconnencryptsupported:** true
**phpversion:** 8.0.26
**server:** Apache/2.4.54 (Win64) PHP/8.0.26 mod_fcgid/2.3.10-dev
**sapi_name:** apache2handler
**version:** Joomla! 4.3.3 Stable [ Bora ] 11-July-2023 16:00 GMT
**useragent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

Error:
`Save failed with the following error: BLOB, TEXT, GEOMETRY or JSON column 'fulldescription' can't have a default value`

I want to create a new field which is the type of Wysiwyg Editor, but I got the above error after saving.

![image](https://github.com/Octopoos/SEBLOD/assets/22453534/79206333-6c6d-4b7a-8826-4b5a677baff5)

**Comment by Ilya-Zhulin** [comment]
> Starting from MySQL 8.0.13, it is now possible to have a default value for TEXT/BLOB field.
Has anybody solved this problem?

**Comment by sebastienheraud** [comment]
Hi,
We'll have a look. But did you also try to change the mode:

<img width="895" alt="image" src="https://github.com/user-attachments/assets/973482f0-187a-456b-93fb-87f5da2e4ab8">

Saba

**Comment by Ilya-Zhulin** [comment]
> Hi, We'll have a look. But did you also try to change the mode:
> 
> <img alt="image" width="895" src="https://private-user-images.githubusercontent.com/1101317/359067553-973482f0-187a-456b-93fb-87f5da2e4ab8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDc1MzksIm5iZiI6MTcyNDE0NzIzOSwicGF0aCI6Ii8xMTAxMzE3LzM1OTA2NzU1My05NzM0ODJmMC0xODdhLTQ1NmItOTNmYi04N2Y1ZGEyZTRhYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDk0NzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU3OTI2YjZkZDA5OGU5ZTllODIyMmVmNjU4NTA2NWQzODhjODJkMWM2NWU2ODAyM2RhNmYxYWMxY2E3MjVjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RSgLQnFH2ZZPFOccrQvyXBHV5ftwV7j-yAFmedTDHuc">
> Saba

Thanks, Saba. It has helped. Didn't see this option earlier. 
_Sorry for offtop, but didn't you know, will new version be and when?_

**Comment by sebastienheraud** [comment]
Hi,

Glad it helped.

> Sorry for offtop, but didn't you know, will new version be and when?

New versions yes, a small one (at least for J3.x) in August, and a bigger one (J5.x) in September

Saba

**Comment by sebastienheraud** [comment]
> Joomla 4.3.3 / Seblod 4.06
> 
> **System Information**
> 
> **php:** Windows 10 build 19044 (Windows 10) AMD64 **dbserver:** mysql **dbversion:** 8.0.31 **dbcollation:** utf8mb4_0900_ai_ci **dbconnectioncollation:** utf8mb4_0900_ai_ci **dbconnectionencryption:** **dbconnencryptsupported:** true **phpversion:** 8.0.26 **server:** Apache/2.4.54 (Win64) PHP/8.0.26 mod_fcgid/2.3.10-dev **sapi_name:** apache2handler **version:** Joomla! 4.3.3 Stable [ Bora ] 11-July-2023 16:00 GMT **useragent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
> 
> Error: `Save failed with the following error: BLOB, TEXT, GEOMETRY or JSON column 'fulldescription' can't have a default value`
> 
> I want to create a new field which is the type of Wysiwyg Editor, but I got the above error after saving.
> 
> ![image](https://private-user-images.githubusercontent.com/22453534/252917233-79206333-6c6d-4b7a-8826-4b5a677baff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTUxMzksIm5iZiI6MTcyNDc1NDgzOSwicGF0aCI6Ii8yMjQ1MzUzNC8yNTI5MTcyMzMtNzkyMDYzMzMtNmM2ZC00YjdhLTg4MjYtNGI1YTY3N2JhZmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEwMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYzBmNTM4NTM5YjFmMDY0YjUxNWVhZWNjMjJlOTdhOWNlNTI3MmM2ZGVjYTUxZTI5N2E0YzlkYjM0ZTYyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jXF2GngJ1ObYnJ7mFPKUrt_5qb_Z8xxkvtPcIcqzyvE)

Hi,

This is fixed in upcoming 4.4.0 package.

Thanks,
Saba
