### ISSUE TITLE
Seblod 4.0.6 - Category List shows nothing because of SEBLOD System Plugin

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#750]
In the file: plugins/system/cck/cck.php

there is a line 
				$app->setUserState( 'com_content.category.list.'.(int)$id.':'.(int)$itemId.'.limit', -1 );

Which causes category lists to have no output at all.

				Line 195: $app->setUserState( 'com_content.category.list.'.(int)$id.':'.(int)$itemId.'.limit', -1 );

Why is this line there?

**Comment by sebastienheraud** [comment]
Hi @coolcat-creations,
Thanks for reporting. One condition https://github.com/Octopoos/SEBLOD/commit/cc1ae5b4cc78f937465e71bf334c4118c20d4c0f added in upcoming SEBLOD 4.1 release, so you should be fine.
Saba
