### ISSUE TITLE
SEBLOD User Bridge

### ISSUE THREAD

**Issue by lionated88** [Octopoos/SEBLOD#758]
On Joomla  4.3.4 with Seblod 4.1 in the joomla user location plugin the article bridge enabled doesn't create any article object after user creation. 

> The settigns help line says:
> - With Bridge:
> Same features as "Without Bridge" + the following..
> Each time a User is created, an Article will also be added automatically.. and both will be linked. The Article will bring a Content View for User's page/profile, will allow the Route, and will give "natively" much more control over the Lists.. (access, hits, publish_up, publish_down, ..)
> You can define some values and how the title is going to be generated.. below.

I tried in on a new installaton aswell, becausue on the site I'm working on I already did a lot of customizations and I though there might be an issue because of that, but it doesn't work on a new installation either.

Thanks

**Comment by joomleb** [comment]
Hi,
@sebastienheraud  maybe something connected with #683 ?!?

**Comment by Giuse69** [comment]
I have the same problem with no article created with a new user

**Comment by olivier-nolbert** [comment]
Hi everyone,

PR : https://github.com/Octopoos/SEBLOD/pull/775 to fix the aticle bridge creation issue.

Have a good day

**Comment by kimbare** [comment]
The only way I can add new users is to go back to PHP 8.0.  When will this problem be fixed?
