### ISSUE TITLE
SELECT CONCAT does not work in dynamic field

### ISSUE THREAD

**Issue by helgator** [Octopoos/SEBLOD#79]
Using CONCAT in the free SQL query makes SEBLOD inserting a usless div into the link markup and wiping out the content so the page source looks like 

```
<a href<="" div=""></a>
```

despite the sql says:

```
SELECT CONCAT('<a href=\"/index.php?Itemid=496&option=com_comprofiler&task=userprofile&user=',#__comprofiler.user_id,'\" taget=_blank>',#__comprofiler.lastname,', ', #__comprofiler.firstname,'</a>') AS text, ...
```

No setup in the form or field can prevent that from happening.

**Comment by klas** [comment]
Wheare are trying to use this? Seblod does not fitler out any sql, but it might filter some incorrect markup.

**Comment by klas** [comment]
To be closed
