### ISSUE TITLE
SEBLOD users cannot be managed from the backend

### ISSUE THREAD

**Issue by kimbare** [Octopoos/SEBLOD#799]
When I add a user from the backend, none of the information I add is saved.  I add a first name, a last name, etc. and when I hit save, all the information goes away.  The user number stays, but all other information disappears.  I am using the user form supplied by SEBLOD.

I have SEBLOD 4.3.0, joomla 4.4.1 and php 8.1

**Comment by sebastienheraud** [comment]
Closing this one, not related to SEBLOD core package.

**Comment by kimbare** [comment]
Hello All,

I am very confused, I do not understand how this is not related to SEBLOD.  It only happens when we try to add users on the backend using the SEBLOD user forms we created that work on the front.  So how is this not related to SEBLOD?

Thanks,

Kim

________________________________

**Comment by kimbare** [comment]
Hello Everyone,

Ursula asked me to be very clear about the fact that we can create users in the backend using the normal Joomla user.  However, as you are aware, we have a form for contributors we are using that was created with SEBLOD.  We can add users in the front of the site using that SEBLOD form, but we cannot create users on the backend using that form.  So I am very confused how this is not a SEBLOD issue.

Thanks,

Kim

________________________________
