### ISSUE TITLE
Module SEBLOD list and Joomla 4

### ISSUE THREAD

**Issue by webmasterpaca** [Octopoos/SEBLOD#804]
Hi,

I use the Seblod List Module to display lists with Seblod 4.3.1 and Joomla 4.3.1, PHP 8.2 and Mysql 5.7.42

Unfortunately, on pages where the module is displayed, I get a 500 error when I want to edit the page. 
_Sorry, there was a problem we could not recover from.
The server returned a "500 - Whoops, looks like something went wrong."_
By deactivating the Seblod List module the error disappears. 

Seblod List module it's compatible with Joomla 4 ? 

Thanks for your help !

**Comment by webmasterpaca** [comment]
Hi,
This is the “Forthcoming training” module on this page: https://paca.lpo.fr/formation
I use the Seblod List module to display a classic search list
I get the following error when editing the page on Cassiopea 
count(): Argument #1 ($value) must be of type Countable|array, null given

SELECT t0.id AS pid,t0.pk AS pk,t0.pkb AS pkb,t0.parent_id AS parent,t0.author_id AS author,t0.author_session AS author_session,t0.cck AS cck,t0.storage_location AS loc,tt.id AS type_id
FROM `#__cck_core` AS t0
LEFT JOIN `#__cck_store_form_formation` AS t1 ON t1.id = t0.pk
LEFT JOIN `#__content` AS t2 ON t2.id = t0.pk
LEFT JOIN `#__cck_core_types` AS tt ON tt.name = t0.cck
WHERE t2.access IN (1,2,3,4,5,6,7,8,9)
  AND ( t2.publish_up IS NULL OR t2.publish_up <= '2024-02-21 13:50' )
  AND ( t2.publish_down IS NULL OR t2.publish_down >= '2024-02-21 13:50' )
  AND t0.storage_location = "joomla_article"
  AND t1.inscriptions_statut LIKE '%ouvertes%'
  AND t2.state LIKE '%1%'
ORDER BY t1.date_debut ASC
LIMIT 25

SELECT COUNT(t0.id)
FROM `#__cck_core` AS t0
LEFT JOIN `#__cck_store_form_formation` AS t1 ON t1.id = t0.pk
LEFT JOIN `#__content` AS t2 ON t2.id = t0.pk
LEFT JOIN `#__cck_core_types` AS tt ON tt.name = t0.cck
WHERE t2.access IN (1,2,3,4,5,6,7,8,9)
  AND ( t2.publish_up IS NULL OR t2.publish_up <= '2024-02-21 13:50' )
  AND ( t2.publish_down IS NULL OR t2.publish_down >= '2024-02-21 13:50' )
  AND t0.storage_location = "joomla_article"
  AND t1.inscriptions_statut LIKE '%ouvertes%'
  AND t2.state LIKE '%1%'

0.007 seconds (0.007); 14.25 MB (0.029) - afterSearch [Cache=OFF] = 34 results.
0.037 seconds (0.030); 14.52 MB (0.272) - afterRender [Cache=OFF

**Comment by sebastienheraud** [comment]
Hi,
Please have a try with the upcoming package (tomorrow), and reopen if needed.
Saba

**Comment by webmasterpaca** [comment]
Hi,
Thanks, I have updated to Seblod 4.4.2, with Joomla 5.1.4
I have created a new module "Seblod list" that consults an existing and functional list.
When I edit a page where the module appears, I get the following error:
Sorry, there was a problem we could not recover from.
The server returned a "500 - Whoops, looks like something went wrong."
I tested with Gantry 5 and Cassiopea templates
With Cassiopea I have this additional error code: 0 count(): Argument #1 ($value) must be of type Countable|array, null given
Thanks for your help
