### ISSUE TITLE
There does not seem to be a way to list articles that are scheduled to be published using article_publish_up

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#81]
Hi there,

There doesn't seem to be a way to list articles using a List & Search Type that have been scheduled for publication at future date using the article_publish_up field. My list successfully shows published, unpublished and trashed items, but not ones that have been schedules for publication in future.

To debug, I have tried to:

- Add the article_publish_up field to the search form
- Set the live value to "today" and "Match" to Future or Equal - in this case ONLY the future scheduled posts appear
- Duplicate the field (same storage), have "future or equal" on one field and "past or equal" on the other field - with live value as "today"

All of the above do not list all articles, including the scheduled ones.

James

**Comment by klas** [comment]
Jsut tested and It works ok with live value 0 and Future or Equal matching.

**Comment by klas** [comment]
Does not exist anymore - live value NOW + future matching works ok.
