### ISSUE TITLE
PHP-error form.php line 221 and line 226 after fresh installing

### ISSUE THREAD

**Issue by Karpfensami** [Octopoos/SEBLOD#811]
Hello,
I have installed Seblod version 4.3.1 on a fresh Joomla 4.4.3 system on a xampp (version 3.3.0, with php 8.1) server.
If I would like add a new field I got any errors at the storage area. 
![error seblod new field](https://github.com/Octopoos/SEBLOD/assets/161637178/7ce08d07-5366-4798-bb93-09d0a4f05ebe)

Has anybody an the same problem?
How can I fix it?

Best regards,
Christoph

**Comment by Ilya-Zhulin** [comment]
Hi, it's a problem with PHP 8+
correct this row with this:
```if (strpos($config['item']->storage_table ?? '', '#__cck_store_form_') !== false) {```

**Comment by Ilya-Zhulin** [comment]
Also you can fix possible problems from these [pulls](https://github.com/Octopoos/SEBLOD/pulls/Ilya-Zhulin)

**Comment by Karpfensami** [comment]
Thank you for the very fast answer.
Line 221 is fixed, the message on line 226 is still open.

**Comment by Ilya-Zhulin** [comment]
As a temporary fix add ’ ?? ''’ after third parameter of function

**Comment by Karpfensami** [comment]
Thank you for your helping!

**Comment by sebastienheraud** [comment]
Hi,

These notices are fixed in upcoming 4.4.0 package.

Thanks,  
Saba
