### ISSUE TITLE
Checkbox Dynamic: $user doesn't work (SQL error)

### ISSUE THREAD

**Issue by pierre-H** [Octopoos/SEBLOD#82]
Hi,
Thank you for Seblod : it's a great tool !
I setup a checkbox dynamic field (v. 1.0.0) which select title and id of usergroups according to an user propriety. So I 'Where' I put : parent_id = $user->  *something*. With **Select dynamic** it's working but not with **Checkbox dynamic** : i've got in the form an SQL error : ``SELECT title AS text, id AS value FROM #__usergroups WHERE parent_id= $user->something`` so it doesn't evaluate the expression $user->something.

The only solution is to use the free method and write the sql line : ``SELECT title AS text, id AS value FROM #__usergroups WHERE parent_id= $user->something``.

Thank you in advance for the fix !

**Comment by pierre-H** [comment]
I discovered that the answer above is an half answer because after I submit something, there is the same sql error.

I found an answer : I compared the code of **Select dynamic** and I found that with adding this line : 
``$query = JCckDevHelper::replaceLive( $query );`` after the line 107 and 314 and this : 
``$opt_query	=	JCckDevHelper::replaceLive( $opt_query );`` after the line 323.

And after that it works perfectly (construction or free).

**Comment by pierre-H** [comment]
So, need a real fix...

**Comment by olivier-at-octopoos** [comment]
Hi Pierre-H,

Fix in validation phase. It won't be available on the market before 1st week of August.

We've tested with latest version of the Checkbox dynamic field (1.1.0) so we don't have the same line numbers. Though, What you've done should fix both free & construction methods.

Olivier

**Comment by sebastienheraud** [comment]
Hi Pierre-H,
Dynamic Checkbox 1.2.0 release is available. It includes your fix.
Thank you.
Saba.
