### ISSUE TITLE
Warning after update to 4.4.

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Octopoos/SEBLOD#822]
![image](https://github.com/user-attachments/assets/3bf4a36d-e27b-4e9d-8ae1-766599cbe84e)

I've added condition `isset($field->language) && ` to this string but I'm not sure that it is correct.
Site is updated from version 3.x

**Comment by salahjaafar** [comment]
Set  Error Reporting to none

![Uploading config.png…]()

**Comment by sebastienheraud** [comment]
Hi,
These warnings are fixed with SEBLOD 4.4.1
Saba
