### ISSUE TITLE
JavaScript validation issue for required fields

### ISSUE THREAD

**Issue by salahjaafar** [Octopoos/SEBLOD#829]
In the currently installed version of Joomla! "5.1.4", with the CCK Seblod extension version 4.4.1, the JavaScript validation for required fields is not functioning correctly. No error message appears when required fields are left empty, preventing users from being notified of missing mandatory information.

**Comment by sebastienheraud** [comment]
Hi,

Regression is fixed, by adding a "position:relative;" on the field markup, included in SEBLOD 4.5.1 :
* https://github.com/Octopoos/SEBLOD/commit/1cafb15c1a8191b9a1d6bfc5dd3d769994d873e2
* https://github.com/Octopoos/SEBLOD/commit/c7543ddaf831346167514cfce95e6fe15833d996

Feel free to adapt on your own field markups/css if needed.
Note : it would be better also to remove the float:left, and make the width:auto ... or even better to apply a display:grid on the parent element with the start alignment... which would make the tooltip properly placed on each field.

Saba
