### ISSUE TITLE
> Hi, Fixed included in SEBLOD 4.4.1 for Joomla! 5.1.4 https://www.seblod.com/changelogs#SEBLOD_441_20240919 Saba

### ISSUE THREAD

**Issue by denysdesign** [Octopoos/SEBLOD#831]
> Hi, Fixed included in SEBLOD 4.4.1 for Joomla! 5.1.4 https://www.seblod.com/changelogs#SEBLOD_441_20240919 Saba

Sorry, but it's not work.

For example:
/directory?catalog_s_cat_id=71&start=20

So, I'm found mistake.

In file: components/com_cck/views/list/tmpl/default_list.php
string 22

replace:
`if ( strpos( $url, '=&' ) !== false ) {`

to:
`if ( strpos( $url, '&' ) !== false ) {`

And, so, work perfectly!!!

_Originally posted by @denysdesign in https://github.com/Octopoos/SEBLOD/issues/823#issuecomment-2364311487_

**Comment by sebastienheraud** [comment]
Hi,
A release is planned for later today, but this condition was already there for the other part of the process so I guess it will stay like that, and the code will be placed elsewhere
Thanks,
Saba

**Comment by sebastienheraud** [comment]
Hi,
In the end no need to duplicate the code, neither to change the condition that way (as it is the same as not having it :)) so it is just removed. 
Feel free to have a try with SEBLOD 4.4.2
Thanks,
Saba
