### ISSUE TITLE
Deprecated message with User create

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Octopoos/SEBLOD#832]
> **Deprecated**: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /sites/lproject/plugins/cck_field/link/link.php on line 132

This message you can see in user create form in Admin panel.

**Comment by sebastienheraud** [comment]
Hi @Ilya-Zhulin,

Notice fixed in SEBLOD 4.5.1 https://github.com/Octopoos/SEBLOD/commit/6373d259cfdfb1f676302f02eb2135369b5a9e24

Thanks,
Saba
