### ISSUE TITLE
Items are not deleted from the cck_store_item_user_notes table for User Notes Object

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#85]
When deleting a user note item created with the User Notes Object, the item is deleted from the #__user_notes table but it is not deleted from #__cck_store_item_user_notes.

**Comment by olivier-at-octopoos** [comment]
Thanks James for the info,

It's fixed and waiting to be released.

Quick fix with this SQL query:

UPDATE `#__cck_core_objects` SET `context` = 'com_users.note' WHERE `name` = 'joomla_user_note';

Olivier

**Comment by sebastienheraud** [comment]
Hey,
This is fixed in upcoming SEBLOD 3.7.1
Thank you!
Saba.
