### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Octopoos/SEBLOD#86]
Issue from forum http://www.seblod.com/community/forums/general-discussions/upgrade-problem
Every time when I upgrade SEBLOD I have an error
```Duplicate column name 'path' SQL=ALTER TABLE xxx_cck_core_folders ADD path VARCHAR( 1024 ) NOT NULL AFTER parent_id;```
I found in plg_conten_cck.zip/csript.php following:
```if ( $i < 23 ) {	// ONLY < 2.4.5
	JCckDatabase::doQuery( 'ALTER TABLE #__cck_core_folders ADD path VARCHAR( 1024 ) NOT NULL AFTER parent_id;' );```
So, now the question is - where is marker which defines my SEBLOD version like < 2.4.5?
I don't remember when it started, but it was 3-4 times exactly. Every update and last update also - from 3.6.2 to 3.7.

**Comment by olivier-at-octopoos** [comment]
Hi,

Can you check and post the result of this SQL query on your website DB ?
```
SELECT manifest_cache FROM #__extensions WHERE element = "com_cck"
```
Thanks,

Olivier

**Comment by Ilya-Zhulin** [comment]
Hello.
Result contains two string:
```
{"name":"com_cck","type":"component","creationDate":"January 2011","author":"Octopoos","copyright":"Copyright (C) 2013 SEBLOD. All Rights Reserved.","authorEmail":"contact@seblod.com","authorUrl":"http:\/\/www.seblod.com","version":"3.7.0","description":"SEBLOD 3.x - www.seblod.com \/\/ by Octopoos - www.octopoos.com","group":"","filename":"manifest"}
```
and
```
{"name":"Xmap - SEBLOD CCK Plugin","type":"plugin","creationDate":"10\/12\/2014","author":"Ilya A. Zhulin","copyright":"GNU GPL","authorEmail":"ilya.zhulin@hotmail.com","authorUrl":"seblod.pro","version":"2.0.4","description":"XMAP_CONTENT_PLUGIN_DESCRIPTION","group":""}
```
The second one is my XMap plugin.

Regards, Ilya

**Comment by olivier-at-octopoos** [comment]
This explains that...

Your XMap plugin shouldn't have 'com_cck' as extension name...

You need to change the 'name' column value for your extension to something like 'plg_content_xmap' and everything will be fine with SEBLOD upgrades.

Olivier

**Comment by Ilya-Zhulin** [comment]
ОК, I'll do it. But Xmap plugins all named by component name. I thiink, that install script has to check not only `name` but `type` also. Thank you!

**Comment by olivier-at-octopoos** [comment]
Right...

It will be done in the next release...

Quick fix in 'administrator/components/com_cck/script.php', '_getVersion' function : 

The query
```
$db->setQuery( 'SELECT manifest_cache FROM #__extensions WHERE element = "com_cck"' );
```

becomes
```
$db->setQuery( 'SELECT manifest_cache FROM #__extensions WHERE element = "com_cck" AND type = "component"' );
```

Thanks,

Olivier

**Comment by Ilya-Zhulin** [comment]
Thank you! Problem is solved
