### ISSUE TITLE
Can't save field

### ISSUE THREAD

**Issue by proweb** [Octopoos/SEBLOD#88]
Joomla 3.4.3 + Seblod 3.7.0
Something strange....

Trying to add field to default Article content type
and on Save get this:
![_626](https://cloud.githubusercontent.com/assets/680073/9026916/73ca31ea-3949-11e5-8f8a-c7cb836c4f0d.png)
![_625](https://cloud.githubusercontent.com/assets/680073/9026917/78322d5a-3949-11e5-8de8-3ecccdde2276.png)

**Comment by proweb** [comment]
Tested again.

And as I can see Save problem coming then I Use Cyrillic for Title of field.

If I use Latin - no problem.

**Comment by olivier-at-octopoos** [comment]
Hi,

We've reproduced the problem and made a fix that will be available soon (not in the next release as it has been already packaged).

Thanks,

Olivier

**Comment by sebastienheraud** [comment]
Hi Sergey/Olivier,
Merged: https://github.com/Octopoos/SEBLOD/commit/bc383074164bcf7ac4837d25b74aa0366a86ab02
Thank you!
Saba.
