### ISSUE TITLE
Order by Category title for article search & list type doesn't work

### ISSUE THREAD

**Issue by thebeuving** [Octopoos/SEBLOD#89]
If you create a list & search type for an article or related Content Type, and then try ordering by Category Title it is not possible.

You can order by Article Category Id, which orders by the actual catid field, which doesn't provide alphabetically sorting.

If you try to order by Category Title, it fails because it tries to join the category table with the cck_core table matching the category tables id column with the pk column in cck_core.

I believe this is likely a common problem, and am supplying a pull request with a fix. I would be happy to discuss other solutions with anyone, but would really like this or a related fix to make it into a near future release.

**Comment by thebeuving** [comment]
Pull request here: https://github.com/Octopoos/SEBLOD/pull/90

**Comment by olivier-at-octopoos** [comment]
Hi,

The solution is to add a 'Search Join' plugin field to your search like this:

![forum_seblod_-_administration_-_list___search_type___small__small___edit____span_class__subtitle____seblod_workshop____span___small___small_](https://cloud.githubusercontent.com/assets/6637889/9269224/ae46492c-4267-11e5-8ca6-496e34731a4c.jpg)

Than you can add your 'Category Title' field to your ordering tab and the SQL query will look like this:

![articles_with_category_title_ordering](https://cloud.githubusercontent.com/assets/6637889/9269245/e6f3f85a-4267-11e5-8f2c-d4d85fc165ee.jpg)

So, no fix needed...

Link to the plugin on the SEBLDO market:
http://www.seblod.com/products/922

Olivier

**Comment by thebeuving** [comment]
Awesome thank you, sorry for the false Issue report, I spent a lot of time searching and couldn't find anything.

I love working with seblod, just keep finding more awesome features/plugins!
