### ISSUE TITLE
Custom Attributes in Wysiwyg field

### ISSUE THREAD

**Issue by MaierGrem** [Octopoos/SEBLOD#9]
Hi all! In the wysiwyg editor field does not work custom attributes & css class.. So it should be or is it a bug?

**Comment by lionelratel** [comment]
After verification, there is no real possibility to add, in a generic way, attributes and classes in the field wysiwyg.
It depends on the type of wysiwyg and their JS script, and the mode "inline" or "modal".

**Comment by sebastienheraud** [comment]
Let's close this for now... we may reopen it later.
