### ISSUE TITLE
Select - Dynamic Ordering

### ISSUE THREAD

**Issue by ericdavisosu** [Octopoos/SEBLOD#91]
I am attempting to use the Select - Dynamic field to display the joomla vote calculation.  I am able to use this field to display the correct value.  I also tried ordering this field but it is ordering by the "value" rather than the "options name".  It seems like this field would be more useful if it ordered the field by what the user actually sees rather than what is saved to the database table.  Thank you for your time.  I enjoy using the product.

**Comment by olivier-at-octopoos** [comment]
Hi,

Not sure to understand what you mean as there's an ordering option in the field where you can set the column to order by:

![forum_seblod_-_administration_-_list___search_type___small__small___edit____span_class__subtitle____seblod_workshop____span___small___small_](https://cloud.githubusercontent.com/assets/6637889/9288168/5466b7ca-4339-11e5-8aa2-29dbe2c122aa.jpg)

Olivier

**Comment by ericdavisosu** [comment]
Thank you for the response.  I was actually talking about the ordering tab of the List and Search Type, not the "Order By" on the field itself.  I was trying to use the Select Dynamic as a way to order a List and Search Type by the rating.  I set the storage type to the article ID, set the article id as the value, and then divided the overall votes by the number of votes for the "Options Name".  This worked for displaying the average vote on the front end list, but I wanted to order the List and Search type by this field to show the highest rated content.  I am able to drag the Select Dynamic field to the ordering tab, but it just orders the list by the article ID rather than the average vote, which is what is displayed on the front end.

**Comment by olivier-at-octopoos** [comment]
Hi,

I would suggest  to post your question on the SEBLOD forum : http://www.seblod.com/community/forums as this doesn't look like a bug but more a configuration problem.

If you can also post a screenshot of your field configuration as I've done in this thread, that would be helpful for our support team to reply.

This non-issue will be closed in the coming days.

Cheers,

Olivier

**Comment by klas** [comment]
To be closed.
