### ISSUE TITLE
Form validates at Cancel Button

### ISSUE THREAD

**Issue by designbengel** [Octopoos/SEBLOD#92]
In case a form needs to be canceled the validation rules block this function, only after all required fields are filled i can cancel a form. (This happens on all forms in backend)

**Comment by olivier-at-octopoos** [comment]
Hi Elisa,

It should be fixed in 3.7.0, could you check your version please.

Cheers,

Olivier

**Comment by designbengel** [comment]
Hi Olivier,
yes you are right - sorry :)
