### ISSUE TITLE
Button Free Field Won't Render in Form without Edit Permissions

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#98]
Hi there,

The button free field will not render in a multi-stage form when it is used as a "Back" button by using the Form -> Edition settings, if the user does not have full edit permissions.

The scenario I have tested this in is where I require a user to have "edit own" permissions, which works perfectly so that the user can only edit articles they've created, and use the multi-page form features of SEBLOD. However, with "edit own" permissions, the Button Free field is not rendered. If the user is changed to have full "edit" permissions, then the button is rendered.

SEBLOD 3.7.1
Joomla 3.4.3

Thanks,
James

**Comment by Octopoos-James** [comment]
Hi again,

Following up on this with more information:

On another separate site using the Button Free field in order to create an "add new" content button for Registered users (Content type set to "Edit Own - permitted" and also "Edit - permitted" and "Create - permitted" both times to try and debug) I've noticed now the button is not rendered, when before updating it was rendered and working fine.

Something has changed with permissions either relating to the Button Free > Form setup OR with edit own permissions that has seriously altered the way these buttons behave and has now caused them to not display and break crucial functionality.

I believe this is going to / already has impacted most people who are using the multi-page form functionality of SEBLOD.

James

**Comment by olivier-at-octopoos** [comment]
Hi James,

This is almost the same behavior as for the the 'form link' in a content or list view. You have to set a core field (like the Article title) first in your form and in the case of a multi-page form, set one core field first for avery pages and it's working.

Though, as we've already fixed this for the content & list views (Issue #63), we've also done it for the form view. Fix in testing stage.

Olivier

**Comment by Octopoos-James** [comment]
Hi Olivier, 

Thanks for your reply, but I think the issue is more than this. In each case my Button Free field was positioned as the LAST CCK field in my view for each stage, with about 10 other fields before it in each stage. Does that surprise you or is it expected given your understanding of the issue?

Cheers,
James

**Comment by olivier-at-octopoos** [comment]
Tested this morning with SEBLOD 3.7.1 and a multi-page form. The content type is configured with edit own ( not edit) permissions for registered. As soon as I add the 'Article Title' field above the back button, the button is displayed.

Olivier

**Comment by sebastienheraud** [comment]
Hi,
Is this still open with 3.8.x ?
Thanks,
Saba.

**Comment by sebastienheraud** [comment]
Hi James,
Merged for 3.8.2
@oliviernolbert thanks for the fix!
Saba.
