### ISSUE TITLE
Plugin Link problem after update to S 3.7.1

### ISSUE THREAD

**Issue by paoprod** [Octopoos/SEBLOD#99]
Hi, I have notify a bug [in the Seblod Forum VIP](http://www.seblod.com/community/forums/standard-premium-memberships/plugin-link-problem-after-update-to-s-3-7-1), James Morrel suggested me to notify it here, so ...

I have a link on a Free text field made with the plugin Link on "2" linked to a form.
That's worked well until I upgrade my Seblod from 3.6.2 to 3.7.0 OR 3.7.1
When I upgrade, the link doesn't work anymore, just is print the word "Insccription" from my free text field.
I have a Custom variable on this plugin : "formation=$cck->getValue('art_id')"
If i don't enter the custom variable, the link work again but of course link to Error as the variable is not given anymore....
If I enter the custom variable, the link disappear...
The problem is also mentionned here by an other user : http://www.seblod.com/community/forums/general-discussions/update-3-7-problem
To make it work again, I change the entire folder Plugin > cck_field_link from a Seblod 3.6.2. And work again.
I know this is just a temporary solution, if you could have  an eye on this problem ?

**Comment by olivier-at-octopoos** [comment]
Hi Stefan,

This has been fixed and will be available in the next release of SEBLOD.

Thanks,

Olivier

**Comment by olivier-at-octopoos** [comment]
Hi Stefan,

This has been fixed and will be available in the next release of SEBLOD.

Thanks,

Olivier

**Comment by paoprod** [comment]
Hi Olivier,
Merci pour l'info :)

**Comment by sebastienheraud** [comment]
Hi Stefan,
Here is the fix: https://github.com/Octopoos/SEBLOD/blob/6610c9391895ffbacb7f613f6a695395641675e8/plugins/cck_field_link/cck_form/cck_form.php
Saba.

**Comment by paoprod** [comment]
Works well ! :)
Thanks a lot...
